trimAl: statisticsConsistency Class Reference
statisticsConsistency Class Reference
Helper class to handle the comparison between alignments. It also handles Consistency staticstics.
#include <statisticsConsistency.h>
Public Member Functions
void perform (char *comparesetFilePath, ReadWriteMS &ReadWriteMachine, trimAlManager &manager, char *forceFile)
bool applyWindow (int _halfWindow)
Applies a new window to the alignment.
statisticsConsistency (newAlignment *pAlignment, statisticsConsistency *pConsistency)
float * getValues ()
Static Public Member Functions
static void printStatisticsFileColumns (newAlignment &_alignment, float *compareVect)
Print the consistency value for each column from the selected alignment.
static void printStatisticsFileAcl (newAlignment &_alignment, float *compareVect)
Print the accumulated consistency value from the selected alignment.
static int compareAndChoose (newAlignment **vectAlignments, char **fileNames, float *columnsValue, int numAlignments, bool verbosity)
Method to compare a set of alignments to select the most consistent one respect the others.
To compute the consistency values we use the proportion of residue pairs per columns in the alignments to compare.
static bool forceComparison (newAlignment **vectAlignments, int numAlignments, newAlignment *selected, float *columnsValue)
Method to obtain the consistency values vector for a given alignment against a set of alignments with the same sequences.
Private Member Functions
void delete_variables ()
bool isDefinedWindow ()
Private Attributes
newAlignment * _alignment
std::ifstream compare
float * values = nullptr
float * values_windowed = nullptr
int numFiles = 0
int i = 0
int maxAminos = 0
int prevType = -1
int referFile = -1
int halfWindow = -1
int residues = -1
int * refCounter
char * line = nullptr
char c
char ** filesToCompare = nullptr
std::string nline
newAlignment ** compareAlignmentsArray = nullptr
bool appearErrors = false
Detailed Description
Helper class to handle the comparison between alignments. It also handles Consistency staticstics.
Definition at line 40 of file statisticsConsistency.h.
Member Function Documentation
applyWindow()
bool statisticsConsistency::applyWindow (int _halfWindow)
Applies a new window to the alignment.
Parameters
columns Number of columns present in the alignment.
_halfWindow Half size of window to apply.
[in,out] columnsValue Vector containing the values that should be averaged and, at the same time, vector that will contain the new averaged values.
Returns
True
Definition at line 474 of file statisticsConsistency.cpp.
References __internalReport::__reportSystem::report().
compareAndChoose()
int statisticsConsistency::compareAndChoose (newAlignment ** vectAlignments, char ** fileNames, float * columnsValue, int numAlignments, bool verbosity) static
Method to compare a set of alignments to select the most consistent one respect the others.
To compute the consistency values we use the proportion of residue pairs per columns in the alignments to compare.
Parameters
vectAlignments Alignment vector to compare and select the most consistent.
fileNames Vector containing all the filenames. Useful only if verbosity==True.
[out] columnsValue Consistency values of selected alignment.
numAlignments Number of alignments to compare.
verbosity Wether or not report by printing some results.
Returns
-1 if there was any error.
Alignment index of the selected algorithm otherwise.
Definition at line 194 of file statisticsConsistency.cpp.
References sequencesMatrix::getColumn(), newAlignment::getNumSpecies(), newAlignment::getSequenceNameOrder(), newAlignment::getSequences(), utils::initlVect(), __internalReport::__reportSystem::report(), newAlignment::SequencesMatrix, and sequencesMatrix::setOrder().
forceComparison()
bool statisticsConsistency::forceComparison (newAlignment ** vectAlignments, int numAlignments, newAlignment * selected, float * columnsValue) static
Method to obtain the consistency values vector for a given alignment against a set of alignments with the same sequences.
Parameters
vectAlignments Alignment vector to compare against the selected alignment
numAlignments Number of alignments to compare
selected Alignment to compare against the set of alignments.
[out] columnsValue Vector to fill with the consistency values.
Returns
Wether or not the method went ok.
Definition at line 368 of file statisticsConsistency.cpp.
References sequencesMatrix::getColumn(), newAlignment::getNumAminos(), newAlignment::getNumSpecies(), newAlignment::getSequenceNameOrder(), newAlignment::getSequences(), utils::initlVect(), __internalReport::__reportSystem::report(), newAlignment::SequencesMatrix, and sequencesMatrix::setOrder().
printStatisticsFileAcl()
void statisticsConsistency::printStatisticsFileAcl (newAlignment & _alignment, float * compareVect) static
Print the accumulated consistency value from the selected alignment.
Parameters
_alignment Alignment used to obtain the accumulated consistency value
compareVect Vector containing the consistency value for each column.
Definition at line 616 of file statisticsConsistency.cpp.
References utils::copyVect(), newAlignment::filename, utils::quicksort(), and newAlignment::residNumber.
Referenced by trimAlManager::print_statistics().
printStatisticsFileColumns()
void statisticsConsistency::printStatisticsFileColumns (newAlignment & _alignment, float * compareVect) static
Print the consistency value for each column from the selected alignment.
Parameters
_alignment Alignment used to obtain the accumulated consistency value
compareVect Vector containing the consistency value for each column.
Definition at line 556 of file statisticsConsistency.cpp.
References newAlignment::filename, and newAlignment::residNumber.
Referenced by trimAlManager::print_statistics().
The documentation for this class was generated from the following files:
include/Statistics/statisticsConsistency.h
source/Statistics/statisticsConsistency.cpp