trimAl: statistics::Gaps Class Reference
statistics::Gaps Class Reference
Class to handle gaps statistics.
#include <Gaps.h>
Public Member Functions
Gaps (Alignment *pAlignment, Gaps *pGaps)
Gaps (Alignment *parent)
~Gaps ()
bool applyWindow (int)
int * getGapsWindow ()
double calcCutPoint (float, float)
int calcCutPointMixSlope ()
int calcCutPoint2ndSlope ()
void printGapsColumns ()
void printGapsAcl ()
bool isDefinedWindow ()
void CalculateVectors ()
Public Attributes
Alignment * alig
int maxGaps = -1
int halfWindow = -1
int * gapsInColumn = nullptr
int * numColumnsWithGaps = nullptr
int * gapsWindow = nullptr
int * refCounter
Detailed Description
Class to handle gaps statistics.
Definition at line 39 of file Gaps.h.
Constructor & Destructor Documentation
Gaps() [1/2]
statistics::Gaps::Gaps (Alignment * pAlignment, Gaps * pGaps)
Definition at line 55 of file Gaps.cpp.
References alig, gapsInColumn, gapsWindow, maxGaps, numColumnsWithGaps, and refCounter.
Gaps() [2/2]
statistics::Gaps::Gaps (Alignment * parent) explicit
Definition at line 35 of file Gaps.cpp.
References alig, gapsInColumn, halfWindow, utils::initlVect(), maxGaps, numColumnsWithGaps, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, refCounter, and StartTiming.
~Gaps()
statistics::Gaps::~Gaps ()
Definition at line 76 of file Gaps.cpp.
References gapsInColumn, gapsWindow, numColumnsWithGaps, refCounter, and StartTiming.
Member Function Documentation
applyWindow()
bool statistics::Gaps::applyWindow (int halfW)
Definition at line 90 of file Gaps.cpp.
References alig, debug, gapsInColumn, gapsWindow, GapWindowTooBig, halfWindow, utils::initlVect(), maxGaps, numColumnsWithGaps, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, reporting::reportManager::report(), utils::roundInt(), and StartTiming.
Referenced by statistics::Manager::calculateGapStats(), and getGapsWindow().
calcCutPoint()
double statistics::Gaps::calcCutPoint (float minInputAlignment, float gapThreshold)
Definition at line 178 of file Gaps.cpp.
References alig, utils::max(), Alignment::numberOfSequences, numColumnsWithGaps, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, utils::roundInt(), and StartTiming.
Referenced by Cleaner::clean(), and Cleaner::cleanGaps().
calcCutPoint2ndSlope()
int statistics::Gaps::calcCutPoint2ndSlope ()
Definition at line 313 of file Gaps.cpp.
References alig, utils::initlVect(), utils::max(), maxGaps, Alignment::numberOfSequences, numColumnsWithGaps, Alignment::originalNumberOfResidues, and StartTiming.
Referenced by Cleaner::clean2ndSlope(), and Cleaner::cleanCombMethods().
calcCutPointMixSlope()
int statistics::Gaps::calcCutPointMixSlope ()
Definition at line 223 of file Gaps.cpp.
References alig, utils::initlVect(), utils::max(), maxGaps, numColumnsWithGaps, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, and StartTiming.
CalculateVectors()
void statistics::Gaps::CalculateVectors ()
Definition at line 590 of file Gaps.cpp.
References alig, gapsInColumn, maxGaps, numColumnsWithGaps, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, Alignment::saveSequences, and Alignment::sequences.
Referenced by statistics::Manager::calculateGapStats().
getGapsWindow()
int * statistics::Gaps::getGapsWindow ()
Definition at line 160 of file Gaps.cpp.
References applyWindow(), gapsInColumn, gapsWindow, halfWindow, isDefinedWindow(), and StartTiming.
Referenced by Alignment::alignmentSummaryHTML(), Alignment::alignmentSummarySVG(), statistics::Similarity::calculateVectors(), Cleaner::clean(), Cleaner::clean2ndSlope(), Cleaner::cleanCombMethods(), Cleaner::cleanGaps(), Cleaner::cleanNoAllGaps(), and Cleaner::removeOnlyTerminal().
isDefinedWindow()
bool statistics::Gaps::isDefinedWindow ()
Definition at line 152 of file Gaps.cpp.
References halfWindow, and StartTiming.
Referenced by getGapsWindow().
printGapsAcl()
void statistics::Gaps::printGapsAcl ()
Definition at line 461 of file Gaps.cpp.
References alig, Alignment::filename, maxGaps, numColumnsWithGaps, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, and StartTiming.
Referenced by statistics::Manager::printStatisticsGapsTotal().
printGapsColumns()
void statistics::Gaps::printGapsColumns ()
Definition at line 384 of file Gaps.cpp.
References alig, utils::copyVect(), Alignment::filename, gapsInColumn, gapsWindow, halfWindow, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, and StartTiming.
Referenced by statistics::Manager::printStatisticsGapsColumns().
Member Data Documentation
alig
Alignment* statistics::Gaps::alig
Definition at line 44 of file Gaps.h.
Referenced by applyWindow(), calcCutPoint(), calcCutPoint2ndSlope(), calcCutPointMixSlope(), CalculateVectors(), Gaps(), printGapsAcl(), and printGapsColumns().
gapsInColumn
int* statistics::Gaps::gapsInColumn = nullptr
Definition at line 49 of file Gaps.h.
Referenced by applyWindow(), CalculateVectors(), Gaps(), getGapsWindow(), printGapsColumns(), and ~Gaps().
gapsWindow
int* statistics::Gaps::gapsWindow = nullptr
Definition at line 51 of file Gaps.h.
Referenced by applyWindow(), Gaps(), getGapsWindow(), printGapsColumns(), and ~Gaps().
halfWindow
int statistics::Gaps::halfWindow = -1
Definition at line 47 of file Gaps.h.
Referenced by applyWindow(), Gaps(), getGapsWindow(), isDefinedWindow(), and printGapsColumns().
maxGaps
int statistics::Gaps::maxGaps = -1
Definition at line 46 of file Gaps.h.
Referenced by applyWindow(), calcCutPoint2ndSlope(), calcCutPointMixSlope(), CalculateVectors(), Gaps(), printGapsAcl(), and trimAlManager::svg_stats_out().
numColumnsWithGaps
int* statistics::Gaps::numColumnsWithGaps = nullptr
Definition at line 50 of file Gaps.h.
Referenced by applyWindow(), calcCutPoint(), calcCutPoint2ndSlope(), calcCutPointMixSlope(), CalculateVectors(), Gaps(), printGapsAcl(), trimAlManager::svg_stats_out(), and ~Gaps().
refCounter
int* statistics::Gaps::refCounter
Definition at line 52 of file Gaps.h.
Referenced by Gaps(), and ~Gaps().
The documentation for this class was generated from the following files:
/home/vfernandez/git/trimAl/include/Statistics/Gaps.h
/home/vfernandez/git/trimAl/source/Statistics/Gaps.cpp