trimAl: statistics::Similarity Class Reference
statistics::Similarity Class Reference
Class to handle the calculation relative to similarity.
This class is narrowly connected to similarityMatrix, as the latter contains the information to calculate the similarity of the alignment.
#include <Similarity.h>
Public Member Functions
Similarity (Alignment *parentAlignment, Similarity *mold)
void calculateMatrixIdentity ()
Computes the matrix identity between alignment's columns.
Similarity (Alignment *parentAlignment)
Constructor without any parameters.
~Similarity ()
Destructor.
bool calculateVectors (bool cutByGap=true)
Method to calculate the similarity values of a alignment matrix.
bool applyWindow (int halfW)
Allows us compute the conservationWindow's values.
bool isDefinedWindow ()
Returns if a windows size value has been defined or not.
float * getMdkWindowedVector ()
This methods returns a pointer to conservationWindow's vector.
bool setSimilarityMatrix (similarityMatrix *sm)
Stores a valid similarity matrix point to use.
bool isSimMatrixDef ()
Returns if a similarity matrix is being used or not.
double calcCutPoint (float baseLine, float conservationPct)
Computes and selects the cut point values based on similarity's values.
void printConservationColumns ()
Prints the similarity's value for each alignment's column.
void printConservationAcl ()
Computes and prints the accumulative statistics associated to the alignment.
Public Attributes
Alignment * alig
int halfWindow = -1
Half Window used on the calculation of the similarity.
float * MDK = nullptr
Raw similarity values.
float * MDK_Window = nullptr
Windowed convervation values.
float ** matrixIdentity = nullptr
Identity weight matrix between alignment rows.
similarityMatrix * simMatrix = nullptr
Similarity matrix used to similarity calculations.
int * refCounter
Counter of how many other instances share the same information.
Detailed Description
Class to handle the calculation relative to similarity.
This class is narrowly connected to similarityMatrix, as the latter contains the information to calculate the similarity of the alignment.
Definition at line 52 of file Similarity.h.
Constructor & Destructor Documentation
Similarity() [1/2]
statistics::Similarity::Similarity (Alignment * parentAlignment, Similarity * mold)
Definition at line 56 of file Similarity.cpp.
References alig, halfWindow, MDK, MDK_Window, refCounter, and simMatrix.
Referenced by statistics::Manager::Manager().
Similarity() [2/2]
statistics::Similarity::Similarity (Alignment * parentAlignment) explicit
Constructor without any parameters.
Definition at line 40 of file Similarity.cpp.
References alig, utils::initlVect(), MDK, Alignment::originalNumberOfResidues, refCounter, and simMatrix.
Referenced by statistics::Manager::calculateConservationStats(), and statistics::Manager::setSimilarityMatrix().
~Similarity()
statistics::Similarity::~Similarity ()
Destructor.
Definition at line 75 of file Similarity.cpp.
References alig, matrixIdentity, MDK, MDK_Window, Alignment::numberOfSequences, and refCounter.
Member Function Documentation
applyWindow()
bool statistics::Similarity::applyWindow (int halfW)
Allows us compute the conservationWindow's values.
Parameters
halfW Half window size to apply.
Returns
False if there is a previously computed vector for this window size or half window size is greater than 1/4 of the alignment length.
Definition at line 271 of file Similarity.cpp.
References alig, calculateVectors(), debug, halfWindow, MDK, MDK_Window, Alignment::originalNumberOfResidues, reporting::reportManager::report(), and SimilarityWindowTooBig.
Referenced by statistics::Manager::calculateConservationStats(), and getMdkWindowedVector().
calcCutPoint()
double statistics::Similarity::calcCutPoint (float baseLine, float conservationPct)
Computes and selects the cut point values based on similarity's values.
Parameters
baseLine Percentage of columns desired.
conservationPct Percentage of similarity desired.
Definition at line 381 of file Similarity.cpp.
References alig, utils::copyVect(), getMdkWindowedVector(), Alignment::originalNumberOfResidues, and utils::quicksort().
Referenced by Cleaner::clean(), and Cleaner::cleanConservation().
calculateMatrixIdentity()
void statistics::Similarity::calculateMatrixIdentity ()
Computes the matrix identity between alignment's columns.
Definition at line 97 of file Similarity.cpp.
References AA, alig, Alignment::getAlignmentType(), matrixIdentity, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, and Alignment::sequences.
Referenced by calculateVectors().
calculateVectors()
bool statistics::Similarity::calculateVectors (bool cutByGap = true)
Method to calculate the similarity values of a alignment matrix.
Parameters
cutByGap Wheter to cut by gap or not
Definition at line 157 of file Similarity.cpp.
References AA, alig, statistics::Manager::calculateGapStats(), calculateMatrixIdentity(), statistics::Manager::gaps, Alignment::getAlignmentType(), statistics::similarityMatrix::getDistance(), statistics::Gaps::getGapsWindow(), matrixIdentity, MDK, Alignment::numberOfResidues, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, Alignment::sequences, simMatrix, Alignment::Statistics, and utils::toUpper().
Referenced by applyWindow(), and statistics::Manager::calculateConservationStats().
getMdkWindowedVector()
float * statistics::Similarity::getMdkWindowedVector ()
This methods returns a pointer to conservationWindow's vector.
Returns
Similarity window vector.
Definition at line 338 of file Similarity.cpp.
References applyWindow(), halfWindow, isDefinedWindow(), MDK, and MDK_Window.
Referenced by Alignment::alignmentSummaryHTML(), Alignment::alignmentSummarySVG(), calcCutPoint(), Cleaner::clean(), Cleaner::cleanCombMethods(), Cleaner::cleanConservation(), and Alignment::statSVG().
isDefinedWindow()
bool statistics::Similarity::isDefinedWindow ()
Returns if a windows size value has been defined or not.
Returns
True if a windows size has been defined.False otherwise.
Definition at line 330 of file Similarity.cpp.
References halfWindow.
Referenced by statistics::Manager::calculateConservationStats(), and getMdkWindowedVector().
isSimMatrixDef()
bool statistics::Similarity::isSimMatrixDef ()
Returns if a similarity matrix is being used or not.
Returns
True if there is a similarity matrix set, False otherwise.
Definition at line 373 of file Similarity.cpp.
References simMatrix.
Referenced by statistics::Manager::calculateConservationStats().
printConservationAcl()
void statistics::Similarity::printConservationAcl ()
Computes and prints the accumulative statistics associated to the alignment.
Definition at line 483 of file Similarity.cpp.
References alig, utils::copyVect(), Alignment::filename, MDK, MDK_Window, Alignment::originalNumberOfResidues, and utils::quicksort().
Referenced by statistics::Manager::printStatisticsConservationTotal().
printConservationColumns()
void statistics::Similarity::printConservationColumns ()
Prints the similarity's value for each alignment's column.
Definition at line 423 of file Similarity.cpp.
References alig, Alignment::filename, MDK, MDK_Window, and Alignment::originalNumberOfResidues.
Referenced by statistics::Manager::printStatisticsConservationColumns().
setSimilarityMatrix()
bool statistics::Similarity::setSimilarityMatrix (similarityMatrix * sm)
Stores a valid similarity matrix point to use.
Parameters
sm Similarity matrix pointer to associate.
Returns
True if sm is valid, False if it's null
Definition at line 355 of file Similarity.cpp.
References simMatrix.
Referenced by statistics::Manager::calculateConservationStats(), and statistics::Manager::setSimilarityMatrix().
Member Data Documentation
alig
Alignment* statistics::Similarity::alig
Definition at line 57 of file Similarity.h.
Referenced by applyWindow(), calcCutPoint(), calculateMatrixIdentity(), calculateVectors(), printConservationAcl(), printConservationColumns(), Similarity(), and ~Similarity().
halfWindow
int statistics::Similarity::halfWindow = -1
Half Window used on the calculation of the similarity.
Definition at line 60 of file Similarity.h.
Referenced by applyWindow(), getMdkWindowedVector(), isDefinedWindow(), and Similarity().
matrixIdentity
float** statistics::Similarity::matrixIdentity = nullptr
Identity weight matrix between alignment rows.
Definition at line 69 of file Similarity.h.
Referenced by calculateMatrixIdentity(), calculateVectors(), and ~Similarity().
MDK
float* statistics::Similarity::MDK = nullptr
Raw similarity values.
Definition at line 64 of file Similarity.h.
Referenced by applyWindow(), calculateVectors(), getMdkWindowedVector(), printConservationAcl(), printConservationColumns(), Similarity(), and ~Similarity().
MDK_Window
float* statistics::Similarity::MDK_Window = nullptr
Windowed convervation values.
Definition at line 66 of file Similarity.h.
Referenced by applyWindow(), getMdkWindowedVector(), printConservationAcl(), printConservationColumns(), Similarity(), and ~Similarity().
refCounter
int* statistics::Similarity::refCounter
Counter of how many other instances share the same information.
Definition at line 75 of file Similarity.h.
Referenced by Similarity(), and ~Similarity().
simMatrix
similarityMatrix* statistics::Similarity::simMatrix = nullptr
Similarity matrix used to similarity calculations.
Definition at line 72 of file Similarity.h.
Referenced by calculateVectors(), isSimMatrixDef(), setSimilarityMatrix(), and Similarity().
The documentation for this class was generated from the following files:
/home/vfernandez/git/MyFork/include/Statistics/Similarity.h
/home/vfernandez/git/MyFork/source/Statistics/Similarity.cpp