trimAl: Cleaner Class Reference
Cleaner Class Reference
Submodule contained by Alignment .
#include <Cleaner.h>
Public Member Functions
int selectMethod ()
Method that selects the best cleaning method based on statistics of the alignment.
Alignment * cleanByCutValueOverpass (double cut, float baseLine, const int *gInCol, bool complementary)
Method to clean an alignment.
It removes sequences that overpass or equals a certain threshold.
The function detects if it would clean too many sequences, and relaxes the threshold until we have enough sequences to achieve the given percentage desired to keep.
To achieve this, the method starts in the middle of the sequence and, alternating sides, adds column one by one.
.
Alignment * cleanByCutValueFallBehind (float cut, float baseLine, const float *ValueVect, bool complementary)
Method to clean an alignment.
It removes sequences that fall behind a certain threshold.
The function detects if it would clean too many sequences, and relaxes the threshold until we have enough sequences to achieve the given percentage desired to keep.
To achieve this, the method starts in the middle of the sequence and, alternating sides, adds column one by one.
Alignment * cleanByCutValueOverpassOrEquals (double cutGaps, const int *gInCol, float baseLine, float cutCons, const float *MDK_Win, bool complementary)
Method to clean an alignment.
It removes sequences that overpass or equals the gap threshold but fall behind the similarity threshold.
The function detects if it would clean too many sequences, and relaxes both thresholds until we have enough sequences to achieve the given percentage desired to keep.
To achieve this, the method starts in the middle of the sequence and, alternating sides, adds column one by one.
Alignment * cleanStrict (int gapCut, const int *gInCol, float simCut, const float *MDK_W, bool complementary, bool variable)
Method to clean an alignment. It carries out strict and strictplus.
It removes sequences that overpass the gap threshold but fall behind the similarity threshold.
The function recovers those columns that, by themselves would be rejected, but it's neighbours (3 of 4) don't.
Column blocks that don't have a minimum size set by the method itself, will be removed too.
Alignment * cleanOverlapSeq (float minimumOverlap, float *overlapSeq, bool complementary)
Method to trim an alignment based on a minimum sequence overlap threshold.
The method selects a combination of parameters to maximize the final number of columns in the new alignment.
.
Alignment * cleanGaps (float baseLine, float gapsPct, bool complementary)
Method to trim an alignment based on the gap distribution values. Column blocks that don't have a minimum size set by the method itself, will be removed too.
Alignment * cleanConservation (float baseLine, float conservationPct, bool complementary)
Method to trim an alignment based on the similarity distribution values.
Alignment * clean (float baseLine, float GapsPct, float conservationPct, bool complementary)
Method to trim an alignment based on the similarity and gaps distribution values.
.
Alignment * cleanCompareFile (float cutpoint, float baseLine, float *vectValues, bool complementary)
Method to trim an alignment based on consistency values obtained from a dataset of alignments.
The function computes the optimal parameter combination values to trim an alignment based on the consistency value from the comparison among a dataset of alignments with the same sequences.
bool calculateSpuriousVector (float overlap, float *spuriousVector)
Method to compute the overlap values.
See Alignment::overlaps.
Alignment * cleanSpuriousSeq (float overlapColumn, float minimumOverlap, bool complementary)
Method to remove sequences missaligned with the rest of sequences in the alignment.
For each residue in the sequence, it tests it's similarity. If the similarity of that residue is higher than overlapColumn value, it counts as a hit for the sequence.
After calculating the number of hits for the sequence, it removes the sequence if it has a proportion hits/residues lower tan minimumOverlap.
Alignment * clean2ndSlope (bool complementary)
Method that carries the gappyout approach.
This methods calculates the slope in gaps distribution on the original alignment.
Then, it compares groups of three consecutive residues, searching for the group with the most abrupt change in slope.
When found, the first residue is taken as the cutpoint for the sequences.
Alignment * cleanCombMethods (bool complementary, bool variable)
Method to clean an alignment. It carries out strict and strictplus.
The method:
Alignment * cleanNoAllGaps (bool complementary)
Method to remove columns composed only by gaps
This method is specially useful when we remove missaligned sequences from a given alignment.
Alignment * removeColumns (int *columns, int init, int size, bool complementary)
Method to remove columns, expressed as ranges.
Alignment * removeSequences (int *seqs, int init, int size, bool complementary)
Method to remove sequences, expressed as ranges.
Alignment * getClustering (float identityThreshold)
Method to select the most representative sequence (the longest one) for each cluster from the input alignment to generate a new alignment.
float getCutPointClusters (int clusterNumber)
Method that calculates the optimal cut point for a given clusters number.
The idea is to obtain a cutpoint that can be used to obtain as sequences as clusterNumber.
void removeSmallerBlocks (int blockSize, Alignment &original)
Method to remove blocks of columns with no rejected residue smaller than a given size.
bool removeOnlyTerminal ()
Method to detect right and left borders. Borders are the first column found with no gaps.
Everything between the borders are kept in the trimmed alignments.
void removeAllGapsSeqsAndCols (bool seqs=true, bool cols=true)
Method that identifies and removes columns and sequences composed only by gaps.
void setTrimTerminalGapsFlag (bool terminalOnly_)
Setter method to Terminal Only Flag.
void setBoundaries (int *boundaries)
Boundaries setter.
void calculateSeqIdentity ()
Method to calculate identities between the sequences from the alignment.
See Alignment::identities.
void calculateRelaxedSeqIdentity ()
Method that makes a raw approximation of sequence identity computation.
.
int * calculateRepresentativeSeq (float maximumIdent)
Method to assign sequences to clusters.
Clusters are calculated following this flow:
void computeComplementaryAlig (bool residues, bool sequences)
Method for computing the complementary alignment.
Complementary alignment is an alignment containing all sequences and columns that the original alignment would reject.
It inverses the saveResidues / saveSequences tags.
Public Attributes
bool terminalGapOnly
Flag for trimming only on the terminal positions.
bool keepSequences
Flag for keeping sequences even when they are composed only by gaps.
int blockSize
Block size to use on the cleaning methods.
int left_boundary
left boundary of the alignment
int right_boundary
right boundary of the alignment
Private Member Functions
Cleaner (Alignment *parent)
Class Constructor - Called by Alignment.
Cleaner (Alignment *parent, Cleaner *mold)
Copy Constructor - Called by Alignment.
Private Attributes
Alignment * alig
Pointer to the alignment that contains this object.
Friends
class Alignment
Detailed Description
Submodule contained by Alignment .
Complementary parameter
All cleaning methods contains a boolean flag called 'complementary' .
If set to true, the function will return a new alignment that contains the sequences and residues that method would reject.
Otherwise it returns the cleaned version of the original alignment this object belongs to.
The use of this flag - complementary - is not recommended.
Complementarity is now performed when ALL methods have been applied.
Definition at line 27 of file Cleaner.h.
Constructor & Destructor Documentation
Cleaner() [1/2]
Cleaner::Cleaner (Alignment * parent) explicit private
Class Constructor - Called by Alignment.
Definition at line 1593 of file Cleaner.cpp.
References alig, blockSize, keepSequences, left_boundary, right_boundary, StartTiming, and terminalGapOnly.
Cleaner() [2/2]
Cleaner::Cleaner (Alignment * parent, Cleaner * mold) private
Copy Constructor - Called by Alignment.
Definition at line 1608 of file Cleaner.cpp.
References alig, blockSize, keepSequences, left_boundary, right_boundary, StartTiming, and terminalGapOnly.
Member Function Documentation
calculateRelaxedSeqIdentity()
void Cleaner::calculateRelaxedSeqIdentity ()
Method that makes a raw approximation of sequence identity computation.
.
Warning
Not In Use
Note
Designed for reducing comparisons for huge alignments.
Definition at line 1471 of file Cleaner.cpp.
References alig, Alignment::identities, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, Alignment::saveResidues, Alignment::saveSequences, Alignment::sequences, and StartTiming.
calculateRepresentativeSeq()
int * Cleaner::calculateRepresentativeSeq (float maximumIdent)
Method to assign sequences to clusters.
Clusters are calculated following this flow:
Select the longest sequence and use it as representative of the first cluster.
Using the previously computed identity values, check if second longest sequence should be part of cluster of first sequence. This is computed using the identity value in comparison with a threshold.
If the second sequence should be part of the existing cluster, we add it. Otherwise we create a new cluster and use this sequence as representative for this new cluster.
Continue with the rest of sequences, comparing them with the representatives of existing clusters. If a sequence can pertain to more than one cluster, we choose the one that maximizes the identity value with the representative sequence.
Parameters
maximumIdent Identity threshold used to decide if a sequence should be part of a cluster or create a new one.
Returns
Vector that contains the clustering info.
The first item in the vector contains it's size.
Definition at line 1513 of file Cleaner.cpp.
References alig, calculateSeqIdentity(), Alignment::Cleaning, Alignment::identities, utils::max(), Alignment::originalNumberOfSequences, utils::quicksort(), utils::removeCharacter(), Alignment::saveSequences, Alignment::sequences, and StartTiming.
Referenced by getClustering().
calculateSeqIdentity()
void Cleaner::calculateSeqIdentity ()
Method to calculate identities between the sequences from the alignment.
See Alignment::identities.
Definition at line 1422 of file Cleaner.cpp.
References AA, alig, Alignment::getAlignmentType(), Alignment::identities, Alignment::numberOfResidues, Alignment::originalNumberOfSequences, Alignment::saveResidues, Alignment::saveSequences, Alignment::sequences, and StartTiming.
Referenced by calculateRepresentativeSeq(), getCutPointClusters(), Alignment::printSeqIdentity(), and selectMethod().
calculateSpuriousVector()
bool Cleaner::calculateSpuriousVector (float overlap, float * spuriousVector)
Method to compute the overlap values.
See Alignment::overlaps.
Parameters
overlap Overlap threshold.
[out] spuriousVector Pointer to the spuriousVector to fill.
Returns
True if the calculation went ok.
False otherwise.
This should happen only if you pass a null pointer instead of a spuriousVector.
Definition at line 827 of file Cleaner.cpp.
References AA, alig, Alignment::getAlignmentType(), Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, Alignment::sequences, and StartTiming.
Referenced by cleanSpuriousSeq().
clean()
Alignment * Cleaner::clean (float baseLine, float GapsPct, float conservationPct, bool complementary)
Method to trim an alignment based on the similarity and gaps distribution values.
.
Parameters
baseLine Minimum percentage of columns to conserve in the new alignment.
GapsPct Maximum percentage of gaps per column.
conservationPct Minimum value of similarity per column to keep the column.
complementary Whether or not to return the complementary version of the trimmed alignment.
Take in mind
If baseLine is too strict, the other two will be relaxed to obtain the minimum percentage desired.
Returns
Pointer to the cleaned alignment.
Definition at line 756 of file Cleaner.cpp.
References alig, statistics::Gaps::calcCutPoint(), statistics::Similarity::calcCutPoint(), statistics::Manager::calculateConservationStats(), statistics::Manager::calculateGapStats(), cleanByCutValueOverpassOrEquals(), statistics::Manager::gaps, statistics::Gaps::getGapsWindow(), statistics::Similarity::getMdkWindowedVector(), statistics::Manager::similarity, StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::CleanResiduesNonAuto().
clean2ndSlope()
Alignment * Cleaner::clean2ndSlope (bool complementary)
Method that carries the gappyout approach.
This methods calculates the slope in gaps distribution on the original alignment.
Then, it compares groups of three consecutive residues, searching for the group with the most abrupt change in slope.
When found, the first residue is taken as the cutpoint for the sequences.
Parameters
complementary Whether or not to return the complementary version of the trimmed alignment.
Definition at line 929 of file Cleaner.cpp.
References alig, statistics::Gaps::calcCutPoint2ndSlope(), statistics::Manager::calculateGapStats(), cleanByCutValueOverpass(), statistics::Manager::gaps, statistics::Gaps::getGapsWindow(), StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::CleanResiduesAuto().
cleanByCutValueFallBehind()
Alignment * Cleaner::cleanByCutValueFallBehind (float cut, float baseLine, const float * ValueVect, bool complementary)
Method to clean an alignment.
It removes sequences that fall behind a certain threshold.
The function detects if it would clean too many sequences, and relaxes the threshold until we have enough sequences to achieve the given percentage desired to keep.
To achieve this, the method starts in the middle of the sequence and, alternating sides, adds column one by one.
Parameters
cut Gap cut value to use.
baseLine Percent of sequences to keep
ValueVect Vector that contains the gaps present on each column.
complementary Whether or not to return the complementary version of the trimmed alignment.
Returns
Pointer to the cleaned alignment.
Definition at line 203 of file Cleaner.cpp.
References alig, Alignment, blockSize, Alignment::Cleaning, Alignment::numberOfResidues, Alignment::originalNumberOfResidues, removeAllGapsSeqsAndCols(), removeSmallerBlocks(), utils::roundInt(), Alignment::saveResidues, and StartTiming.
Referenced by cleanCompareFile(), and cleanConservation().
cleanByCutValueOverpass()
Alignment * Cleaner::cleanByCutValueOverpass (double cut, float baseLine, const int * gInCol, bool complementary)
Method to clean an alignment.
It removes sequences that overpass or equals a certain threshold.
The function detects if it would clean too many sequences, and relaxes the threshold until we have enough sequences to achieve the given percentage desired to keep.
To achieve this, the method starts in the middle of the sequence and, alternating sides, adds column one by one.
.
Parameters
cut Cut value to use. If a column has a value lower or equal to the cut value, it is removed.
baseLine Percent of sequences to keep
gInCol Vector that contains the values that will be tested for each column.
complementary Whether or not to return the complementary version of the trimmed alignment.
Returns
Pointer to the cleaned alignment.
Definition at line 62 of file Cleaner.cpp.
References alig, Alignment, blockSize, Alignment::Cleaning, Alignment::numberOfResidues, Alignment::originalNumberOfResidues, utils::quicksort(), removeAllGapsSeqsAndCols(), removeSmallerBlocks(), utils::roundInt(), Alignment::saveResidues, and StartTiming.
Referenced by clean2ndSlope(), cleanGaps(), and cleanNoAllGaps().
cleanByCutValueOverpassOrEquals()
Alignment * Cleaner::cleanByCutValueOverpassOrEquals (double cutGaps, const int * gInCol, float baseLine, float cutCons, const float * MDK_Win, bool complementary)
Method to clean an alignment.
It removes sequences that overpass or equals the gap threshold but fall behind the similarity threshold.
The function detects if it would clean too many sequences, and relaxes both thresholds until we have enough sequences to achieve the given percentage desired to keep.
To achieve this, the method starts in the middle of the sequence and, alternating sides, adds column one by one.
Parameters
cutGaps Gap cut value to use.
baseLine Percent of sequences to keep
gInCol Vector that contains the gaps present on each column.
MDK_Win Vector that contains similarity value for each column.
cutCons Minimum similarity value to keep a column in the alignment.
complementary Whether or not to return the complementary version of the trimmed alignment.
Returns
Pointer to the cleaned alignment.
Definition at line 329 of file Cleaner.cpp.
References alig, Alignment, blockSize, Alignment::Cleaning, Alignment::numberOfResidues, Alignment::originalNumberOfResidues, utils::quicksort(), removeAllGapsSeqsAndCols(), removeSmallerBlocks(), utils::roundInt(), Alignment::saveResidues, and StartTiming.
Referenced by clean().
cleanCombMethods()
Alignment * Cleaner::cleanCombMethods (bool complementary, bool variable)
Method to clean an alignment. It carries out strict and strictplus.
The method:
Computes gaps values and gap cut point of the alignment.
Computes similarity values and similarity cut point of the alignment.
Calls the cleanStrict method with these values and returns its output.
Parameters
complementary Whether or not to return the complementary version of the trimmed alignment.
variable Whether to use a variable block length. If false, block will be size 5. Else, it will use 1% of the alignment length, with a minimum of 3 and maximum of 12. This value will be overwritten if blockSize (of this object) is bigger than 0.
Returns
Pointer to the cleaned alignment returned by cleanStrict using the parameters calculated in this function.
Definition at line 952 of file Cleaner.cpp.
References alig, statistics::Gaps::calcCutPoint2ndSlope(), statistics::Manager::calculateConservationStats(), cleanStrict(), statistics::Manager::gaps, statistics::Gaps::getGapsWindow(), statistics::Similarity::getMdkWindowedVector(), utils::initlVect(), Alignment::originalNumberOfResidues, utils::quicksort(), Alignment::saveResidues, statistics::Manager::similarity, StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::CleanResiduesAuto().
cleanCompareFile()
Alignment * Cleaner::cleanCompareFile (float cutpoint, float baseLine, float * vectValues, bool complementary)
Method to trim an alignment based on consistency values obtained from a dataset of alignments.
The function computes the optimal parameter combination values to trim an alignment based on the consistency value from the comparison among a dataset of alignments with the same sequences.
Parameters
cutpoint Hint of Gap cut point. May be used if it's lower than the minimum percentage threshold.
baseLine Minimum percentage of columns to conserve in the new alignment.
vectValues Vector with alignment consistency values
complementary Whether or not to return the complementary version of the trimmed alignment.
Returns
Pointer to the cleaned alignment.
Definition at line 792 of file Cleaner.cpp.
References alig, cleanByCutValueFallBehind(), utils::copyVect(), utils::min(), Alignment::originalNumberOfResidues, utils::quicksort(), and StartTiming.
Referenced by trimAlManager::CleanResiduesNonAuto().
cleanConservation()
Alignment * Cleaner::cleanConservation (float baseLine, float conservationPct, bool complementary)
Method to trim an alignment based on the similarity distribution values.
Parameters
baseLine Minimum percentage of columns to conserve in the new alignment.
conservationPct Minimum value of similarity per column to keep the column.
complementary Whether or not to return the complementary version of the trimmed alignment.
Returns
Pointer to the cleaned alignment.
Definition at line 732 of file Cleaner.cpp.
References alig, statistics::Similarity::calcCutPoint(), statistics::Manager::calculateConservationStats(), cleanByCutValueFallBehind(), statistics::Similarity::getMdkWindowedVector(), statistics::Manager::similarity, StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::CleanResiduesNonAuto().
cleanGaps()
Alignment * Cleaner::cleanGaps (float baseLine, float gapsPct, bool complementary)
Method to trim an alignment based on the gap distribution values. Column blocks that don't have a minimum size set by the method itself, will be removed too.
Parameters
baseLine Minimum percentage of columns to conserve in the new alignment.
gapsPct Maximum percentage of gaps per column.
complementary Whether or not to return the complementary version of the trimmed alignment.
Returns
Pointer to the cleaned alignment.
Definition at line 708 of file Cleaner.cpp.
References alig, statistics::Gaps::calcCutPoint(), statistics::Manager::calculateGapStats(), cleanByCutValueOverpass(), statistics::Manager::gaps, statistics::Gaps::getGapsWindow(), StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::CleanResiduesAuto(), and trimAlManager::CleanResiduesNonAuto().
cleanNoAllGaps()
Alignment * Cleaner::cleanNoAllGaps (bool complementary)
Method to remove columns composed only by gaps
This method is specially useful when we remove missaligned sequences from a given alignment.
Parameters
complementary Whether or not to return the complementary version of the trimmed alignment.
Although this method contains a complementary flag, setting this up would return an alignment full of gaps-only columns.
Definition at line 1021 of file Cleaner.cpp.
References alig, statistics::Manager::calculateGapStats(), cleanByCutValueOverpass(), statistics::Manager::gaps, statistics::Gaps::getGapsWindow(), Alignment::originalNumberOfSequences, StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::CleanResiduesAuto(), and trimAlManager::CleanSequences().
cleanOverlapSeq()
Alignment * Cleaner::cleanOverlapSeq (float minimumOverlap, float * overlapSeq, bool complementary)
Method to trim an alignment based on a minimum sequence overlap threshold.
The method selects a combination of parameters to maximize the final number of columns in the new alignment.
.
Parameters
minimumOverlap Min overlap to keep a sequence.
overlapSeq Vector containing the overlap for each column.
complementary Whether or not to return the complementary version of the trimmed alignment.
Returns
Pointer to the cleaned alignment.
Definition at line 686 of file Cleaner.cpp.
References alig, Alignment, Alignment::Cleaning, Alignment::originalNumberOfSequences, removeAllGapsSeqsAndCols(), Alignment::saveSequences, and StartTiming.
Referenced by cleanSpuriousSeq().
cleanSpuriousSeq()
Alignment * Cleaner::cleanSpuriousSeq (float overlapColumn, float minimumOverlap, bool complementary)
Method to remove sequences missaligned with the rest of sequences in the alignment.
For each residue in the sequence, it tests it's similarity. If the similarity of that residue is higher than overlapColumn value, it counts as a hit for the sequence.
After calculating the number of hits for the sequence, it removes the sequence if it has a proportion hits/residues lower tan minimumOverlap.
Parameters
overlapColumn Minimum similarity value that a residue needs to be considered a hit.
minimumOverlap Minimum proportion of hits that a sequence needs to be kept in the new alignment.
complementary Whether or not to return the complementary version of the trimmed alignment.
Returns
Pointer to the cleaned alignment. \
Definition at line 906 of file Cleaner.cpp.
References alig, calculateSpuriousVector(), cleanOverlapSeq(), Alignment::originalNumberOfSequences, and StartTiming.
Referenced by trimAlManager::CleanSequences().
cleanStrict()
Alignment * Cleaner::cleanStrict (int gapCut, const int * gInCol, float simCut, const float * MDK_W, bool complementary, bool variable)
Method to clean an alignment. It carries out strict and strictplus.
It removes sequences that overpass the gap threshold but fall behind the similarity threshold.
The function recovers those columns that, by themselves would be rejected, but it's neighbours (3 of 4) don't.
Column blocks that don't have a minimum size set by the method itself, will be removed too.
Parameters
gapCut Gap cut value to use.
gInCol Vector that contains the gaps present on each column.
simCut Minimum similarity value to keep a column.
MDK_W Vector that contains the similarity of each column.
complementary Whether or not to return the complementary version of the trimmed alignment.
variable Whether to use a variable block length. If false, block will be size 5. Else, it will use 1% of the alignment length, with a minimum of 3 and maximum of 12. This value will be overwritten if blockSize (of this object) is bigger than 0.
Returns
Pointer to the cleaned alignment.
Definition at line 485 of file Cleaner.cpp.
References alig, Alignment, blockSize, Alignment::Cleaning, Alignment::numberOfResidues, Alignment::originalNumberOfResidues, removeAllGapsSeqsAndCols(), utils::roundInt(), Alignment::saveResidues, and StartTiming.
Referenced by cleanCombMethods().
computeComplementaryAlig()
void Cleaner::computeComplementaryAlig (bool residues, bool sequences)
Method for computing the complementary alignment.
Complementary alignment is an alignment containing all sequences and columns that the original alignment would reject.
It inverses the saveResidues / saveSequences tags.
Parameters
residues Whether to reverse resiudes tags.
sequences Whether to reverse sequences tags.
Definition at line 1577 of file Cleaner.cpp.
References alig, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, Alignment::saveResidues, Alignment::saveSequences, and StartTiming.
Referenced by trimAlManager::postprocess_alignment().
getClustering()
Alignment * Cleaner::getClustering (float identityThreshold)
Method to select the most representative sequence (the longest one) for each cluster from the input alignment to generate a new alignment.
Parameters
identityThreshold Threshold used to assign sequences to clusters.
If identity between representative sequence of the cluster and sequence to assign is superior to this threshold and no other cluster has a better identity with its representative, it will be assigned to that cluster.
Definition at line 1183 of file Cleaner.cpp.
References alig, Alignment, calculateRepresentativeSeq(), Alignment::numberOfSequences, Alignment::originalNumberOfSequences, Alignment::saveSequences, and StartTiming.
Referenced by trimAlManager::CleanSequences().
getCutPointClusters()
float Cleaner::getCutPointClusters (int clusterNumber)
Method that calculates the optimal cut point for a given clusters number.
The idea is to obtain a cutpoint that can be used to obtain as sequences as clusterNumber.
Parameters
clusterNumber Number of representative sequences to obtain.
Returns
CutPoint to obtain clusterNumber sequences.
Definition at line 1040 of file Cleaner.cpp.
References alig, calculateSeqIdentity(), Alignment::identities, utils::max(), utils::min(), Alignment::numberOfSequences, Alignment::originalNumberOfSequences, utils::quicksort(), utils::removeCharacter(), Alignment::saveSequences, Alignment::sequences, and StartTiming.
Referenced by trimAlManager::CleanSequences().
removeAllGapsSeqsAndCols()
void Cleaner::removeAllGapsSeqsAndCols (bool seqs = true, bool cols = true)
Method that identifies and removes columns and sequences composed only by gaps.
Definition at line 1355 of file Cleaner.cpp.
References alig, debug, KeepingOnlyGapsSequence, keepSequences, Alignment::numberOfResidues, Alignment::numberOfSequences, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, RemovingOnlyGapsSequence, reporting::reportManager::report(), Alignment::saveResidues, Alignment::saveSequences, Alignment::seqsName, Alignment::sequences, and StartTiming.
Referenced by cleanByCutValueFallBehind(), cleanByCutValueOverpass(), cleanByCutValueOverpassOrEquals(), cleanOverlapSeq(), cleanStrict(), removeColumns(), and removeSequences().
removeColumns()
Alignment * Cleaner::removeColumns (int * columns, int init, int size, bool complementary)
Method to remove columns, expressed as ranges.
Parameters
columns Vector containing the columns to remove.
init Where does the vector start. Set to 1 if the vector contains its size as first element.
size Size of the columns vector.
complementary Whether or not to return the complementary version of the trimmed alignment.
Definition at line 1212 of file Cleaner.cpp.
References alig, Alignment, Alignment::Cleaning, removeAllGapsSeqsAndCols(), Alignment::saveResidues, StartTiming, and Alignment::updateSequencesAndResiduesNums().
Referenced by trimAlManager::CleanResiduesNonAuto().
removeOnlyTerminal()
bool Cleaner::removeOnlyTerminal ()
Method to detect right and left borders. Borders are the first column found with no gaps.
Everything between the borders are kept in the trimmed alignments.
Returns
True if everything went ok.
False if it was not possible to calculate the gap stats.
Definition at line 1256 of file Cleaner.cpp.
References alig, statistics::Manager::calculateGapStats(), debug, statistics::Manager::gaps, statistics::Gaps::getGapsWindow(), left_boundary, LeftBoundaryBiggerThanRightBoundary, Alignment::originalNumberOfResidues, reporting::reportManager::report(), right_boundary, Alignment::saveResidues, StartTiming, Alignment::Statistics, and Alignment::updateSequencesAndResiduesNums().
Referenced by trimAlManager::postprocess_alignment().
removeSequences()
Alignment * Cleaner::removeSequences (int * seqs, int init, int size, bool complementary)
Method to remove sequences, expressed as ranges.
Parameters
seqs Vector containing the sequences to remove.
init Where does the vector start. Set to 1 if the vector contains its size as first element.
size Size of the columns vector.
complementary Whether or not to return the complementary version of the trimmed alignment.
Definition at line 1235 of file Cleaner.cpp.
References alig, Alignment, Alignment::Cleaning, removeAllGapsSeqsAndCols(), Alignment::saveSequences, and Alignment::updateSequencesAndResiduesNums().
Referenced by trimAlManager::CleanSequences().
removeSmallerBlocks()
void Cleaner::removeSmallerBlocks (int blockSize, Alignment & original)
Method to remove blocks of columns with no rejected residue smaller than a given size.
Parameters
blockSize Minimum size to remove a block from the alignment
original Alignment to apply the removal. Minimum size a block has to be to be kept.
Definition at line 1299 of file Cleaner.cpp.
References alig, blockSize, Alignment::numberOfResidues, Alignment::saveResidues, and StartTiming.
Referenced by cleanByCutValueFallBehind(), cleanByCutValueOverpass(), and cleanByCutValueOverpassOrEquals().
selectMethod()
int Cleaner::selectMethod ()
Method that selects the best cleaning method based on statistics of the alignment.
Definition at line 14 of file Cleaner.cpp.
References alig, calculateSeqIdentity(), GAPPYOUT, Alignment::identities, Alignment::numberOfSequences, StartTiming, and STRICT.
Referenced by trimAlManager::CleanResiduesAuto().
setBoundaries()
void Cleaner::setBoundaries (int * boundaries)
Boundaries setter.
Warning
Not In Use
Parameters
[in] boundaries New boundaries values.
Definition at line 1173 of file Cleaner.cpp.
References left_boundary, right_boundary, and StartTiming.
setTrimTerminalGapsFlag()
void Cleaner::setTrimTerminalGapsFlag (bool terminalOnly_)
Setter method to Terminal Only Flag.
Parameters
terminalOnly_ New vlue of the Terminal Only Flag.
Definition at line 1166 of file Cleaner.cpp.
References StartTiming, and terminalGapOnly.
Referenced by trimAlManager::perform(), and trimAlManager::perform_VCF().
Friends And Related Function Documentation
Alignment
friend class Alignment friend
Definition at line 450 of file Cleaner.h.
Referenced by cleanByCutValueFallBehind(), cleanByCutValueOverpass(), cleanByCutValueOverpassOrEquals(), cleanOverlapSeq(), cleanStrict(), getClustering(), removeColumns(), and removeSequences().
Member Data Documentation
alig
Alignment* Cleaner::alig private
Pointer to the alignment that contains this object.
Definition at line 455 of file Cleaner.h.
Referenced by calculateRelaxedSeqIdentity(), calculateRepresentativeSeq(), calculateSeqIdentity(), calculateSpuriousVector(), clean(), clean2ndSlope(), cleanByCutValueFallBehind(), cleanByCutValueOverpass(), cleanByCutValueOverpassOrEquals(), cleanCombMethods(), cleanCompareFile(), cleanConservation(), Cleaner(), cleanGaps(), cleanNoAllGaps(), cleanOverlapSeq(), cleanSpuriousSeq(), cleanStrict(), computeComplementaryAlig(), getClustering(), getCutPointClusters(), removeAllGapsSeqsAndCols(), removeColumns(), removeOnlyTerminal(), removeSequences(), removeSmallerBlocks(), and selectMethod().
blockSize
int Cleaner::blockSize
Block size to use on the cleaning methods.
Definition at line 42 of file Cleaner.h.
Referenced by cleanByCutValueFallBehind(), cleanByCutValueOverpass(), cleanByCutValueOverpassOrEquals(), Cleaner(), cleanStrict(), removeSmallerBlocks(), and Alignment::setBlockSize().
keepSequences
bool Cleaner::keepSequences
Flag for keeping sequences even when they are composed only by gaps.
Definition at line 38 of file Cleaner.h.
Referenced by Cleaner(), removeAllGapsSeqsAndCols(), and Alignment::setKeepSequencesFlag().
left_boundary
int Cleaner::left_boundary
left boundary of the alignment
Definition at line 46 of file Cleaner.h.
Referenced by Cleaner(), removeOnlyTerminal(), and setBoundaries().
right_boundary
int Cleaner::right_boundary
right boundary of the alignment
Definition at line 50 of file Cleaner.h.
Referenced by Cleaner(), removeOnlyTerminal(), and setBoundaries().
terminalGapOnly
bool Cleaner::terminalGapOnly
Flag for trimming only on the terminal positions.
Definition at line 34 of file Cleaner.h.
Referenced by Cleaner(), and setTrimTerminalGapsFlag().
The documentation for this class was generated from the following files:
/home/vfernandez/git/trimAl/include/Cleaner.h
/home/vfernandez/git/trimAl/source/Cleaner.cpp