trimAl: newAlignment Class Reference
newAlignment Class Reference
Class containing an alignment
This class stores the alignment sequences with it's names, residues and extra information.
It contains multiple methods regarding the sequences.
It also contains submodules that provide methods for Calculating statistics, Trim the alignment and Printing sequences information.
Public Member Functions
bool fillMatrices (bool aligned)
Method to initialize matrices and check if the sequences have been correctly loaded and are free of errors
It checks if sequences contain unknown characters, sets the isAligned flag and initializes 'saveResidues' and 'saveSequences', depending on the sizes of the sequences (whether or not they have the same length).
newAlignment ()
Constructor.
newAlignment (newAlignment &)
Copy Constructor.
~newAlignment ()
Destructor.
int getNumSpecies ()
Number of sequences getter.
void getSequences (string *names)
Getter for the sequences names.
void getSequences (string *names, int *lengths)
Getter for the sequences names and its lengths.
void getSequences (string *names, string *sequences, int *lenghts)
Getter for the sequences, its names and lenghts.
bool getSequenceNameOrder (string *names, int *orderVector)
Method to map two sets of sequences, own and external.
The method accepts a vector of names, and test them against the alignment own sequences' names.
If the sequence is present, its index will be stored in orderVector.
.
int getNumAminos ()
Residues number getter. It counts gaps as residue.
void setWindowsSize (int ghWindow, int shWindow)
Windows setter.
void setBlockSize (int blockSize)
blockSize BlockSize Setter.
int getBlockSize ()
BlockSize getter.
void calculateSeqIdentity ()
Calculates identity between sequences.
void calculateRelaxedSeqIdentity ()
Lightweight version of newAlignment::calculateSeqIdentity for use in huge alignments.
void calculateSeqOverlap ()
Calculates overlap between sequences.
void printSeqIdentity ()
Method to print different identity values computed from the alignment.
In this method we assess the identity values matrix, as well as different average values.
Moreover, the method computes which one is the most similar sequence.
void printSeqOverlap ()
Prints the overlap between sequences.
int getAlignmentType ()
Alignment type getter.
See SequenceTypes.
int * getCorrespResidues ()
Method that returns the correspondence between old and new alignment residues.
See newAlignment::saveResidues.
int * getCorrespSequences ()
Method that returns the correspondence between old and new alignment sequences.
See newAlignment::saveSequences.
bool isFileAligned ()
isAligned getter.
newAlignment * getTranslationCDS (newAlignment *proteinAlignment)
Method to back translate a protein alignment using the sequences present on the current alignment.
Current alignment should contain the original sequences which were translated to protein sequences, without any gap.
bool checkCorrespondence (string *names, int *lenghts, int totalInputSequences, int multiple)
Function to check CDS file.
.
void fillNewDataStructure (string *newMatrix, string *newNames)
Method that copies information of the alignment to the pointers given.
void calculateColIdentity (float *columnIdentity)
Method that calculates the columns identity value.
This is, the frequency of the most present element in the column, being residue, indetermination and gap allowed.
void printColumnsIdentity_DescriptiveStats ()
Method to print Identity stats: Min, Max, Avg and Std.
void setKeepSequencesFlag (bool newFlagValue)
Keep Sequences setter.
void setKeepSeqsHeaderFlag (bool newFlagValue)
Keep Header setter.
void printAlignmentInfo (ostream &output)
Print information about sequences number, average sequence length, maximum and minimum sequences length, etc.
bool prepareCodingSequence (bool splitByStopCodon, bool ignoreStopCodon, newAlignment *proteinAlignment)
Method to check if the CDS file is correct.
Based on nature of residues: DNA/RNA (Most of the residues)
There is no gaps on the whole dataset.
Each sequence is a multiple of 3.
It will also remove or split stop codons depending on the flags passed.
bool alignmentSummaryHTML (newAlignment &_trimmedAlignment, char *destFile)
Method to report the trimming results in HTML.
Outputs an HTML file that shows visually what has been done to the alignment (removed sequences or residues) and the stats used to do so.
bool alignmentSummarySVG (newAlignment &_trimmedAlignment, char *destFile, int blocks)
Method to report the trimming results in SVG.
Outputs a SVG file that shows visually what has been done to the alignment (removed sequences or residues) and the stats used to do so.
bool alignmentColourHTML (ostream &file)
Method that saves a clustal-color based visualization of the alignment.
It doesn't report any trimming result, meaning this only shows information of an alignment.
void updateSequencesAndResiduesNums (bool countSequences=true, bool countResidues=true)
Updates the sequence number and residue number based on saveResidues and saveSequences.
Public Attributes
Cleaner * Cleaning = nullptr
Trimming submodule.
It contains methods and variables related to trimming.
StatisticsManager * Statistics = nullptr
Statistics submodule.
It contains methods and variables related to Statistics calculation and reporting.
sequencesMatrix * SequencesMatrix = nullptr
SequencesMatrix submodule
This helper module stores the sequences without gaps. Useful when comparing MSA.
int * SeqRef = nullptr
Pointer to keep a count of how many alignments depend on the same shared-sequences.
Increased on each trim step, and automatically reduced on each alignment destroy.
If it arrives to 0, the last alignment being destroyed will also take care of releasing memory for shared information.
int originalSequenNumber = 0
Number of sequences the alignment had when it was loaded.
int sequenNumber = 0
Number of sequences present on the alignment.
int originalResidNumber = 0
Number of residues the alignment had when it was loaded.
int residNumber = 0
Number of residues present on the alignment if it is aligned.
bool isAligned = false
Flag that indicates if all sequences on the alignment have the same length (Including gaps).
string * sequences = nullptr
Vector containing the sequences.
string * seqsName = nullptr
String vector containing the sequences names.
string * seqsInfo = nullptr
Vector containing extra information about each sequence.
string filename
Filename where this alignment was loaded from.
string aligInfo
String containing information of the alignment as a whole.
float ** identities = nullptr
2D Matrix that represents how much each sequence resembles other sequences in the same MSA
float ** overlaps = nullptr
Matrix that stores the overlap between sequences of an alignment. See newAlignment::calculateSeqOverlap.
int * saveResidues = nullptr
Vector containing which residues will be kept/removed.
-1 Indicates a 'removed/toRemove'. Otherwise residue/column will be kept.
int * saveSequences = nullptr
Vector containing which sequences will be kept/removed.
-1 Indicates a 'removed/toRemove'. Otherwise sequence will be kept.
Private Attributes
int dataType = 0
Flag variable that represents the type of the alignment.
Detailed Description
Class containing an alignment
This class stores the alignment sequences with it's names, residues and extra information.
It contains multiple methods regarding the sequences.
It also contains submodules that provide methods for Calculating statistics, Trim the alignment and Printing sequences information.
Definition at line 52 of file newAlignment.h.
Member Function Documentation
alignmentColourHTML()
bool newAlignment::alignmentColourHTML (ostream & file)
Method that saves a clustal-color based visualization of the alignment.
It doesn't report any trimming result, meaning this only shows information of an alignment.
Warning
Not In Use
Parameters
file Where to save the visualization.
Returns
True if everything went ok.
False if alignment is not aligned.
Definition at line 2044 of file newAlignment.cpp.
References utils::max(), and __internalReport::__reportSystem::report().
alignmentSummaryHTML()
bool newAlignment::alignmentSummaryHTML (newAlignment & _trimmedAlignment, char * destFile)
Method to report the trimming results in HTML.
Outputs an HTML file that shows visually what has been done to the alignment (removed sequences or residues) and the stats used to do so.
Parameters
_trimmedAlignment Trimmed alignment to compare with.
destFile Filename where to save the results.
consValues Vector containing the consistency values of columns.
The consistency may be a null pointer, meaning we don't want to report consistency values.
This may happen if we didn't calculated the consistency values or used them to choose the best alignment among a set, but not used to trim the alignment itself.
Returns
True if correct.
False if file couldn't be open or alignment is not aligned.
Definition at line 1145 of file newAlignment.cpp.
References statisticsConservation::getMdkWindowedVector(), utils::max(), __internalReport::__reportSystem::report(), residNumber, sequenNumber, and Statistics.
alignmentSummarySVG()
bool newAlignment::alignmentSummarySVG (newAlignment & _trimmedAlignment, char * destFile, int blocks)
Method to report the trimming results in SVG.
Outputs a SVG file that shows visually what has been done to the alignment (removed sequences or residues) and the stats used to do so.
Parameters
_trimmedAlignment Trimmed alignment obtained from the object calling this function.
destFile Filename where to save the results.
consValues Vector containing the consistency values of columns.
The consistency may be a null pointer, meaning we don't want to report consistency values.
This may happen if we didn't calculated the consistency values or used them to choose the best alignment among a set, but not used to trim the alignment itself.
blocks Size in residues to report. 120 by default.
Returns
True if everything went ok.
False if file couldn't be open or alignment is not aligned.
Definition at line 1409 of file newAlignment.cpp.
References utils::determineColor(), utils::max(), __internalReport::__reportSystem::report(), residNumber, saveResidues, saveSequences, and sequenNumber.
calculateColIdentity()
void newAlignment::calculateColIdentity (float * columnIdentity)
Method that calculates the columns identity value.
This is, the frequency of the most present element in the column, being residue, indetermination and gap allowed.
Parameters
[out] columnIdentity Vector to fill with identities for each column.
Definition at line 1054 of file newAlignment.cpp.
References AA.
calculateRelaxedSeqIdentity()
void newAlignment::calculateRelaxedSeqIdentity (void)
Lightweight version of newAlignment::calculateSeqIdentity for use in huge alignments.
Warning
Not In Use
Definition at line 346 of file newAlignment.cpp.
calculateSeqIdentity()
void newAlignment::calculateSeqIdentity (void)
Calculates identity between sequences.
Warning
Not In Use
Definition at line 302 of file newAlignment.cpp.
References AA.
checkCorrespondence()
bool newAlignment::checkCorrespondence (string * names, int * lenghts, int totalInputSequences, int multiple = 1)
Function to check CDS file.
.
It checks if sequences of input alignment are all present on the CDS file.
If nucleotide sequence is larger than protein sequence length * 3, warns about it and cuts the nucleotide sequence
If sequence has indetermination symbols, it warns about it.
If nucleotide sequence is smaller than protein sequence * 3, it adds some 'N' at the end of the nucleotide sequence.
Parameters
names Vector containing the names to check.
lenghts Vector containing the length of each sequence.
totalInputSequences Number of sequences present.
multiple Multiplies the length of each sequence by this number.
Returns
True if all went right.
False if there is a sequence in the alignment but not in the names vector.
Definition at line 701 of file newAlignment.cpp.
References utils::min(), utils::removeCharacter(), and __internalReport::__reportSystem::report().
Referenced by trimAlManager::check_backtranslation_infile_names_corresponde().
fillMatrices()
bool newAlignment::fillMatrices (bool aligned)
Method to initialize matrices and check if the sequences have been correctly loaded and are free of errors
It checks if sequences contain unknown characters, sets the isAligned flag and initializes 'saveResidues' and 'saveSequences', depending on the sizes of the sequences (whether or not they have the same length).
Parameters
aligned Flag to make the method check if the alignment is aligned or not.
Note
Even with the aligned flag set to false, if the alignment is aligned it will initialize the variables 'saveResidues' and 'saveSequences', allowing the alignment to be trimmed.
Returns
True if the alignment information was ok.
False if there was a problem.
This could happen if the sequences contain any unknown character or if aligned flag is set up to true and the sequences have variable sizes.
Definition at line 779 of file newAlignment.cpp.
References __internalReport::__reportSystem::report().
fillNewDataStructure()
void newAlignment::fillNewDataStructure (string * newMatrix, string * newNames)
Method that copies information of the alignment to the pointers given.
Warning
Not In Use
Parameters
[out] newMatrix Sequences vector to fill.
[out] newNames Names vector to fill.
Definition at line 503 of file newAlignment.cpp.
getAlignmentType()
int newAlignment::getAlignmentType (void)
Alignment type getter.
See SequenceTypes.
Returns
Int representing the alignment type.
Definition at line 473 of file newAlignment.cpp.
References utils::checkAlignmentType().
Referenced by statisticsConservation::calculateMatrixIdentity(), Cleaner::calculateSeqIdentity(), Cleaner::calculateSpuriousVector(), statisticsConservation::calculateVectors(), trimAlManager::check_coding_sequences_type(), and trimAlManager::create_or_use_similarity_matrix().
getBlockSize()
int newAlignment::getBlockSize (void)
BlockSize getter.
Warning
Not In Use
Returns
New BlockSize value.
Definition at line 295 of file newAlignment.cpp.
getCorrespResidues()
int * newAlignment::getCorrespResidues (void)
Method that returns the correspondence between old and new alignment residues.
See newAlignment::saveResidues.
Warning
Not In Use
Returns
Vector that represents which residues are kept (!= -1) and which are rejected (== -1)
Definition at line 482 of file newAlignment.cpp.
getCorrespSequences()
int * newAlignment::getCorrespSequences (void)
Method that returns the correspondence between old and new alignment sequences.
See newAlignment::saveSequences.
Warning
Not In Use
Returns
Vector that represents which sequences are kept (!= -1) and which are rejected (== -1)
Definition at line 489 of file newAlignment.cpp.
getNumAminos()
int newAlignment::getNumAminos (void)
Residues number getter. It counts gaps as residue.
Returns
Number of residues in the alignment.
Definition at line 258 of file newAlignment.cpp.
Referenced by trimAlManager::check_block_size(), trimAlManager::CleanResiduesNonAuto(), and statisticsConsistency::forceComparison().
getNumSpecies()
int newAlignment::getNumSpecies (void)
Number of sequences getter.
Returns
Number of sequences in the alignment.
Definition at line 251 of file newAlignment.cpp.
Referenced by trimAlManager::check_backtranslation_infile_names_corresponde(), trimAlManager::check_clusters_incompatibilities(), trimAlManager::check_select_cols_and_seqs_incompatibilities(), statisticsConsistency::compareAndChoose(), statisticsConsistency::forceComparison(), and prepareCodingSequence().
getSequenceNameOrder()
bool newAlignment::getSequenceNameOrder (string * names, int * orderVector)
Method to map two sets of sequences, own and external.
The method accepts a vector of names, and test them against the alignment own sequences' names.
If the sequence is present, its index will be stored in orderVector.
.
Parameters
names Vector of sequences names to map.
[out] orderVector Vector of orders to fill.
Returns
True if both sets have the same sequences.
False otherwise.
Definition at line 449 of file newAlignment.cpp.
Referenced by statisticsConsistency::compareAndChoose(), and statisticsConsistency::forceComparison().
getSequences() [1/3]
void newAlignment::getSequences (string * names)
Getter for the sequences names.
Parameters
[out] names Vector of sequences names to fill.
Definition at line 420 of file newAlignment.cpp.
Referenced by trimAlManager::check_backtranslation_infile_names_corresponde(), statisticsConsistency::compareAndChoose(), statisticsConsistency::forceComparison(), and prepareCodingSequence().
getSequences() [2/3]
void newAlignment::getSequences (string * names, int * lengths)
Getter for the sequences names and its lengths.
Parameters
[out] names Vector of sequences names to fill.
[out] lengths Vector of lengths to fill.
Definition at line 428 of file newAlignment.cpp.
References utils::removeCharacter().
getSequences() [3/3]
void newAlignment::getSequences (string * names, string * sequences, int * lenghts)
Getter for the sequences, its names and lenghts.
Parameters
[out] names Vector of sequences names to fill.
[out] sequences Vector of sequences to fill.
[out] lengths Vector of lengths to fill.
Definition at line 438 of file newAlignment.cpp.
References utils::removeCharacter().
getTranslationCDS()
newAlignment * newAlignment::getTranslationCDS (newAlignment * proteinAlignment)
Method to back translate a protein alignment using the sequences present on the current alignment.
Current alignment should contain the original sequences which were translated to protein sequences, without any gap.
Note
It's recommended to translate from dna to protein and then, align the protein sequences.
Parameters
proteinAlignment Protein Alignment to use as origin.
Returns
Pointer to new alignment.
Definition at line 190 of file newAlignment.cpp.
References originalSequenNumber, saveResidues, seqsInfo, seqsName, sequences, and sequenNumber.
Referenced by trimAlManager::clean_alignment().
isFileAligned()
bool newAlignment::isFileAligned (void)
isAligned getter.
Returns
Whether the alignment is aligned or not.
Definition at line 496 of file newAlignment.cpp.
Referenced by trimAlManager::check_backtranslations(), trimAlManager::check_file_aligned(), and trimAlManager::clean_alignment().
prepareCodingSequence()
bool newAlignment::prepareCodingSequence (bool splitByStopCodon, bool ignoreStopCodon, newAlignment * proteinAlignment)
Method to check if the CDS file is correct.
Based on nature of residues: DNA/RNA (Most of the residues)
There is no gaps on the whole dataset.
Each sequence is a multiple of 3.
It will also remove or split stop codons depending on the flags passed.
Parameters
splitByStopCodon Flag that informs the method to split sequences if it finds any stop codon.
ignoreStopCodon Flag that informs the method to stop reading sequence if it finds any stop codon.
proteinAlignment Alignment containing protein sequences which names contains all names in the current alignment.
Definition at line 525 of file newAlignment.cpp.
References AA, getNumSpecies(), getSequences(), and __internalReport::__reportSystem::report().
Referenced by trimAlManager::check_and_prepare_coding_sequence().
printAlignmentInfo()
void newAlignment::printAlignmentInfo (ostream & output)
Print information about sequences number, average sequence length, maximum and minimum sequences length, etc.
Parameters
output Output stream.
Definition at line 848 of file newAlignment.cpp.
printColumnsIdentity_DescriptiveStats()
void newAlignment::printColumnsIdentity_DescriptiveStats (void)
Method to print Identity stats: Min, Max, Avg and Std.
Warning
Not In Use
Definition at line 1105 of file newAlignment.cpp.
References utils::initlVect().
setBlockSize()
void newAlignment::setBlockSize (int blockSize)
blockSize BlockSize Setter.
Parameters
blockSize New value.
Definition at line 273 of file newAlignment.cpp.
Referenced by trimAlManager::perform().
setKeepSeqsHeaderFlag()
void newAlignment::setKeepSeqsHeaderFlag (bool newFlagValue)
Keep Header setter.
Warning
Not In Use
Parameters
newFlagValue New flag value
Definition at line 287 of file newAlignment.cpp.
setKeepSequencesFlag()
void newAlignment::setKeepSequencesFlag (bool newFlagValue)
Keep Sequences setter.
Parameters
newFlagValue New flag value
Definition at line 280 of file newAlignment.cpp.
Referenced by trimAlManager::perform().
setWindowsSize()
void newAlignment::setWindowsSize (int ghWindow, int shWindow)
Windows setter.
Parameters
ghWindow Half the Gap Window.
shWindow Half the Similarity Window.
Definition at line 265 of file newAlignment.cpp.
Referenced by trimAlManager::set_window_size().
updateSequencesAndResiduesNums()
void newAlignment::updateSequencesAndResiduesNums (bool countSequences = true, bool countResidues = true)
Updates the sequence number and residue number based on saveResidues and saveSequences.
Parameters
countSequences Whether to count sequences
countResidues Whether to count residues
Definition at line 2127 of file newAlignment.cpp.
Referenced by Cleaner::removeColumns(), Cleaner::removeOnlyTerminal(), and Cleaner::removeSequences().
Member Data Documentation
identities
newAlignment::identities = nullptr
2D Matrix that represents how much each sequence resembles other sequences in the same MSA
Identity score between two sequences is the ratio of identical residues by the total length (common and no-common residues) among them.
Definition at line 90 of file newAlignment.h.
Referenced by Cleaner::calculateRelaxedSeqIdentity(), Cleaner::calculateRepresentativeSeq(), Cleaner::calculateSeqIdentity(), Cleaner::getCutPointClusters(), and Cleaner::selectMethod().
The documentation for this class was generated from the following files:
include/newAlignment.h
include/documentation/externalHeadersConfiguration/newAlignment.dox
source/newAlignment.cpp