trimAl: Alignment::sequencesMatrix Class Reference
Alignment::sequencesMatrix Class Reference
Internal Alignment Class that represents a sequences matrix.
#include <sequencesMatrix.h>
Public Member Functions
sequencesMatrix ()
Null constructor.
sequencesMatrix (string *alignmentMatrix, string *alignmentSeqsName, int sequences, int residues)
Manual constructor.
sequencesMatrix (Alignment *parent)
Automatic constructor.
sequencesMatrix & operator= (const sequencesMatrix &)
~sequencesMatrix ()
Destructor.
void printMatrix ()
Sequences Matrix printing method.
void getColumn (int column, int *numResidueseqMatrix)
Method to get a column out of the matrix.
void getColumn (int value, int row, int *columnSeqMatrix)
Method that looks to value in a row and stores a column's, corresponding to row, sequences matrix in a vector.
void setOrder (int *order)
Method that reorders the stored sequences with a given order list.
bool getSequence (string seqName, int *sequence)
Method to obtain a sequence based on its name.
int getSeqNumber ()
Number of sequences getter.
int getResidNumber ()
Number of residues getter.
Private Attributes
int resNumber
Number of residues per sequence.
int seqsNumber
Number of sequences in the matrix.
int ** matrix
Matrix container.
It contains the sequences and residues of each sequence.
string * seqsName
Sequences names container.
Alignment * alig
Pointer to the alignment this object is related to.
Detailed Description
Internal Alignment Class that represents a sequences matrix.
A Sequence matrix is a 2D matrix that represents MSA without any gaps included.
This class stores the alignment sequences matrix.
It provides methods to build the sequences matrix and print the matrix.
It also provides methods for look to a column in the matrix and for look to value at the position (row, column) in the matrix.
See:
Statistics::Consistency::compareAndChoose
Statistics::Consistency::forceComparison
Definition at line 52 of file sequencesMatrix.h.
Constructor & Destructor Documentation
sequencesMatrix() [1/3]
Alignment::sequencesMatrix::sequencesMatrix (void)
Null constructor.
This construction method initializes all attributes of the new object with 0 or nullptr value.
Definition at line 32 of file sequencesMatrix.cpp.
References matrix, resNumber, seqsName, seqsNumber, and StartTiming.
sequencesMatrix() [2/3]
Alignment::sequencesMatrix::sequencesMatrix (string * alignmentMatrix, string * alignmentSeqsName, int sequences, int residues)
Manual constructor.
This construction method initializes all attributes using the information passed as arguments.
Parameters
alignmentMatrix Sequences of the alignment to convert to sequenceMatrix
alignmentSeqsName Sequences names
sequences Number of sequences
residues Number of residues
Definition at line 76 of file sequencesMatrix.cpp.
References utils::initlVect(), Alignment::seqsName, Alignment::sequences, and StartTiming.
sequencesMatrix() [3/3]
Alignment::sequencesMatrix::sequencesMatrix (Alignment * parent) explicit
Automatic constructor.
This construction method initializes all attributes using the information present in the alignment pointer passed.
Parameters
parent Alignment to associate the sequences matrix to.
Definition at line 45 of file sequencesMatrix.cpp.
References utils::initlVect(), Alignment::originalNumberOfSequences, Alignment::seqsName, and StartTiming.
~sequencesMatrix()
Alignment::sequencesMatrix::~sequencesMatrix ()
Destructor.
Destruction method that frees, if exists, previously allocated memory.
Definition at line 130 of file sequencesMatrix.cpp.
References Alignment::seqsName, and StartTiming.
Member Function Documentation
getColumn() [1/2]
void Alignment::sequencesMatrix::getColumn (int column, int * numResidueseqMatrix)
Method to get a column out of the matrix.
Parameters
column Column number at sequences matrix.
[out] numResidueseqMatrix Vector where storage a column's sequences matrix.
Method that storages a column's sequences matrix in a vector.
Definition at line 166 of file sequencesMatrix.cpp.
References StartTiming.
Referenced by statistics::Consistency::compareAndChoose(), and statistics::Consistency::forceComparison().
getColumn() [2/2]
void Alignment::sequencesMatrix::getColumn (int value, int row, int * columnSeqMatrix)
Method that looks to value in a row and stores a column's, corresponding to row, sequences matrix in a vector.
Parameters
value to look in a row's sequences matrix.
row where to look for a value.
columnSeqMatrix Vector where storage a column's sequences matrix.
Definition at line 182 of file sequencesMatrix.cpp.
References StartTiming.
getResidNumber()
int Alignment::sequencesMatrix::getResidNumber (void)
Number of residues getter.
Returns
Number of residues.
Definition at line 248 of file sequencesMatrix.cpp.
References StartTiming.
getSeqNumber()
int Alignment::sequencesMatrix::getSeqNumber (void)
Number of sequences getter.
Returns
Number of sequences.
Definition at line 241 of file sequencesMatrix.cpp.
References StartTiming.
getSequence()
bool Alignment::sequencesMatrix::getSequence (string seqName, int * sequence)
Method to obtain a sequence based on its name.
Parameters
seqName Name of the sequence to find.
[out] sequence Where to store the sequence.
Returns
True if found. False if not.
Definition at line 222 of file sequencesMatrix.cpp.
References utils::compare(), Alignment::seqsName, and StartTiming.
operator=()
Alignment::sequencesMatrix & Alignment::sequencesMatrix::operator= (const sequencesMatrix & old)
Definition at line 107 of file sequencesMatrix.cpp.
References matrix, resNumber, seqsName, Alignment::seqsName, and seqsNumber.
printMatrix()
void Alignment::sequencesMatrix::printMatrix (void)
Sequences Matrix printing method.
Method that prints the alignment sequences matrix.
Warning
Not In Use
Definition at line 149 of file sequencesMatrix.cpp.
References StartTiming.
setOrder()
void Alignment::sequencesMatrix::setOrder (int * order)
Method that reorders the stored sequences with a given order list.
Parameters
order Pointer that contains the new order we want to give the matrix.
Definition at line 200 of file sequencesMatrix.cpp.
References StartTiming.
Referenced by statistics::Consistency::compareAndChoose(), and statistics::Consistency::forceComparison().
Member Data Documentation
alig
Alignment* Alignment::sequencesMatrix::alig private
Pointer to the alignment this object is related to.
Definition at line 175 of file sequencesMatrix.h.
matrix
int** Alignment::sequencesMatrix::matrix private
Matrix container.
It contains the sequences and residues of each sequence.
Definition at line 66 of file sequencesMatrix.h.
Referenced by operator=(), and sequencesMatrix().
resNumber
int Alignment::sequencesMatrix::resNumber private
Number of residues per sequence.
Definition at line 56 of file sequencesMatrix.h.
Referenced by operator=(), and sequencesMatrix().
seqsName
string* Alignment::sequencesMatrix::seqsName private
Sequences names container.
Definition at line 71 of file sequencesMatrix.h.
Referenced by operator=(), and sequencesMatrix().
seqsNumber
int Alignment::sequencesMatrix::seqsNumber private
Number of sequences in the matrix.
Definition at line 60 of file sequencesMatrix.h.
Referenced by operator=(), and sequencesMatrix().
The documentation for this class was generated from the following files:
/home/vfernandez/git/trimAl/include/Alignment/sequencesMatrix.h
/home/vfernandez/git/trimAl/source/Alignment/sequencesMatrix.cpp