trimAl: statistics::similarityMatrix Class Reference
statistics::similarityMatrix Class Reference
Class that contains information of similarity matrices.
These are used to calculate the similarity between residues on the same column.
Default matrices for AA, NT and DEG NT are provided, along with method for loading custom matrices.
#include <similarityMatrix.h>
Public Member Functions
similarityMatrix ()
Constructor.
~similarityMatrix ()
Destructor.
bool loadSimMatrix (char *filename)
Method to load a custom matrix.
void defaultAASimMatrix ()
Method to load the default AA similarity matrix.
void defaultNTSimMatrix ()
Method to load the default NT similarity matrix.
void defaultNTDegeneratedSimMatrix ()
Method to load the default DEG NT similarity matrix.
void alternativeSimilarityMatrices (int matrix_code, int datatype)
Method to load alternative similarity matrices also included on the suite. Currently, only one type of alternative matrix is available:
matrix_code: 1 datatype SequenceTypes::AA.
float getDistance (char &A, char &B)
Method to get the similarity distance between two residues, A and B
Characters provided must be both uppercase, please, refer to utils::toUpper.
void printMatrix ()
Method to print the loaded matrix.
Private Member Functions
void memoryAllocation (int nPos)
Method to allocate memory for the similiarity matrix.
void memoryDeletion ()
Method to deallocate memory allocated on the similarityMatrix::memoryAllocation method.
It makes use of the numPositions to effectively remove the memory.
Private Attributes
int * vhash
float ** simMat
float ** distMat
int numPositions
Detailed Description
Class that contains information of similarity matrices.
These are used to calculate the similarity between residues on the same column.
Default matrices for AA, NT and DEG NT are provided, along with method for loading custom matrices.
Definition at line 47 of file similarityMatrix.h.
Constructor & Destructor Documentation
similarityMatrix()
statistics::similarityMatrix::similarityMatrix ()
Constructor.
Definition at line 47 of file similarityMatrix.cpp.
References distMat, numPositions, simMat, StartTiming, and vhash.
~similarityMatrix()
statistics::similarityMatrix::~similarityMatrix ()
Destructor.
Definition at line 85 of file similarityMatrix.cpp.
References memoryDeletion(), numPositions, and StartTiming.
Member Function Documentation
alternativeSimilarityMatrices()
void statistics::similarityMatrix::alternativeSimilarityMatrices (int matrix_code, int datatype)
Method to load alternative similarity matrices also included on the suite. Currently, only one type of alternative matrix is available:
matrix_code: 1 datatype SequenceTypes::AA.
Parameters
matrix_code ID of the matrix
datatype Numberical representation of the data type. See SequenceTypes
Definition at line 350 of file similarityMatrix.cpp.
References AA, DEG, distMat, DNA, memoryAllocation(), numPositions, RNA, simMat, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
defaultAASimMatrix()
void statistics::similarityMatrix::defaultAASimMatrix (void)
Method to load the default AA similarity matrix.
Definition at line 248 of file similarityMatrix.cpp.
References distMat, memoryAllocation(), numPositions, simMat, StartTiming, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
defaultNTDegeneratedSimMatrix()
void statistics::similarityMatrix::defaultNTDegeneratedSimMatrix (void)
Method to load the default DEG NT similarity matrix.
Definition at line 317 of file similarityMatrix.cpp.
References distMat, memoryAllocation(), numPositions, simMat, StartTiming, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
defaultNTSimMatrix()
void statistics::similarityMatrix::defaultNTSimMatrix (void)
Method to load the default NT similarity matrix.
Definition at line 283 of file similarityMatrix.cpp.
References distMat, memoryAllocation(), numPositions, simMat, StartTiming, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
getDistance()
float statistics::similarityMatrix::getDistance (char & A, char & B)
Method to get the similarity distance between two residues, A and B
Characters provided must be both uppercase, please, refer to utils::toUpper.
Parameters
A First residue to compare
B Second residue to compare
Returns
Distance between A and B based on the similarity matrix loaded.
Definition at line 427 of file similarityMatrix.cpp.
References debug, distMat, IncorrectSymbol, reporting::reportManager::report(), StartTiming, UndefinedSymbol, and vhash.
Referenced by statistics::Similarity::calculateVectors().
loadSimMatrix()
bool statistics::similarityMatrix::loadSimMatrix (char * filename)
Method to load a custom matrix.
Parameters
filename Path to file containing the matrix to load
Returns
True if loaded
False if an error ocurred
Definition at line 115 of file similarityMatrix.cpp.
References distMat, utils::initlVect(), LINE_LENGTH, memoryAllocation(), memoryDeletion(), numPositions, utils::removeSpaces(), simMat, StartTiming, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
memoryAllocation()
void statistics::similarityMatrix::memoryAllocation (int nPos) private
Method to allocate memory for the similiarity matrix.
Parameters
nPos Number of different possible residues in the alignment.
This are, on the default matrices:
AA: 20 residues
NT: 5 residues
DEG NT: 15 residues
Definition at line 57 of file similarityMatrix.cpp.
References distMat, memoryDeletion(), numPositions, simMat, StartTiming, TAMABC, and vhash.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), and loadSimMatrix().
memoryDeletion()
void statistics::similarityMatrix::memoryDeletion () private
Method to deallocate memory allocated on the similarityMatrix::memoryAllocation method.
It makes use of the numPositions to effectively remove the memory.
Definition at line 94 of file similarityMatrix.cpp.
References distMat, numPositions, simMat, StartTiming, and vhash.
Referenced by loadSimMatrix(), memoryAllocation(), and ~similarityMatrix().
printMatrix()
void statistics::similarityMatrix::printMatrix (void)
Method to print the loaded matrix.
Definition at line 415 of file similarityMatrix.cpp.
References numPositions, simMat, and StartTiming.
Member Data Documentation
distMat
float** statistics::similarityMatrix::distMat private
Definition at line 51 of file similarityMatrix.h.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), getDistance(), loadSimMatrix(), memoryAllocation(), memoryDeletion(), and similarityMatrix().
numPositions
int statistics::similarityMatrix::numPositions private
Definition at line 52 of file similarityMatrix.h.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), loadSimMatrix(), memoryAllocation(), memoryDeletion(), printMatrix(), similarityMatrix(), and ~similarityMatrix().
simMat
float** statistics::similarityMatrix::simMat private
Definition at line 50 of file similarityMatrix.h.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), loadSimMatrix(), memoryAllocation(), memoryDeletion(), printMatrix(), and similarityMatrix().
vhash
int* statistics::similarityMatrix::vhash private
Definition at line 49 of file similarityMatrix.h.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), getDistance(), loadSimMatrix(), memoryAllocation(), memoryDeletion(), and similarityMatrix().
The documentation for this class was generated from the following files:
/home/vfernandez/git/trimAl/include/Statistics/similarityMatrix.h
/home/vfernandez/git/trimAl/source/Statistics/similarityMatrix.cpp