trimAl: utils Class Reference
utils Class Reference
Utilities class. This class contains shared methods to be used in multiple parts of the code.
#include <utils.h>
Static Public Member Functions
static void initlVect (int *vector, int tam, int valor)
Vector initialization.
static void initlVect (float *vector, int tam, float valor)
Vector initialization.
static void copyVect (int *vect1, int *vect2, int tam)
Integer vector copying.
static void copyVect (float *vect1, float *vect2, int tam)
Float vector copying.
static int roundToInf (double number)
Round double to inferior integer method.
static int roundInt (double number)
Round double to integer method.
static int roundToSup (double number)
Round double to greater integer method.
static int max (int x, int y)
Maximum of two numbers method.
static float max (float x, float y)
Maximum of two numbers method.
static double max (double x, double y)
Maximum of two numbers method.
static int min (int x, int y)
Minimum of two numbers method.
static float min (float x, float y)
Minimum of two numbers method.
static double min (double x, double y)
Minimum of two numbers method.
static bool isNumber (char *num)
String-is-number checking.
static bool compare (char *a, char *b)
String comparing method.
static void removeSpaces (char *in, char *out)
Removing spaces method.
static void quicksort (float *list, int ini, int fin)
Quicksort sorting method.
static void swap (float *a, float *b)
Swapping elements method.
static void quicksort (int *list, int ini, int fin)
Quicksort sorting method.
static void swap (int *a, int *b)
Swapping elements method.
static bool checkFile (ifstream &file)
Check if a given file exists and its size is greater than 0.
static char * readLine (ifstream &file)
Read a new line from current input stream.
This function is better than standard one since cares of operative system compatibility.
It is useful as well because removes tabs and blank spaces at lines at beginning/ending.
.
static char * readLine (istream &file)
Read a new line from current input stream.
This function is better than standard one since cares of operative system compatibility.
It is useful as well because removes tabs and blank spaces at lines at beginning/ending.
.
static char * trimLine (string nline)
Remove all content surrounded by ("") or ([]).
It warns as well when a mismatch for these flags is found.
.
static string getReverse (string toReverse)
Reverses a string.
static string removeCharacter (char c, string line)
Removes a determined char from the string.
static int checkAlignmentType (int seqNumber, int residNumber, string *sequences)
Checks an alignment type.
static int * readNumbers (string line)
Reads a line and converts it to an array of number.
static void quicksort (int **vect, int ini, int fin)
Quicksort sorting method.
static void swap (int **a, int **b)
Swaps double pointers.
static char determineColor (char res, string column)
Checks the color that has to be used on the output report.
static bool lookForPattern (const string data, const string pattern, const float threshold)
Method to check for a pattern in a string.
The method will check, character by character of the first string if there is some equality for each character in the pattern. When done, it will calculate the fraction of characters present in the pattern and compare to the threshold argument.
static void ReplaceStringInPlace (std::string &subject, const std::string &search, const std::string &replace)
Function that replaces a substring with another substring in a string. It does not make a copy of the original string, but modifies it.
static std::string ReplaceString (std::string subject, const std::string &search, const std::string &replace)
Function that replaces a substring with another substring in a string. It makes a copy of the original string.
static int GetGapStep (int *gapValue, int sequenNumber)
Function that gives the gap classification of a column of values.
static int GetGapStep (int *gapValue, float inverseSequenNumber)
Function that gives the gap classification of a column of values.
This function should work faster than it's sister utils::GetGapStep(int * gapValue, int sequenNumber), as it uses a precomputed (by the user) inverseSequenNumber (1F / newAlignment::sequenNumber), instead of calculating it over again each time the function is called (which is equal to number of residues).
This comes with a precision cost that shouldn't be a problem.
static int GetSimStep (float *simValue)
Function that gives the similarity classification of a column of values.
static int GetConsStep (float *consValue)
Function that gives the consistency classification of a column of values.
static void streamSVG (float *x, float *y, int num, std::string *lineName, std::string *lineColor, std::string *chartTitle, std::string *filename)
Detailed Description
Utilities class. This class contains shared methods to be used in multiple parts of the code.
Definition at line 45 of file utils.h.
Member Function Documentation
checkAlignmentType()
int utils::checkAlignmentType (int seqNumber, int residNumber, string * sequences) static
Checks an alignment type.
Parameters
seqNumber Number of sequences to check it's type.
residNumber Number of residues of the alignment.
sequences Sequences pointer
Returns
Integer that represents the alignment type.
Definition at line 506 of file utils.cpp.
References AA, DEG, DNA, and RNA.
Referenced by newAlignment::getAlignmentType().
checkFile()
bool utils::checkFile (ifstream & file) static
Check if a given file exists and its size is greater than 0.
Parameters
file ifstream to check
Definition at line 288 of file utils.cpp.
compare()
bool utils::compare (char * a, char * b) static
String comparing method.
Parameters
a The first string that will be compared.
b The second string that will be compared.
Returns
true if the two strings are the same, false if not.
This method compares the two strings given, and returns true if the two strings are equal.
Definition at line 142 of file utils.cpp.
copyVect() [1/2]
void utils::copyVect (int * vect1, int * vect2, int tam) static
Integer vector copying.
Parameters
vect1 Vector that we want to copy.
[out] vect2 Destination vector of the copy.
tam Vectors size.
This method copies integer vector 1 to integer vector 2.
Definition at line 54 of file utils.cpp.
Referenced by statisticsConservation::calcCutPoint(), Cleaner::cleanCompareFile(), trimAlManager::print_statistics(), statisticsConservation::printConservationAcl(), and statisticsConsistency::printStatisticsFileAcl().
copyVect() [2/2]
void utils::copyVect (float * vect1, float * vect2, int tam) static
Float vector copying.
Parameters
vect1 Vector that we want to copy.
[out] vect2 Destination vector of the copy.
tam Vectors size.
This method copies float vector 1 to float vector 2.
Definition at line 60 of file utils.cpp.
determineColor()
char utils::determineColor (char res, string column) static
Checks the color that has to be used on the output report.
Parameters
res Resiude to check its color
column Column to which this residue belongs.
Returns
Char that represents the color to be used.
Definition at line 623 of file utils.cpp.
References lookForPattern().
Referenced by newAlignment::alignmentSummarySVG().
GetConsStep()
int utils::GetConsStep (float * consValue) static
Function that gives the consistency classification of a column of values.
Parameters
consValue Consistency value.
Returns
Int representing the classification of this gap value.
Definition at line 867 of file utils.cpp.
GetGapStep() [1/2]
int utils::GetGapStep (int * gapValue, int sequenNumber) static
Function that gives the gap classification of a column of values.
Parameters
gapValue Number of gaps present in the column.
sequenNumber Number of sequences.
Returns
Int representing the classification of this gap value.
Definition at line 779 of file utils.cpp.
GetGapStep() [2/2]
int utils::GetGapStep (int * gapValue, float inverseSequenNumber) static
Function that gives the gap classification of a column of values.
This function should work faster than it's sister utils::GetGapStep(int * gapValue, int sequenNumber), as it uses a precomputed (by the user) inverseSequenNumber (1F / newAlignment::sequenNumber), instead of calculating it over again each time the function is called (which is equal to number of residues).
This comes with a precision cost that shouldn't be a problem.
Parameters
gapValue Number of gaps present in the column.
inverseSequenNumber Inverse of number of sequences. (1F / sequenNumber)
Returns
Int representing the classification of this gap value.
Definition at line 810 of file utils.cpp.
getReverse()
string utils::getReverse (string toReverse) static
Reverses a string.
Parameters
toReverse String to get a reversed copy.
Returns
Reversed string of toReverse.
Definition at line 481 of file utils.cpp.
GetSimStep()
int utils::GetSimStep (float * simValue) static
Function that gives the similarity classification of a column of values.
Parameters
simValue Similarity value.
Returns
Int representing the classification of this gap value.
Definition at line 840 of file utils.cpp.
initlVect() [1/2]
void utils::initlVect (int * vector, int tam, int valor) static
Vector initialization.
Parameters
[out] vector The vector that will be initialized.
tam The size of the vector.
valor The initialization value that will of all positions of the vector.
This method is used to initialize all positions of a vector with a given value.
Definition at line 43 of file utils.cpp.
Referenced by statisticsConservation::calculateMatrixIdentity(), Cleaner::cleanCombMethods(), statisticsConsistency::compareAndChoose(), statisticsConsistency::forceComparison(), newAlignment::printColumnsIdentity_DescriptiveStats(), sequencesMatrix::sequencesMatrix(), and statisticsConservation::statisticsConservation().
initlVect() [2/2]
void utils::initlVect (float * vector, int tam, float valor) static
Vector initialization.
Parameters
[out] vector The vector that will be initialized.
tam The size of the vector.
valor The initialization value of all positions of the vector.
This method is used to initialize all positions of a vector with a given value.
Definition at line 49 of file utils.cpp.
isNumber()
bool utils::isNumber (char * num) static
String-is-number checking.
Parameters
num The string we want to check.
Returns
true if the string is a number, false if not.
This method checks if the given string is a number (taking in mind the possibility of floating numbers and scientific notation)
Definition at line 119 of file utils.cpp.
Referenced by trimAlManager::block_argument(), trimAlManager::clusters_argument(), trimAlManager::conservation_threshold_argument(), trimAlManager::consistency_threshold_argument(), trimAlManager::consistency_window_argument(), trimAlManager::gap_threshold_argument(), trimAlManager::gap_window_argument(), trimAlManager::max_identity_argument(), trimAlManager::residue_overlap_argument(), trimAlManager::sequence_overlap_argument(), trimAlManager::similarity_threshold_argument(), trimAlManager::similarity_window_argument(), and trimAlManager::window_argument().
lookForPattern()
bool utils::lookForPattern (const string data, const string pattern, const float threshold) static
Method to check for a pattern in a string.
The method will check, character by character of the first string if there is some equality for each character in the pattern. When done, it will calculate the fraction of characters present in the pattern and compare to the threshold argument.
Parameters
data string that will be compared against a pattern
pattern string that contains the pattern.
Todo:
Give a good description for this function.
Definition at line 741 of file utils.cpp.
Referenced by determineColor().
max() [1/3]
int utils::max (int x, int y) static
Maximum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The maximum between the two given numbers.
This method returns the maximum between the two numbers given as parameters.
Definition at line 83 of file utils.cpp.
Referenced by newAlignment::alignmentColourHTML(), newAlignment::alignmentSummaryHTML(), newAlignment::alignmentSummarySVG(), newAlignment::printSeqIdentity(), and newAlignment::printSeqOverlap().
max() [2/3]
float utils::max (float x, float y) static
Maximum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The maximum between the two given numbers.
This method returns the maximum between the two numbers given as parameters.
Definition at line 89 of file utils.cpp.
max() [3/3]
double utils::max (double x, double y) static
Maximum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The maximum between the two given numbers.
This method returns the maximum between the two numbers given as parameters.
Definition at line 95 of file utils.cpp.
min() [1/3]
int utils::min (int x, int y) static
Minimum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The minumum between the two given numbers.
This method returns the minimum between the two numbers given as parameters.
Definition at line 101 of file utils.cpp.
Referenced by newAlignment::checkCorrespondence(), and Cleaner::cleanCompareFile().
min() [2/3]
float utils::min (float x, float y) static
Minimum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The minumum between the two given numbers.
This method returns the minimum between the two numbers given as parameters.
Definition at line 107 of file utils.cpp.
min() [3/3]
double utils::min (double x, double y) static
Minimum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The minumum between the two given numbers.
This method returns the minimum between the two numbers given as parameters.
Definition at line 113 of file utils.cpp.
quicksort() [1/3]
void utils::quicksort (float * list, int ini, int fin) static
Quicksort sorting method.
Parameters
list The vector that we want to sort.
ini The first element of the vector.
fin The last element of the vector.
This method sorts the vector using the quicksort method.
Definition at line 162 of file utils.cpp.
References swap().
Referenced by statisticsConservation::calcCutPoint(), Cleaner::calculateRepresentativeSeq(), Cleaner::cleanByCutValueOverpass(), Cleaner::cleanByCutValueOverpassOrEquals(), Cleaner::cleanCombMethods(), Cleaner::cleanCompareFile(), Cleaner::getCutPointClusters(), trimAlManager::print_statistics(), statisticsConservation::printConservationAcl(), statisticsConsistency::printStatisticsFileAcl(), and quicksort().
quicksort() [2/3]
void utils::quicksort (int * list, int ini, int fin) static
Quicksort sorting method.
Parameters
list The vector that we want to sort.
ini The first element of the vector.
fin The last element of the vector.
This method sorts the vector using the quicksort method.
Definition at line 208 of file utils.cpp.
References quicksort(), and swap().
quicksort() [3/3]
void utils::quicksort (int ** vect, int ini, int fin) static
Quicksort sorting method.
Parameters
vect The vector that we want to sort.
ini The first element of the vector.
fin The last element of the vector.
Definition at line 250 of file utils.cpp.
References quicksort(), and swap().
readLine() [1/2]
char * utils::readLine (ifstream & file) static
Read a new line from current input stream.
This function is better than standard one since cares of operative system compatibility.
It is useful as well because removes tabs and blank spaces at lines at beginning/ending.
.
Parameters
file ifstream to read line from.
Returns
Line that has been read or nullptr if there is nothing to read.
Definition at line 308 of file utils.cpp.
readLine() [2/2]
char * utils::readLine (std::istream & file) static
Read a new line from current input stream.
This function is better than standard one since cares of operative system compatibility.
It is useful as well because removes tabs and blank spaces at lines at beginning/ending.
.
Parameters
file ifstream to read line from.
Returns
nullptr if there is nothing to read.
Line that has been read.
Definition at line 353 of file utils.cpp.
readNumbers()
int * utils::readNumbers (string line) static
Reads a line and converts it to an array of number.
Parameters
line Line to convert to array of ints
Returns
Pointer to an array of numbers that contains line
Definition at line 578 of file utils.cpp.
Referenced by trimAlManager::select_cols_argument(), and trimAlManager::seqs_select_argument().
removeCharacter()
string utils::removeCharacter (char c, string line) static
Removes a determined char from the string.
Parameters
c Character to remove from line
line String to remove c from.
Returns
New string without c character
Definition at line 493 of file utils.cpp.
Referenced by Cleaner::calculateRepresentativeSeq(), newAlignment::checkCorrespondence(), Cleaner::getCutPointClusters(), and newAlignment::getSequences().
removeSpaces()
void utils::removeSpaces (char * in, char * out) static
Removing spaces method.
Parameters
in The string that we want to clean.
[out] out The destination of the clean string.
This method removes spaces in the input string and put the result in the output string.
Definition at line 147 of file utils.cpp.
ReplaceString()
std::string utils::ReplaceString (std::string subject, const std::string & search, const std::string & replace) static
Function that replaces a substring with another substring in a string. It makes a copy of the original string.
Parameters
[in] subject String to be modified
search Substring to search and change
replace Substring to put in place of search
Definition at line 768 of file utils.cpp.
Referenced by ReadWriteMS::loadAndSaveMultipleAlignments(), and ReadWriteMS::saveAlignment().
ReplaceStringInPlace()
void utils::ReplaceStringInPlace (std::string & subject, const std::string & search, const std::string & replace) static
Function that replaces a substring with another substring in a string. It does not make a copy of the original string, but modifies it.
Parameters
[in,out] subject String to be modified
search Substring to search and change
replace Substring to put in place of search
Definition at line 758 of file utils.cpp.
Referenced by ReadWriteMS::loadAndSaveMultipleAlignments(), trimAlManager::menu(), and ReadWriteMS::saveAlignment().
roundInt()
int utils::roundInt (double number) static
Round double to integer method.
Parameters
number The number that will be rounded.
Returns
the rounded number.
This method rounds a double number to a integer.
Definition at line 71 of file utils.cpp.
Referenced by Cleaner::cleanByCutValueFallBehind(), Cleaner::cleanByCutValueOverpass(), Cleaner::cleanByCutValueOverpassOrEquals(), and Cleaner::cleanStrict().
roundToInf()
int utils::roundToInf (double number) static
Round double to inferior integer method.
Parameters
number The number that will be rounded.
Returns
the rounded number.
This method rounds a double number to the inferior integer.
Definition at line 65 of file utils.cpp.
roundToSup()
int utils::roundToSup (double number) static
Round double to greater integer method.
Parameters
number The number that will be rounded.
Returns
the rounded number.
This method rounds a double number to the greater integer.
Definition at line 77 of file utils.cpp.
swap() [1/3]
void utils::swap (float * a, float * b) static
Swapping elements method.
Parameters
a One element to swap.
b Other element to swap.
This method swaps the values in a and b.
Definition at line 196 of file utils.cpp.
Referenced by quicksort().
swap() [2/3]
void utils::swap (int * a, int * b) static
Swapping elements method.
Parameters
a One element to swap.
b Other element to swap.
This method swaps the values in a and b.
Definition at line 241 of file utils.cpp.
swap() [3/3]
void utils::swap (int ** a, int ** b) static
Swaps double pointers.
Parameters
a Double pointer A
b Double pointer B
Definition at line 279 of file utils.cpp.
trimLine()
char * utils::trimLine (string nline) static
Remove all content surrounded by ("") or ([]).
It warns as well when a mismatch for these flags is found.
.
Parameters
nline Line to be trimmed.
Returns
Line trimmed of comments or nullptr if there has been a mismatch
Definition at line 398 of file utils.cpp.
References __internalReport::__reportSystem::report().
The documentation for this class was generated from the following files:
include/utils.h
source/utils.cpp