trimAl: __internalReport::__reportSystem Class Reference
__internalReport::__reportSystem Class Reference
Class that allows us to centralize all the reporting messages that should be used to inform the user of Errors, Warnings and Info.
The object can also be used as a substitute to cout for temporal messages using the << overloaded operator or the log method, and the messages will be behind the IsDebug variable, which should be set to false in Release.
This allows us to protect the user from receiving Debug/Developing messages that shouldn't bother them, in case any of them is not removed by error.
#include <reportsystem.h>
Public Member Functions
void PrintCodesAndMessages ()
Method to print all Info, Warning and Error codes and their respective message.
This method is useful to check whether all codes have a message linked to them. It will use the current VerboseLevel of the object, which defaults to ERROR level.
void report (ErrorCode message, std::string *vars=nullptr)
Method to report an Error.
It will be displayed if Level is equal or higher to VerboseLevel::ERROR.
void report (ErrorCode message, char *vars)
Method to report an Error.
It will be displayed if Level is equal or higher to VerboseLevel::ERROR.
void report (WarningCode message, std::string *vars=nullptr)
Method to report a Warning.
It will be displayed if Level is equal or higher to VerboseLevel::WARNING.
void report (WarningCode message, char *vars)
Method to report a Warning.
It will be displayed if Level is equal or higher to VerboseLevel::WARNING.
void report (InfoCode message, std::string *vars=nullptr)
Method to report an Info message.
It will be displayed if Level is equal or higher to VerboseLevel::INFO.
void report (InfoCode message, char *vars)
Method to report an Info message.
It will be displayed if Level is equal or higher to VerboseLevel::WARNING.
__reporter log (VerboseLevel level)
Method to output a message behind two checks: IsDebug and VerboseLevel passed.
If IsDebug is false, it will ignore the message returning the cantReport , otherwise, VerboseLevel level will be checked.
template<typename T >
__reportSystem & operator<< (const T &a)
Overloaded operator that allows us to debug some messages behind IsDebug .
__reportSystem & operator<< (std::ostream &(*pf)(std::ostream &))
Overloaded operator that allows us to debug some messages behind IsDebug .
Public Attributes
VerboseLevel Level = VerboseLevel::INFO
Level of Verbosity.
The report system won't output messages that are lower than the current level.
bool IsDebug = false
Protection variable. This variable should be set to true while in development, and false on Release.
Private Attributes
__reporter canReport = __reporter(true)
Object that will be returned by log if it allows to output the message.
__reporter cantReport = __reporter(false)
Object that will be returned by log if it doesn't allow to output the message.
Static Private Attributes
static const std::map< InfoCode, const char * > InfoMessages
static const std::map< WarningCode, const char * > WarningMessages
static const std::map< ErrorCode, const char * > ErrorMessages
Related Functions
(Note that these are not member functions.)
__internalReport::__reportSystem debug
This instance is the one that should be used
It's use is similar to a singleton, without the need to obtain the instance every time it's needed.
Instead, it's a global instance of the __internalReport::__reportSystem
This allows us to have the '<<' operator overloaded, as it can't be statically overloaded.
Detailed Description
Class that allows us to centralize all the reporting messages that should be used to inform the user of Errors, Warnings and Info.
The object can also be used as a substitute to cout for temporal messages using the << overloaded operator or the log method, and the messages will be behind the IsDebug variable, which should be set to false in Release.
This allows us to protect the user from receiving Debug/Developing messages that shouldn't bother them, in case any of them is not removed by error.
Warning
THIS CLASS SHOULDN'T BE USED DIRECTLY
Use instanced global variable debug instead.
Definition at line 275 of file reportsystem.h.
Member Function Documentation
log()
__reporter __internalReport::__reportSystem::log (VerboseLevel level) inline
Method to output a message behind two checks: IsDebug and VerboseLevel passed.
If IsDebug is false, it will ignore the message returning the cantReport , otherwise, VerboseLevel level will be checked.
Parameters
level Level to use for this message.
If Level is higher than this argument, message will be ignored, otherwise, message will be outputted to cout.
Definition at line 415 of file reportsystem.h.
operator<<() [1/2]
template<typename T > __reportSystem& __internalReport::__reportSystem::operator<< (const T & a) inline
Overloaded operator that allows us to debug some messages behind IsDebug .
Parameters
a Message to be outputed if IsDebug
Definition at line 433 of file reportsystem.h.
operator<<() [2/2]
__reportSystem& __internalReport::__reportSystem::operator<< (std::ostream &(*)(std::ostream &) pf) inline
Overloaded operator that allows us to debug some messages behind IsDebug .
Parameters
pf Object that overloads the '<<' operator
Definition at line 445 of file reportsystem.h.
report() [1/6]
void __internalReport::__reportSystem::report (ErrorCode message, std::string * vars = nullptr)
Method to report an Error.
It will be displayed if Level is equal or higher to VerboseLevel::ERROR.
Parameters
message Code to report.
vars Array of strings that will replace the '[tags]' in the message.
The number of elements in the array must be the same as [tag] occurrences on the message.
The method will take care of destroying the array
Definition at line 375 of file reportsystem.cpp.
References Level.
Referenced by newAlignment::alignmentColourHTML(), newAlignment::alignmentSummaryHTML(), newAlignment::alignmentSummarySVG(), statisticsConsistency::applyWindow(), statisticsConservation::applyWindow(), trimAlManager::back_trans_argument(), trimAlManager::block_argument(), trimAlManager::check_automated_manual_incompatibilities(), trimAlManager::check_automated_methods_incompatibilities(), trimAlManager::check_backtranslations(), trimAlManager::check_block_size(), trimAlManager::check_clusters_incompatibilities(), trimAlManager::check_coding_sequences_type(), trimAlManager::check_codon_behaviour_incompatibility(), trimAlManager::check_col_numbering(), trimAlManager::check_combinations_among_thresholds_incompatibility(), trimAlManager::check_compareset_window_argument(), trimAlManager::check_file_aligned(), trimAlManager::check_force_selection(), trimAlManager::check_inFile_incompatibilities(), trimAlManager::check_input_file_with_coding_sequences_argument(), trimAlManager::check_max_identity_incompatibilities(), trimAlManager::check_output_file_with_statistics(), trimAlManager::check_output_relevance(), trimAlManager::check_outputs_coincidence(), trimAlManager::check_residue_and_sequence_overlap(), trimAlManager::check_select_cols_and_seqs_incompatibilities(), trimAlManager::check_similarity_matrix(), trimAlManager::check_stats_incompatibilities(), trimAlManager::check_thresholds_incompatibilities(), trimAlManager::check_windows_incompatibilities(), newAlignment::checkCorrespondence(), trimAlManager::clean_alignment(), trimAlManager::CleanResiduesNonAuto(), trimAlManager::clusters_argument(), statisticsConsistency::compareAndChoose(), trimAlManager::compareset_argument(), trimAlManager::conservation_threshold_argument(), trimAlManager::consistency_threshold_argument(), trimAlManager::consistency_window_argument(), trimAlManager::create_or_use_similarity_matrix(), newAlignment::fillMatrices(), trimAlManager::force_select_argument(), statisticsConsistency::forceComparison(), trimAlManager::gap_threshold_argument(), trimAlManager::gap_window_argument(), ReadWriteMS::getFileFormatName(), ReadWriteMS::loadAlignment(), ReadWriteMS::loadAndSaveMultipleAlignments(), trimAlManager::matrix_argument(), trimAlManager::max_identity_argument(), trimAlManager::out_format_arguments(), trimAlManager::parseArguments(), trimAlManager::perform(), newAlignment::prepareCodingSequence(), PrintCodesAndMessages(), Cleaner::removeAllGapsSeqsAndCols(), Cleaner::removeOnlyTerminal(), trimAlManager::residue_overlap_argument(), ReadWriteMS::saveAlignment(), trimAlManager::select_cols_argument(), trimAlManager::seqs_select_argument(), trimAlManager::sequence_overlap_argument(), trimAlManager::similarity_threshold_argument(), trimAlManager::similarity_window_argument(), utils::trimLine(), trimAlManager::verbosity_argument(), and trimAlManager::window_argument().
report() [2/6]
void __internalReport::__reportSystem::report (ErrorCode message, char * vars)
Method to report an Error.
It will be displayed if Level is equal or higher to VerboseLevel::ERROR.
Parameters
message Code to report.
vars Array of chars that will replace the first occurrence of '[tags]' in the message.
The method wont take care of destroying the array
This allows to reuse the parameter passed.
Definition at line 404 of file reportsystem.cpp.
References Level.
report() [3/6]
void __internalReport::__reportSystem::report (WarningCode message, std::string * vars = nullptr)
Method to report a Warning.
It will be displayed if Level is equal or higher to VerboseLevel::WARNING.
Parameters
message Code to report.
vars Array of strings that will replace the '[tags]' in the message.
The number of elements in the array must be the same as [tag] occurrences on the message.
The method will take care of destroying the array
Definition at line 429 of file reportsystem.cpp.
References Level.
report() [4/6]
void __internalReport::__reportSystem::report (WarningCode message, char * vars)
Method to report a Warning.
It will be displayed if Level is equal or higher to VerboseLevel::WARNING.
Parameters
message Code to report.
vars Array of chars that will replace the first occurrence of '[tags]' in the message.
The method wont take care of destroying the array
This allows to reuse the parameter passed.
Definition at line 458 of file reportsystem.cpp.
References Level.
report() [5/6]
void __internalReport::__reportSystem::report (InfoCode message, std::string * vars = nullptr)
Method to report an Info message.
It will be displayed if Level is equal or higher to VerboseLevel::INFO.
Parameters
message Code to report.
vars Array of strings that will replace the '[tags]' in the message.
The number of elements in the array must be the same as [tag] occurrences on the message.
The method will take care of destroying the array
Definition at line 483 of file reportsystem.cpp.
References Level.
report() [6/6]
void __internalReport::__reportSystem::report (InfoCode message, char * vars)
Method to report an Info message.
It will be displayed if Level is equal or higher to VerboseLevel::WARNING.
Parameters
message Code to report.
vars Array of chars that will replace the first occurrence of '[tags]' in the message.
The method wont take care of destroying the array
This allows to reuse the parameter passed.
Definition at line 512 of file reportsystem.cpp.
References Level.
Member Data Documentation
ErrorMessages
const std::map< ErrorCode, const char * > __internalReport::__reportSystem::ErrorMessages static private
Initial value:
=
        {
                {ErrorCode::AlignmentNotLoaded,
                        "Alignment not loaded: \" [tag] \" Check the file's content"},
                {ErrorCode::NoFormatsSpecified,
                        "You must specify at least one format after the '-formats' argument"},
                {ErrorCode::AlternativeMatrixNotRecognized,
                        "Alternative matrix \" [tag] \" not recognized"},
                {ErrorCode::ReferenceFileNotLoaded,
                        "Reference file \" [tag] \" not loaded"},
                {ErrorCode::GapThresholdOutOfRange,
                        "The gap threshold value should be between 0 and 1"},
                {ErrorCode::GapThresholdNotRecognized,
                        "The gap threshold value should be a positive real number between 0 and 1"},
                {ErrorCode::SimilarityThresholdOutOfRange,
                        "The similarity threshold value should be between 0 and 1"},
                {ErrorCode::SimilarityThresholdNotRecognized,
                        "The similarity threshold value should be a positive real number between 0 and 1"},
                {ErrorCode::ConsistencyThresholdOutOfRange,
                        "The consistency threshold value should be between 0 and 1"},
                {ErrorCode::ConsistencyThresholdNotRecognized,
                        "The consistency threshold value should be a positive real number between 0 and 1"},
                {ErrorCode::ConservationThresholdOutOfRange,
                        "The conservation threshold value should be between 0 and 100"},
                {ErrorCode::ConservationThresholdNotRecognized,
                        "The conservation threshold value should be a positive real number between 0 and 100"},
                {ErrorCode::ResidueOverlapOutOfRange,
                        "The residue overlap value should be between 0 and 100"},
                {ErrorCode::ResidueOverlapNotRecognized,
                        "The residue overlap value should be a positive real number between 0 and 100"},
                {ErrorCode::SequencesOverlapOutOfRange,
                        "The sequences overlap value should be between 0 and 100"},
                {ErrorCode::SequencesOverlapNotRecognized,
                        "The sequences overlap value should be a positive real number between 0 and 100"},
                {ErrorCode::MaxIdentityOutOfRange,
                        "The max identity value should be between 0 and 1"},
                {ErrorCode::MaxIdentityNotRecognized,
                        "The max identity value should be a positive real number between 0 and 1"},
                {ErrorCode::ClustersValueOutOfRange,
                        "The clusters value should be greater than 0"},
                {ErrorCode::ClustersValueNotRecognized,
                        "The clusters value should be a positive integer number greater than 0"},
                {ErrorCode::WindowValueOutOfRange,
                        "The window value should be greater than 0"},
                {ErrorCode::WindowValueNotRecognized,
                        "The window value should be a positive integer number greater than 0"},
                {ErrorCode::SelectSeqsNotRecognized,
                        "Could not parse the -selectseqs ranges"},
                {ErrorCode::SelectColsNotRecognized,
                        "Could not parse the -selectres ranges"},
                {ErrorCode::GapWindowValueOutOfRange,
                        "The gap window value should be greater than 0"},
                {ErrorCode::GapWindowValueNotRecognized,
                        "The gap window value should be a positive integer number grater than 0"},
                {ErrorCode::SimilarityWindowValueOutOfRange,
                        "The similarity window value should be greater than 0"},
                {ErrorCode::SimilarityWindowValueNotRecognized,
                        "The similarity window value should be a positive integer number grater than 0"},
                {ErrorCode::ConsistencyThresholdOutOfRange,
                        "The consistency window value should be greater than 0"},
                {ErrorCode::ConsistencyThresholdNotRecognized,
                        "The consistency window value should be a positive integer number grater than 0"},
                {ErrorCode::BlockSizeOutOfRange,
                        "The consistency window value should be greater than 0"},
                {ErrorCode::BlockSizeNotRecognized,
                        "The consistency window value should be a positive integer number grater than 0"},
                {ErrorCode::InFileComparisonStatistics,
                        "Option -in not valid in combination with file comparision options: -sft || -sfc || -ct"},
                {ErrorCode::IncompatibleArguments,
                        "Argument [tag] is not compatible with argument [tag]"},
                {ErrorCode::SelectSeqsResAndThresholdIncompatibilities,
                        "Options -selectCols and -selectSeqs are not allowed in combination with threshold options: (-gt || -st || -ct || -cons)"},
                {ErrorCode::SelectSeqsResAndAutomathedMethodsIncompatibilities,
                        "Options -selectCols and -selectSeqs are not allowed in combination with automated trimming options: (-nogaps || -noallgaps || -gappyout || -strict || -strictplus || -automated1)."},
                {ErrorCode::SelectSeqsResAndWindowIncompatibilities,
                        "Options -selectCols and -selectSeqs are not allowed in combination with window options: (-w || -sw || -gw || -wc)"},
                {ErrorCode::SelectSeqsResAndOverlapIncompatibilites,
                        "Options -selectCols and -selectSeqs are not allowed in combination of overlap options (-resoverlap || -seqoverlap)"},
                {ErrorCode::OnlyOneSequencesSelectionMethodAllowed,
                        "Only one method to chose sequences can be applied: (-selectseqs || -clusters || -maxIdentity"},
                {ErrorCode::CombinationAmongTrimmingMethods,
                        "Only one trimming method can be used at the same time, either automatic or manual"},
                {ErrorCode::AutomathicMethodAndBlock,
                        "Combination between automatic methods and -block options is not allowed"},
                {ErrorCode::WindowAndArgumentIncompatibilities,
                        "Combination between general and specific windows is not allowed"},
                {ErrorCode::CombinationAmongThresholdsMethods,
                        "Combination among thresholds are not allowed"},
                {ErrorCode::GeneralAndSpecificWindows,
                        "General window (-w) is not compatible with specific window options: (-cw, -gw, -sw)"},
                {ErrorCode::StatisticsArgumentIncompatibilities,
                        "Parameter [tag] is not valid when statistics' parameters are defined"},
                {ErrorCode::TrimmingMethodNeeded,
                        "Parameter [tag] can only be used with either an automatic or a manual method"},
                {ErrorCode::ForceFileWithoutCompareDataset,
                        "You can not force the alignment selection without setting an alignment dataset to compare against"},
                {ErrorCode::BacktranslationWithoutMainAlignment,
                        "You need to specify an input alignment (-in or -forcefile) to use a Coding Sequence File (-backtranslation) to apply the back translation method"},
                {ErrorCode::NotAligned,
                        "The sequences in the input alignment [tag] should be aligned in order to use any trimming method or statistics"},
                {ErrorCode::MatrixGivenWithNoMethodToUseIt,
                        "The Similarity Matrix can only be used with methods that use this matrix"},
                {ErrorCode::SameNameOutput,
                        "The [tag] and [tag] files can't be the same"},
                {ErrorCode::SequenceAndResiduesOverlapMutuallyNeeded,
                        "Sequence and residues overlap values are mutually needed. You only specified [tag]"},
                {ErrorCode::OutFileNeededWhenPrintingStatistics,
                        "Out file must be specified in order to print any statistics"},
                {ErrorCode::AlignmentTypesNotMatching,
                        "The alignments' datatypes are different. Check your dataset"},
                {ErrorCode::BlocksizeTooBig,
                        "The block size value is too big. Please, choose another one smaller than residues number / 4. In this case, the limit is: [tag]"},
                {ErrorCode::ParemeterOnlyOnBacktranslation,
                        "The [tag] parameter can be only set up with backtranslation functionality"},
                {ErrorCode::ProteinAlignmentMustBeAligned,
                        "The input protein file has to be aligned to carry out the backtranslation process"},
                {ErrorCode::BacktransAlignIsDNA,
                        "Check your Coding sequences file. It has been detected other kind of biological sequences"},
                {ErrorCode::ImpossibleToGenerate,
                        "Impossible to generate [tag]"},
                {ErrorCode::ImpossibleToProcessMatrix,
                        "It's impossible to process the Similarity Matrix"},
                {ErrorCode::SelectOnlyAccepts,
                        "Option [tag] only accepts ranges from 0 to number of [tag] - 1"},
                {ErrorCode::MoreClustersThanSequences,
                        "The number of clusters from the Alignment can not be larger than the number of sequences from that alignment"},
                {ErrorCode::LeftBoundaryBiggerThanRightBoundary,
                        "Check your manually set left '[tag]' and right '[tag]' boundaries'"},
                {ErrorCode::DifferentNumberOfSequencesInCompareset,
                        "The files to compare do not have the same number of sequences"},
                {ErrorCode::DifferentSeqsNamesInCompareset,
                        "Sequences names differ in compareset files"},
                {ErrorCode::CDScontainsProteinSequences,
                        "Check input CDS file. It seems to content protein residues."},
                {ErrorCode::SequenceContainsGap,
                        "Sequence \"[tag]\" has, at least, one gap"},
                {ErrorCode::SequenceNotMultipleOfThree,
                        "Sequence length \"[tag]\" is not multiple of 3 (length: [tag])"},
                {ErrorCode::SequenceHasStopCodon,
                        "Sequence \"[tag]\" has stop codon \"[tag]\" (residue \"[tag]\") at position [tag] (length: [tag])"},
                {ErrorCode::SequenceNotPresentInCDS,
                        "Sequence \"[tag]\" is not in CDS file"},
                {ErrorCode::UnknownCharacter,
                        "The sequence \"[tag]\" has an unknown ([tag]) character"},
                {ErrorCode::SequencesNotSameSize,
                        "The sequence \"[tag]\" ([tag]) does not have the same number of residues fixed by the alignment ([tag])"},
                {ErrorCode::IncorrectSymbol,
                        "the symbol '[tag]' is incorrect"},
                {ErrorCode::UndefinedSymbol,
                        "the symbol '[tag]' accesing the matrix is not defined in this object"},
                {ErrorCode::ParameterNotFoundOrRepeated,
                        "Parameter \"[tag]\" not valid or repeated"},
                {ErrorCode::SimilarityMatrixNotCompatibleWindow,
                        "The Similarity Matrix can only be used with general/similarity windows size"},
                {ErrorCode::PossibleMissmatch,
                        "Possible (\") mismatch for comments"},
                {ErrorCode::BracketsMissmatchFound,
                        "Brackets (]) mismatch found"},
                {ErrorCode::UnalignedAlignmentToAlignedFormat,
                        "Sequences are not aligned. Format ([tag]) not compatible with unaligned sequences."},
                {ErrorCode::CantOpenFile,
                        "File [tag] not found or impossible to open"},
                {ErrorCode::FileIsEmpty,
                        "File [tag] is empty"},
                {ErrorCode::AlignmentFormatNotRecognized,
                        "Alignment not loaded: \"[tag]\". Format couldn't be recognized."},
                {ErrorCode::OutputFormatNotRecognized,
                        "Output format [tag] not recognized"},
                {ErrorCode::OnlyOneFormatOnConsoleOutput,
                        "You must specify only one output format if you don't provide an output file pattern"},
                {ErrorCode::AlignmentNotSaved,
                        "Alignment couldn't be saved on [tag] format"},
                {ErrorCode::VerboseLevelNotRecognized,
                        "Verbose Level specified ([tag]) wasn't recognized. Current level is: [tag]"},
                {ErrorCode::NeedToSpecifyVerboseLevel,
                        "Verbose Level has to be specified after the [tag] argument. Acceptable values are: 'error', 'warning', 'info', 'none' and their numerical equivalents '3', '2', '1' and '0'. Current level is [tag]"},
                {ErrorCode::NoReferenceSequenceForContig,
                        "No reference sequence found for contig \"[tag]\""},
                {ErrorCode::SNPoutOfBounds,
                        "SNP at positon \"[tag]\" in file \"[tag]\" cannot be applied as sequence has a length of \"[tag]\""},
                {ErrorCode::NoInputFile,
                        "An MSA input file has to be provided"},
                {ErrorCode::ComparesetFailedAlignmentMissing,
                        "Compareset couldn't be performed as some alignments are missing"},
                {ErrorCode::GapWindowTooBig,
                        "Gap window size (-gw) provided is too big, please specify a window lesser than 1/4 of residues"},
                {ErrorCode::SimilarityWindowTooBig,
                        "Similarity window size (-sw) provided is too big, please specify a window lesser than 1/4 of residues"},
                {ErrorCode::ConsistencyWindowTooBig,
                        "Consistency window size (-cw) provided is too big, please specify a window lesser than 1/4 of residues"},
                {ErrorCode::WindowTooBig,
                        "Window size (-w) provided is too big, please specify a window lesser than 1/4 of residues"},
                {ErrorCode::AlignmentIsEmpty,
                        "Couldn't output any alignment as it doesn't contain any sequence"},
                {ErrorCode::AlignmentTypeisUnkwnown,
                        "Couldn't perform the trimming step, alignment type unkwnown. "},
        }
Definition at line 292 of file reportsystem.h.
InfoMessages
const std::map< InfoCode, const char * > __internalReport::__reportSystem::InfoMessages static private
Initial value:
=
        {
                {InfoCode::CuttingSequence,
                        "Cutting sequence \"[tag]\" at first appearance of stop codon \"[tag]\""
                                " (residue \"[tag]\") at position [tag] (length: [tag] \")"},
                {InfoCode::WindowSizeCompareset,
                        "Window size (-w) is provided. "
                                "It's recommended to use specific consistency window size (-cw)"
                                " when using -compareset option"},
        }
Definition at line 290 of file reportsystem.h.
WarningMessages
const std::map< WarningCode, const char * > __internalReport::__reportSystem::WarningMessages static private
Initial value:
=
        {
                {WarningCode::RemovingOnlyGapsSequence,
                        "Removing sequence '[tag]' composed only by gaps"},
                {WarningCode::KeepingOnlyGapsSequence,
                        "Keeping sequence '[tag]' composed only by gaps"},
                {WarningCode::SequenceWillBeCutted,
                        "Sequence \"[tag]\" will be cutted at position [tag] (length:[tag])"},
                {WarningCode::IncludingIndeterminationSymbols,
                        "Sequence \"[tag]\" has some indetermination symbols 'X' at the end of sequence. They will be included in the final newAlignment."},
                {WarningCode::LessNucleotidesThanExpected,
                        "Sequence \"[tag]\" has less nucleotides ([tag]) than expected ([tag]). It will be added N's to complete the sequence"},
                {WarningCode::HeaderWillBeCut,
                        "Original sequence header will be cutted by 10 characters"},
                {WarningCode::DonorAlreadyAdded,
                        "The donor \"[tag]\" is present on more than one VCF. The SNP's of all entries will be merged in one single sequence."},
                {WarningCode::ReferenceNucleotideNotCorresponding,
                        "The sequence \"[tag]\" at position \"[tag]\" does not correspond with reference allele in file \"[tag]\". Found \"[tag]\". Expected \"[tag]\""
                }
        }
Definition at line 291 of file reportsystem.h.
The documentation for this class was generated from the following files:
include/reportsystem.h
source/reportsystem.cpp