trimAl: FormatManager Class Reference
FormatManager Class Reference
Class to handle Format Handlers .
It serves as a proxy to the handlers, so the code outside the FormatManager is format-agnostic.
#include <FormatManager.h>
Public Member Functions
FormatManager ()
~FormatManager ()
Alignment * loadAlignment (std::string inFile)
Function that loads an alignment given a file path. It automatically detects the format of the file.
bool saveAlignment (std::string outPattern, std::vector< std::string > *outFormats, Alignment *alignment)
Function to save an alignment to a file. It searches among the available_states one that can write the alignment in the specified format.
void loadAndSaveMultipleAlignments (std::vector< std::string > *inFile, std::string *outPattern, std::vector< std::string > *outFormats)
Function that takes multiple files, loads them and saves in a cumulus of formats, using an outPattern.
std::string getFileFormatName (std::string inFile)
Function to obtain the format name of a given file.
std::string getInputFormatsAvailable ()
Function to obtain all format names available by this object that can load an alignment.
std::string getOutputFormatsAvailable ()
Function to obtain all format names available by this object that can save an alignment.
std::vector< Alignment * > splitAlignmentKeeping (Alignment &alignment)
Function to divide an alignment into different alignments, each one with a sequence from the original.
This function does a deep copy of each sequence, so the original alignment can be deleted after being splitted.
Public Attributes
bool hasOutputFile = true
Tag to know if the machine has an output file or it has to output to console.
bool keepHeader = false
Tag to know if the machine should keep original headers.
bool reverse = false
Tag to know if sequences should be reversed before saving them.
bool format = false
Tag to know if the machine should output the format information about the alignment.
bool type = false
Tag to know if the machine should output the type of the alignment.
bool info = false
Tag to know if the machine should output the information of the alignment.
Private Member Functions
void addState (BaseFormatHandler *newState)
Function that adds a newState to the FormatManager::available_states vector.
This should be called on the constructor function foreach format existent.
Private Attributes
std::vector< BaseFormatHandler * > available_states
Detailed Description
Class to handle Format Handlers .
It serves as a proxy to the handlers, so the code outside the FormatManager is format-agnostic.
Note
The Format Handlers are added automatically by CMake, on CMake configuration.
This is achieved by creating the file include/FormatHandling/formats_header.h , which implements the FormatManager constructor.
Definition at line 25 of file FormatManager.h.
Constructor & Destructor Documentation
FormatManager()
FormatManager::FormatManager ()
Definition at line 28 of file formats_header.h.
 {
     addState(new clustal_state(this));
     addState(new fasta_m10_state(this));
     addState(new fasta_state(this));
     addState(new htmlreport_state(this));
     addState(new mega_interleaved_state(this));
     addState(new mega_sequential_state(this));
     addState(new nexus_m10_state(this));
     addState(new nexus_state(this));
     addState(new phylip32_m10_state(this));
     addState(new phylip32_state(this));
     addState(new phylip40_m10_state(this));
     addState(new phylip40_state(this));
     addState(new phylip_paml_m10_state(this));
     addState(new phylip_paml_state(this));
     addState(new pir_state(this));
 }
References addState().
~FormatManager()
FormatManager::~FormatManager ()
Definition at line 8 of file BaseFormatHandler.cpp.
 {
     for(BaseFormatHandler* child : available_states) {
         delete child;
     }
 }
References available_states.
Member Function Documentation
addState()
void FormatManager::addState (BaseFormatHandler * newState) private
Function that adds a newState to the FormatManager::available_states vector.
This should be called on the constructor function foreach format existent.
Parameters
newState Pointer to the newState we want to instantiate.
Definition at line 15 of file BaseFormatHandler.cpp.
 {
     this -> available_states.push_back(newState);
 }
References available_states.
Referenced by FormatManager().
getFileFormatName()
std::string FormatManager::getFileFormatName (std::string inFile)
Function to obtain the format name of a given file.
Parameters
inFile File path of the file which we want to obtain it's format.
Definition at line 285 of file BaseFormatHandler.cpp.
 {
     std::ifstream inFileHandler;
     // Open file.
     inFileHandler.open(inFile);
     if (!inFileHandler.is_open())
     {
         debug.report(ErrorCode::CantOpenFile, &inFile[0]);
         return "Unknown";
     }
     else if (inFileHandler.peek() == std::ifstream::traits_type::eof())
     {
         debug.report(ErrorCode::FileIsEmpty, &inFile[0]);
         return "None";
     }
     BaseFormatHandler* inState = nullptr;
     int format_value = 0;
     int temp_value = 0;
     // Get format State that can handle this alignment.
     for(BaseFormatHandler* state : available_states)
     {
         temp_value = state -> CheckAlignment(&inFileHandler);
         if (temp_value > format_value)
         {
             format_value = temp_value;
             inState = state;
         }
     }
     // Check if there is a format State to handle the alignment.
     if (inState == nullptr)
     {
         inFileHandler.close();
         return "Unknown";
     }
     return inState->name;
 }
References available_states, CantOpenFile, debug, FileIsEmpty, BaseFormatHandler::name, and reporting::reportManager::report().
Referenced by trimAlManager::check_output_format(), main(), and statistics::Consistency::perform().
getInputFormatsAvailable()
std::string FormatManager::getInputFormatsAvailable ()
Function to obtain all format names available by this object that can load an alignment.
Definition at line 328 of file BaseFormatHandler.cpp.
 {
     std::stringstream ss("");
     for (BaseFormatHandler* state : available_states)
     {
         if (state->canLoad)
             ss << state->name << ", " ;
     }
     ss.seekp(-2, std::ios_base::end);
     ss << "  ";
     return ss.str();
 }
References available_states.
Referenced by trimAlManager::help_arguments(), menu(), and trimAlManager::menu().
getOutputFormatsAvailable()
std::string FormatManager::getOutputFormatsAvailable ()
Function to obtain all format names available by this object that can save an alignment.
Definition at line 344 of file BaseFormatHandler.cpp.
 {
     std::stringstream ss("");
     for (BaseFormatHandler* state : available_states)
     {
         if (state->canSave)
             ss << state->name << ", " ;
     }
     ss.seekp(-2, std::ios_base::end);
     ss << "  ";
     return ss.str();
 }
References available_states.
Referenced by trimAlManager::help_arguments(), menu(), and trimAlManager::menu().
loadAlignment()
Alignment * FormatManager::loadAlignment (std::string inFile)
Function that loads an alignment given a file path. It automatically detects the format of the file.
Parameters
inFile File path of the alignment to load.
Returns
Pointer to the alignment if it could be loaded.
Null if not.
Definition at line 20 of file BaseFormatHandler.cpp.
 {
     // Check input file.
     std::ifstream inFileHandler;
     inFileHandler.open(inFile);
     if (!inFileHandler.is_open())
     {
         debug.report(ErrorCode::CantOpenFile, &inFile[0]);
         return nullptr;
     }
     else if (inFileHandler.peek() == std::ifstream::traits_type::eof())
     {
         debug.report(ErrorCode::FileIsEmpty, &inFile[0]);
         return nullptr;
     }
     BaseFormatHandler* inState = nullptr;
     int format_value = 0;
     int temp_value = 0;
     for(BaseFormatHandler* state : available_states)
     {
         temp_value = state -> CheckAlignment(&inFileHandler);
         if (temp_value > format_value)
         {
             format_value = temp_value;
             inState = state;
         }
     }
     if (inState == nullptr)
     {
         debug.report(ErrorCode::AlignmentFormatNotRecognized, &inFile[0]);
         inFileHandler.close();
         return nullptr;
     }
     Alignment* alignment = inState->LoadAlignment(inFile);
     inFileHandler.close();
     return alignment;
 }
References AlignmentFormatNotRecognized, available_states, CantOpenFile, debug, FileIsEmpty, BaseFormatHandler::LoadAlignment(), and reporting::reportManager::report().
Referenced by trimAlManager::back_trans_argument(), trimAlManager::force_select_argument(), trimAlManager::in_argument(), main(), and statistics::Consistency::perform().
loadAndSaveMultipleAlignments()
void FormatManager::loadAndSaveMultipleAlignments (std::vector< std::string > * inFile, std::string * outPattern, std::vector< std::string > * outFormats)
Function that takes multiple files, loads them and saves in a cumulus of formats, using an outPattern.
Parameters
inFile Vector of files to load, reformat and save.
outPattern Path and name of the new files.
The function changes some optional tokens on the original string to obtain multiple versions:
[in] Token that is changed with the original filename without extension.
[format] Token that is changed with the new format name.
[extension] Token that is changed with the format file extensions.
Note
This method should be used in combination of the output tag system, which allows to reuse the name of the original alignment, in the new output, along the new format and extension. Otherwise, the system would overwrite the same file over and over.
Parameters
outFormats Output formats that original files should reformat to.
Definition at line 181 of file BaseFormatHandler.cpp.
 {
     // Get all the output format states needed.
     std::vector<BaseFormatHandler*> outStates = std::vector<BaseFormatHandler*>();
     {
         bool recognized;
         for (std::string outFormat : *outFormats)
         {
             recognized = false;
             for(BaseFormatHandler* state : available_states)
             {
                 if (state->RecognizeOutputFormat(outFormat))
                 {
                     outStates.push_back(state);
                     recognized = true;
                     break;
                 }
             }
             if (!recognized)
             {
                 debug.report(ErrorCode::OutputFormatNotRecognized, &outFormat[0]);
                 return;
             }
         }
     }
     // Process input files one by one.
     BaseFormatHandler* inState = nullptr;
     std::ifstream inFileHandler;
     int format_value = 0;
     int temp_value = 0;
     for (std::string inFile : *inFiles)
     {
         // Open file.
         inFileHandler.open(inFile);
         if (!inFileHandler.is_open())
         {
             debug.report(ErrorCode::CantOpenFile, &inFile[0]);
             return;
         }
         else if (inFileHandler.peek() == std::ifstream::traits_type::eof())
         {
             debug.report(ErrorCode::FileIsEmpty, &inFile[0]);
             return;
         }
         inState = nullptr;
         format_value = 0;
         // Get format State that can handle this alignment.
         for(BaseFormatHandler* state : available_states)
         {
             temp_value = state -> CheckAlignment(&inFileHandler);
             if (temp_value > format_value)
             {
                 format_value = temp_value;
                 inState = state;
             }
         }
         // Check if there is a format State to handle the alignment.
         if (inState == nullptr)
         {
             debug.report(ErrorCode::AlignmentFormatNotRecognized, &inFile[0]);
             inFileHandler.close();
             return;
         }
         // Load alignment one by one and store it on each of the formats specified.
         Alignment* alignment = inState->LoadAlignment(inFile);
         unsigned long start;
         unsigned long end;
         inFileHandler.close();
         {
             std::string filename;
             std::ofstream outFileHandler;
             for (BaseFormatHandler * state : outStates)
             {
                 start = std::max((int)inFile.find_last_of('/'), 0);
                 end = inFile.find_last_of('.');
                 filename = utils::ReplaceString(*outPattern, "[in]", inFile.substr(start, end-start));
                 utils::ReplaceStringInPlace(filename, "[extension]", state->extension);
                 utils::ReplaceStringInPlace(filename, "[format]", state->name);
                 outFileHandler.open(filename);
                 if (this->hasOutputFile)
                     state -> SaveAlignment(alignment, &outFileHandler);
                 else
                     state -> SaveAlignment(alignment, &std::cout);
                 outFileHandler.close();
             }
         }
         delete alignment;
     }
 }
References AlignmentFormatNotRecognized, available_states, CantOpenFile, debug, FileIsEmpty, hasOutputFile, BaseFormatHandler::LoadAlignment(), utils::max(), OutputFormatNotRecognized, utils::ReplaceString(), utils::ReplaceStringInPlace(), and reporting::reportManager::report().
Referenced by main().
saveAlignment()
bool FormatManager::saveAlignment (std::string outPattern, std::vector< std::string > * outFormats, Alignment * alignment)
Function to save an alignment to a file. It searches among the available_states one that can write the alignment in the specified format.
Parameters
outPattern File path to save the alignment.
outFormats Format in which save the alignment.
alignment Alignment
Definition at line 63 of file BaseFormatHandler.cpp.
 {
     StartTiming("bool FormatManager::saveAlignment()");
     if (alignment->numberOfResidues == 0 || alignment->numberOfSequences == 0)
     {
         debug.report(ErrorCode::AlignmentIsEmpty);
         return false;
     }
     std::string filename;
     unsigned long start;
     unsigned long end;
     if (alignment->filename.empty())
     {
         filename = utils::ReplaceString(outPattern, "[in]", "NoInputFileName");
     }
     else
     {
         start = std::max((int)alignment->filename.find_last_of('/'), 0);
         end = alignment->filename.find_last_of('.');
         filename = utils::ReplaceString(outPattern, "[in]", alignment->filename.substr(start, end-start));
     }
     if (outPattern.empty())
     {
         if (outFormats->empty())
         {
             outFormats->push_back("fasta");
         }
         if (outFormats->size() == 1)
         {
             for(BaseFormatHandler* state : available_states)
             {
                 if (state->RecognizeOutputFormat( outFormats->at(0) ))
                 {
                     return state->SaveAlignment(alignment, &std::cout);
                 }
             }
             debug.report(ErrorCode::OutputFormatNotRecognized, &outFormats->at(0)[0]);
             return false;
         }
         else
         {
             debug.report(ErrorCode::OnlyOneFormatOnConsoleOutput);
             return false;
         }
     }
     else
     {
         if (outFormats->empty())
         {
             outFormats->push_back("fasta");
         }
         if (outFormats->size() == 1)
         {
             for(BaseFormatHandler* state : available_states)
             {
                 if (state->RecognizeOutputFormat( outFormats->at(0) ))
                 {
                     utils::ReplaceStringInPlace(filename, "[extension]", state->extension);
                     utils::ReplaceStringInPlace(filename, "[format]", state->name);
                     std::ofstream outFileHandler;
                     outFileHandler.open(filename);
                     return state->SaveAlignment(alignment, &outFileHandler);
                 }
             }
             debug.report(ErrorCode::OutputFormatNotRecognized, &outFormats->at(0)[0]);
             return false;
         }
         else
         {
             // Tranform the list of std::string states to a BaseFormatHandler list.
             bool recognized;
             std::vector<BaseFormatHandler*> outStates = std::vector<BaseFormatHandler*>();
             {
                 for (std::string outFormat : *outFormats)
                 {
                     recognized = false;
                     for(BaseFormatHandler* state : available_states)
                     {
                         if (state->RecognizeOutputFormat(outFormat))
{
                             outStates.push_back(state);
                             recognized = true;
                         }
                     }
                     if (!recognized)
                     {
                         debug.report(ErrorCode::OutputFormatNotRecognized, &outFormat[0]);
                         return false;
                     }
                 }
             }
             std::ofstream outFileHandler;
             bool isCorrect = true;
             std::string filename_2;
             for (BaseFormatHandler * state : outStates)
             {
                 filename_2 = utils::ReplaceString(filename, "[extension]", state->extension);
                 utils::ReplaceStringInPlace(filename_2, "[format]", state->name);
                 outFileHandler.open(filename_2);
                 if(!state -> SaveAlignment(alignment, &outFileHandler))
                 {
                     debug.report(ErrorCode::AlignmentNotSaved, &state->name[0]);
                     isCorrect = false;
                 }
                 outFileHandler.close();
             }
             if (!isCorrect)
                 debug.report(ErrorCode::ImpossibleToGenerate, new std::string[1]{"the output file"});
             return isCorrect;
         }
     }
 }
References AlignmentIsEmpty, AlignmentNotSaved, available_states, debug, Alignment::filename, ImpossibleToGenerate, utils::max(), Alignment::numberOfResidues, Alignment::numberOfSequences, OnlyOneFormatOnConsoleOutput, OutputFormatNotRecognized, utils::ReplaceString(), utils::ReplaceStringInPlace(), reporting::reportManager::report(), and StartTiming.
Referenced by main(), trimAlManager::perform_VCF(), and trimAlManager::save_alignment().
splitAlignmentKeeping()
std::vector< Alignment * > FormatManager::splitAlignmentKeeping (Alignment & alignment)
Function to divide an alignment into different alignments, each one with a sequence from the original.
This function does a deep copy of each sequence, so the original alignment can be deleted after being splitted.
Definition at line 360 of file BaseFormatHandler.cpp.
 {
     std::vector<Alignment *> splitted = std::vector<Alignment *>(alignment.originalNumberOfSequences);
     for (int i = 0; i < alignment.originalNumberOfSequences; i++)
     {
         Alignment * tempAlignment = new Alignment();
         tempAlignment->sequences = new std::string[1];
         tempAlignment->sequences[0] = std::string(alignment.sequences[i]);
         tempAlignment->seqsName = new std::string[1] { alignment.seqsName[i] };
         tempAlignment->numberOfSequences = 1;
         tempAlignment->originalNumberOfSequences = 1;
         tempAlignment->numberOfResidues = tempAlignment->sequences[0].size();
         tempAlignment->originalNumberOfResidues = tempAlignment->numberOfResidues;
         tempAlignment->filename = tempAlignment->seqsName[0];
         splitted[i] = tempAlignment;
     }
     return splitted;
 }
References Alignment::filename, Alignment::numberOfResidues, Alignment::numberOfSequences, Alignment::originalNumberOfResidues, Alignment::originalNumberOfSequences, Alignment::seqsName, and Alignment::sequences.
Referenced by trimAlManager::perform_VCF().
Member Data Documentation
available_states
std::vector<BaseFormatHandler*> FormatManager::available_states private
 \brief Vector that contains the available formats to load/save from.\n
        They are loaded into the format in the constructor function.
 \note The formats (\link BaseFormatHandler \endlink) are hard-coded loaded,
    and thus so when a new format is implemented, it has to be added 'manually'.
    There is a workaround for this, done on CMake, which creates the constructor of the class.
    This on-the-fly constructor implements all states found, using some rules.\n
Note
This file includes all States found, and also defines the ReadWriteMS constructor.
To be able to be automatically recognized, the new state should:
Have the same Class Name as File Name (without the extension)
Name must end with '_state'
Be placed on ReadWriteMS folder
Definition at line 47 of file FormatManager.h.
Referenced by addState(), getFileFormatName(), getInputFormatsAvailable(), getOutputFormatsAvailable(), loadAlignment(), loadAndSaveMultipleAlignments(), saveAlignment(), and ~FormatManager().
format
bool FormatManager::format = false
Tag to know if the machine should output the format information about the alignment.
Definition at line 69 of file FormatManager.h.
Referenced by checkArguments(), main(), and parseArguments().
hasOutputFile
bool FormatManager::hasOutputFile = true
Tag to know if the machine has an output file or it has to output to console.
Definition at line 60 of file FormatManager.h.
Referenced by checkArguments(), and loadAndSaveMultipleAlignments().
info
bool FormatManager::info = false
Tag to know if the machine should output the information of the alignment.
Definition at line 75 of file FormatManager.h.
Referenced by checkArguments(), main(), and parseArguments().
keepHeader
bool FormatManager::keepHeader = false
Tag to know if the machine should keep original headers.
Definition at line 62 of file FormatManager.h.
Referenced by trimAlManager::keep_header_argument(), and parseArguments().
reverse
bool FormatManager::reverse = false
Tag to know if sequences should be reversed before saving them.
Definition at line 64 of file FormatManager.h.
Referenced by parseArguments().
type
bool FormatManager::type = false
Tag to know if the machine should output the type of the alignment.
Definition at line 72 of file FormatManager.h.
Referenced by checkArguments(), main(), and parseArguments().
The documentation for this class was generated from the following files:
/home/vfernandez/git/trimAl/include/FormatHandling/FormatManager.h
/home/vfernandez/git/trimAl/include/FormatHandling/formats_header.h
/home/vfernandez/git/trimAl/source/FormatHandling/BaseFormatHandler.cpp