trimAl: sequencesMatrix Class Reference
sequencesMatrix Class Reference
Class that represents a sequences matrix.
#include <sequencesMatrix.h>
Public Member Functions
sequencesMatrix ()
Null constructor.
sequencesMatrix (string *alignmentMatrix, string *alignmentSeqsName, int sequences, int residues)
Manual constructor.
sequencesMatrix (newAlignment *parent)
Automatic constructor.
sequencesMatrix & operator= (const sequencesMatrix &)
~sequencesMatrix ()
Destructor.
void printMatrix ()
Sequences Matrix printing method.
void getColumn (int column, int *numResidueseqMatrix)
Method to get a column out of the matrix.
void getColumn (int value, int row, int *columnSeqMatrix)
Method that looks to value in a row and stores a column's, corresponding to row, sequences matrix in a vector.
void setOrder (int *order)
Method that reorders the stored sequences with a given order list.
bool getSequence (string seqName, int *sequence)
Method to obtain a sequence based on its name.
int getSeqNumber ()
Number of sequences getter.
int getResidNumber ()
Number of residues getter.
Private Attributes
int resNumber
Number of residues per sequence.
int seqsNumber
Number of sequences in the matrix.
int ** matrix
Matrix container.
It contains the sequences and residues of each sequence.
string * seqsName
Sequences names container.
newAlignment * _alignment
Pointer to the alignment this object is related to.
Detailed Description
Class that represents a sequences matrix.
A Sequence matrix is a 2D matrix that represents MSA without any gaps included.
This class stores the alignment sequences matrix.
It provides methods to build the sequences matrix and print the matrix. It also provides methods for look to a column in the matrix and for look to value at the position (row, column) in the matrix.
See:
statisticsConsistency::compareAndChoose
statisticsConsistency::forceComparison
Definition at line 52 of file sequencesMatrix.h.
Constructor & Destructor Documentation
sequencesMatrix() [1/3]
sequencesMatrix::sequencesMatrix (void)
Null constructor.
This construction method initializes all attributes of the new object with 0 or nullptr value.
Definition at line 31 of file sequencesMatrix.cpp.
References matrix, resNumber, seqsName, and seqsNumber.
sequencesMatrix() [2/3]
sequencesMatrix::sequencesMatrix (string * alignmentMatrix, string * alignmentSeqsName, int sequences, int residues)
Manual constructor.
This construction method initializes all attributes using the information passed as arguments.
Parameters
alignmentMatrix Sequences of the alignment to convert to sequenceMatrix
alignmentSeqsName Sequences names
sequences Number of sequences
residues Number of residues
Definition at line 75 of file sequencesMatrix.cpp.
References utils::initlVect(), matrix, resNumber, seqsName, and seqsNumber.
sequencesMatrix() [3/3]
sequencesMatrix::sequencesMatrix (newAlignment * parent) explicit
Automatic constructor.
This construction method initializes all attributes using the information present in the alignment pointer passed.
Parameters
alignmentMatrix Sequences of the alignment to convert to sequenceMatrix
alignmentSeqsName Sequences names
sequences Number of sequences
residues Number of residues
Definition at line 44 of file sequencesMatrix.cpp.
References _alignment, utils::initlVect(), matrix, newAlignment::originalResidNumber, newAlignment::originalSequenNumber, resNumber, seqsName, newAlignment::seqsName, seqsNumber, and newAlignment::sequences.
~sequencesMatrix()
sequencesMatrix::~sequencesMatrix ()
Destructor.
Destruction method that frees, if exists, previously allocated memory.
Definition at line 129 of file sequencesMatrix.cpp.
References matrix, resNumber, seqsName, and seqsNumber.
Member Function Documentation
getColumn() [1/2]
void sequencesMatrix::getColumn (int column, int * numResidueseqMatrix)
Method to get a column out of the matrix.
Parameters
column Column number at sequences matrix.
[out] numResidueseqMatrix Vector where storage a column's sequences matrix.
Method that storages a column's sequences matrix in a vector.
Definition at line 165 of file sequencesMatrix.cpp.
References matrix, resNumber, and seqsNumber.
Referenced by statisticsConsistency::compareAndChoose(), and statisticsConsistency::forceComparison().
getColumn() [2/2]
void sequencesMatrix::getColumn (int value, int row, int * columnSeqMatrix)
Method that looks to value in a row and stores a column's, corresponding to row, sequences matrix in a vector.
Parameters
value to look in a row's sequences matrix.
row where to look for a value.
columnSeqMatrix Vector where storage a column's sequences matrix.
Definition at line 181 of file sequencesMatrix.cpp.
References matrix, resNumber, and seqsNumber.
getResidNumber()
int sequencesMatrix::getResidNumber (void)
Number of residues getter.
Returns
Number of residues.
Definition at line 247 of file sequencesMatrix.cpp.
References resNumber.
getSeqNumber()
int sequencesMatrix::getSeqNumber (void)
Number of sequences getter.
Returns
Number of sequences.
Definition at line 240 of file sequencesMatrix.cpp.
References seqsNumber.
getSequence()
bool sequencesMatrix::getSequence (string seqName, int * sequence)
Method to obtain a sequence based on its name.
Parameters
seqName Name of the sequence to find.
[out] sequence Where to store the sequence.
Returns
True if found. False if not.
Definition at line 221 of file sequencesMatrix.cpp.
References matrix, resNumber, seqsName, and seqsNumber.
printMatrix()
void sequencesMatrix::printMatrix (void)
Sequences Matrix printing method.
Method that prints the alignment sequences matrix.
Warning
Not In Use
Definition at line 148 of file sequencesMatrix.cpp.
References matrix, resNumber, and seqsNumber.
setOrder()
void sequencesMatrix::setOrder (int * order)
Method that reorders the stored sequences with a given order list.
Parameters
order Pointer that contains the new order we want to give the matrix.
Definition at line 199 of file sequencesMatrix.cpp.
References matrix, resNumber, and seqsNumber.
Referenced by statisticsConsistency::compareAndChoose(), and statisticsConsistency::forceComparison().
The documentation for this class was generated from the following files:
include/sequencesMatrix.h
source/sequencesMatrix.cpp