trimAl: utils Namespace Reference
utils Namespace Reference
Utilities class. This class contains shared methods to be used in multiple parts of the code.
Functions
void initlVect (int *vector, int tam, int valor)
Vector initialization.
void initlVect (float *vector, int tam, float valor)
Vector initialization.
void copyVect (int *vect1, int *vect2, int tam)
Integer vector copying.
void copyVect (float *vect1, float *vect2, int tam)
Float vector copying.
int roundToInf (double number)
Round double to inferior integer method.
int roundInt (double number)
Round double to integer method.
int roundToSup (double number)
Round double to greater integer method.
int max (int x, int y)
Maximum of two numbers method.
float max (float x, float y)
Maximum of two numbers method.
double max (double x, double y)
Maximum of two numbers method.
int min (int x, int y)
Minimum of two numbers method.
float min (float x, float y)
Minimum of two numbers method.
double min (double x, double y)
Minimum of two numbers method.
bool isNumber (char *num)
String-is-number checking.
bool compare (char *a, char *b)
String comparing method.
void removeSpaces (char *in, char *out)
Removing spaces method.
void quicksort (float *list, int ini, int fin)
Quicksort sorting method.
void swap (float *a, float *b)
Swapping elements method.
void quicksort (int *list, int ini, int fin)
Quicksort sorting method.
void swap (int *a, int *b)
Swapping elements method.
bool checkFile (std::ifstream &file)
Check if a given file exists and its size is greater than 0.
char * readLine (std::ifstream &file)
Read a new line from current input stream.
This function is better than standard one since cares of operative system compatibility.
It is useful as well because removes tabs and blank spaces at lines at beginning/ending.
.
char * readLine (std::istream &file)
Read a new line from current input stream.
This function is better than standard one since cares of operative system compatibility.
It is useful as well because removes tabs and blank spaces at lines at beginning/ending.
.
char * trimLine (std::string nline)
Remove all content surrounded by ("") or ([]).
It warns as well when a mismatch for these flags is found.
.
std::string getReverse (std::string toReverse)
Reverses a string.
std::string removeCharacter (char c, std::string line)
Removes a determined char from the string.
int checkAlignmentType (int seqNumber, int residNumber, std::string *sequences)
Checks an alignment type.
int * readNumbers (std::string line)
Reads a line and converts it to an array of number.
void quicksort (int **vect, int ini, int fin)
Quicksort sorting method.
void swap (int **a, int **b)
Swaps double pointers.
char determineColor (char res, const std::string &column)
Checks the color that has to be used on the output report.
bool lookForPattern (const std::string &data, const std::string &pattern, const float threshold)
Method to check for a pattern in a string.
The method will check, character by character of the first string if there is some equality for each character in the pattern.
When done, it will calculate the fraction of characters present in the pattern and compare to the threshold argument.
void ReplaceStringInPlace (std::string &subject, const std::string &search, const std::string &replace)
Function that replaces a substring with another substring in a string. It does not make a copy of the original string, but modifies it.
std::string ReplaceString (std::string subject, const std::string &search, const std::string &replace)
Function that replaces a substring with another substring in a string. It makes a copy of the original string.
int GetGapStep (int *gapValue, int sequenNumber)
Function that gives the gap classification of a column of values.
int GetGapStep (int *gapValue, float inverseSequenNumber)
Function that gives the gap classification of a column of values.
This function should work faster than it's sister utils::GetGapStep(int * gapValue, int sequenNumber), as it uses a precomputed (by the user) inverseSequenNumber (1F / Alignment::sequenNumber), instead of calculating it over again each time the function is called (which is equal to number of residues).
This comes with a precision cost that shouldn't be a problem.
int GetSimStep (float *simValue)
Function that gives the similarity classification of a column of values.
int GetConsStep (float *consValue)
Function that gives the consistency classification of a column of values.
char toUpper (char c)
void streamSVG (float *x, float *y, int num, std::string *lineName, std::string *lineColor, std::string *chartTitle, std::string *filename)
Detailed Description
Utilities class. This class contains shared methods to be used in multiple parts of the code.
Function Documentation
checkAlignmentType()
int utils::checkAlignmentType (int seqNumber, int residNumber, std::string * sequences)
Checks an alignment type.
Parameters
seqNumber Number of sequences to check it's type.
residNumber Number of residues of the alignment.
sequences Sequences pointer
Returns
Integer that represents the alignment type.
Definition at line 497 of file utils.cpp.
References AA, DEG, DNA, NotDefined, and RNA.
Referenced by Alignment::getAlignmentType().
checkFile()
bool utils::checkFile (std::ifstream & file)
Check if a given file exists and its size is greater than 0.
Parameters
file ifstream to check
Definition at line 283 of file utils.cpp.
compare()
bool utils::compare (char * a, char * b)
String comparing method.
Parameters
a The first string that will be compared.
b The second string that will be compared.
Returns
true if the two strings are the same, false if not.
This method compares the two strings given, and returns true if the two strings are equal.
Definition at line 137 of file utils.cpp.
Referenced by Alignment::sequencesMatrix::getSequence(), and statistics::Consistency::perform().
copyVect() [1/2]
void utils::copyVect (int * vect1, int * vect2, int tam)
Integer vector copying.
Parameters
vect1 Vector that we want to copy.
[out] vect2 Destination vector of the copy.
tam Vectors size.
This method copies integer vector 1 to integer vector 2.
Definition at line 49 of file utils.cpp.
Referenced by statistics::Similarity::calcCutPoint(), Cleaner::cleanCompareFile(), statistics::Mold::printAccumulative(), statistics::Similarity::printConservationAcl(), statistics::Gaps::printGapsColumns(), statistics::Consistency::printStatisticsFileAcl(), and trimAlManager::svg_stats_out().
copyVect() [2/2]
void utils::copyVect (float * vect1, float * vect2, int tam)
Float vector copying.
Parameters
vect1 Vector that we want to copy.
[out] vect2 Destination vector of the copy.
tam Vectors size.
This method copies float vector 1 to float vector 2.
Definition at line 55 of file utils.cpp.
determineColor()
char utils::determineColor (char res, const std::string & column)
Checks the color that has to be used on the output report.
Parameters
res Resiude to check its color
column Column to which this residue belongs.
Returns
Char that represents the color to be used.
Definition at line 614 of file utils.cpp.
References lookForPattern().
Referenced by Alignment::alignmentSummaryHTML(), and Alignment::alignmentSummarySVG().
GetConsStep()
int utils::GetConsStep (float * consValue)
Function that gives the consistency classification of a column of values.
Parameters
consValue Consistency value.
Returns
Int representing the classification of this gap value.
Definition at line 861 of file utils.cpp.
GetGapStep() [1/2]
int utils::GetGapStep (int * gapValue, int sequenNumber)
Function that gives the gap classification of a column of values.
Parameters
gapValue Number of gaps present in the column.
sequenNumber Number of sequences.
Returns
Int representing the classification of this gap value.
Definition at line 773 of file utils.cpp.
GetGapStep() [2/2]
int utils::GetGapStep (int * gapValue, float inverseSequenNumber)
Function that gives the gap classification of a column of values.
This function should work faster than it's sister utils::GetGapStep(int * gapValue, int sequenNumber), as it uses a precomputed (by the user) inverseSequenNumber (1F / Alignment::sequenNumber), instead of calculating it over again each time the function is called (which is equal to number of residues).
This comes with a precision cost that shouldn't be a problem.
Parameters
gapValue Number of gaps present in the column.
inverseSequenNumber Inverse of number of sequences. (1F / sequenNumber)
Returns
Int representing the classification of this gap value.
Definition at line 804 of file utils.cpp.
getReverse()
std::string utils::getReverse (std::string toReverse)
Reverses a string.
Parameters
toReverse String to get a reversed copy.
Returns
Reversed string of toReverse.
Definition at line 474 of file utils.cpp.
GetSimStep()
int utils::GetSimStep (float * simValue)
Function that gives the similarity classification of a column of values.
Parameters
simValue Similarity value.
Returns
Int representing the classification of this gap value.
Definition at line 834 of file utils.cpp.
initlVect() [1/2]
void utils::initlVect (int * vector, int tam, int valor)
Vector initialization.
Parameters
[out] vector The vector that will be initialized.
tam The size of the vector.
valor The initialization value that will of all positions of the vector.
This method is used to initialize all positions of a vector with a given value.
Definition at line 38 of file utils.cpp.
Referenced by statistics::Gaps::applyWindow(), statistics::Gaps::calcCutPoint2ndSlope(), statistics::Gaps::calcCutPointMixSlope(), Cleaner::cleanCombMethods(), statistics::Consistency::compareAndChoose(), statistics::Consistency::forceComparison(), statistics::Gaps::Gaps(), statistics::similarityMatrix::loadSimMatrix(), Alignment::sequencesMatrix::sequencesMatrix(), and statistics::Similarity::Similarity().
initlVect() [2/2]
void utils::initlVect (float * vector, int tam, float valor)
Vector initialization.
Parameters
[out] vector The vector that will be initialized.
tam The size of the vector.
valor The initialization value of all positions of the vector.
This method is used to initialize all positions of a vector with a given value.
Definition at line 44 of file utils.cpp.
isNumber()
bool utils::isNumber (char * num)
String-is-number checking.
Parameters
num The string we want to check.
Returns
true if the string is a number, false if not.
This method checks if the given string is a number (taking in mind the possibility of floating numbers and scientific notation)
Definition at line 114 of file utils.cpp.
Referenced by trimAlManager::block_argument(), trimAlManager::clusters_argument(), trimAlManager::conservation_threshold_argument(), trimAlManager::consistency_threshold_argument(), trimAlManager::consistency_window_argument(), trimAlManager::gap_threshold_argument(), trimAlManager::gap_window_argument(), trimAlManager::max_identity_argument(), trimAlManager::residue_overlap_argument(), trimAlManager::sequence_overlap_argument(), trimAlManager::similarity_threshold_argument(), trimAlManager::similarity_window_argument(), and trimAlManager::window_argument().
lookForPattern()
bool utils::lookForPattern (const std::string & data, const std::string & pattern, const float threshold)
Method to check for a pattern in a string.
The method will check, character by character of the first string if there is some equality for each character in the pattern.
When done, it will calculate the fraction of characters present in the pattern and compare to the threshold argument.
Parameters
data string that will be compared against a pattern
pattern string that contains the pattern.
threshold minimum ratio of hits to consider the pattern valid
Definition at line 732 of file utils.cpp.
References toUpper().
Referenced by determineColor().
max() [1/3]
int utils::max (int x, int y)
Maximum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The maximum between the two given numbers.
This method returns the maximum between the two numbers given as parameters.
Definition at line 78 of file utils.cpp.
Referenced by Alignment::alignmentSummaryHTML(), Alignment::alignmentSummarySVG(), statistics::Gaps::calcCutPoint(), statistics::Gaps::calcCutPoint2ndSlope(), statistics::Gaps::calcCutPointMixSlope(), Alignment::calculateColIdentity(), Cleaner::calculateRepresentativeSeq(), statistics::Consistency::compareAndChoose(), Cleaner::getCutPointClusters(), FormatHandling::FormatManager::loadAndSaveMultipleAlignments(), statistics::Mold::printAccumulative(), Alignment::printAlignmentInfo(), statistics::Mold::printByColumn(), Alignment::printSeqIdentity(), Alignment::printSeqOverlap(), and FormatHandling::FormatManager::saveAlignment().
max() [2/3]
float utils::max (float x, float y)
Maximum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The maximum between the two given numbers.
This method returns the maximum between the two numbers given as parameters.
Definition at line 84 of file utils.cpp.
max() [3/3]
double utils::max (double x, double y)
Maximum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The maximum between the two given numbers.
This method returns the maximum between the two numbers given as parameters.
Definition at line 90 of file utils.cpp.
min() [1/3]
int utils::min (int x, int y)
Minimum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The minumum between the two given numbers.
This method returns the minimum between the two numbers given as parameters.
Definition at line 96 of file utils.cpp.
Referenced by Alignment::alignmentSummarySVG(), Alignment::checkCorrespondence(), Cleaner::cleanCompareFile(), Cleaner::getCutPointClusters(), Alignment::printAlignmentInfo(), and streamSVG().
min() [2/3]
float utils::min (float x, float y)
Minimum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The minumum between the two given numbers.
This method returns the minimum between the two numbers given as parameters.
Definition at line 102 of file utils.cpp.
min() [3/3]
double utils::min (double x, double y)
Minimum of two numbers method.
Parameters
x The first number.
y The second number.
Returns
The minumum between the two given numbers.
This method returns the minimum between the two numbers given as parameters.
Definition at line 108 of file utils.cpp.
quicksort() [1/3]
void utils::quicksort (float * list, int ini, int fin)
Quicksort sorting method.
Parameters
list The vector that we want to sort.
ini The first element of the vector.
fin The last element of the vector.
This method sorts the vector using the quicksort method.
Definition at line 157 of file utils.cpp.
References swap().
Referenced by statistics::Similarity::calcCutPoint(), Cleaner::calculateRepresentativeSeq(), Cleaner::cleanByCutValueOverpass(), Cleaner::cleanByCutValueOverpassOrEquals(), Cleaner::cleanCombMethods(), Cleaner::cleanCompareFile(), Cleaner::getCutPointClusters(), statistics::Mold::printAccumulative(), statistics::Similarity::printConservationAcl(), statistics::Consistency::printStatisticsFileAcl(), quicksort(), and trimAlManager::svg_stats_out().
quicksort() [2/3]
void utils::quicksort (int * list, int ini, int fin)
Quicksort sorting method.
Parameters
list The vector that we want to sort.
ini The first element of the vector.
fin The last element of the vector.
This method sorts the vector using the quicksort method.
Definition at line 203 of file utils.cpp.
References quicksort(), and swap().
quicksort() [3/3]
void utils::quicksort (int ** vect, int ini, int fin)
Quicksort sorting method.
Parameters
vect The vector that we want to sort.
ini The first element of the vector.
fin The last element of the vector.
Definition at line 245 of file utils.cpp.
References quicksort(), and swap().
readLine() [1/2]
char * utils::readLine (std::ifstream & file)
Read a new line from current input stream.
This function is better than standard one since cares of operative system compatibility.
It is useful as well because removes tabs and blank spaces at lines at beginning/ending.
.
Parameters
file ifstream to read line from.
Returns
Line that has been read or nullptr if there is nothing to read.
Definition at line 303 of file utils.cpp.
References StartTiming.
readLine() [2/2]
char * utils::readLine (std::istream & file)
Read a new line from current input stream.
This function is better than standard one since cares of operative system compatibility.
It is useful as well because removes tabs and blank spaces at lines at beginning/ending.
.
Parameters
file ifstream to read line from.
Returns
nullptr if there is nothing to read.
Line that has been read.
Definition at line 347 of file utils.cpp.
readNumbers()
int * utils::readNumbers (std::string line)
Reads a line and converts it to an array of number.
Parameters
line Line to convert to array of ints
Returns
Pointer to an array of numbers that contains line
Definition at line 569 of file utils.cpp.
Referenced by trimAlManager::select_cols_argument(), and trimAlManager::seqs_select_argument().
removeCharacter()
std::string utils::removeCharacter (char c, std::string line)
Removes a determined char from the string.
Parameters
c Character to remove from line
line String to remove c from.
Returns
New string without c character
Definition at line 484 of file utils.cpp.
Referenced by Cleaner::calculateRepresentativeSeq(), Alignment::checkCorrespondence(), Cleaner::getCutPointClusters(), and Alignment::getSequences().
removeSpaces()
void utils::removeSpaces (char * in, char * out)
Removing spaces method.
Parameters
in The string that we want to clean.
[out] out The destination of the clean string.
This method removes spaces in the input string and put the result in the output string.
Definition at line 142 of file utils.cpp.
Referenced by statistics::similarityMatrix::loadSimMatrix().
ReplaceString()
std::string utils::ReplaceString (std::string subject, const std::string & search, const std::string & replace)
Function that replaces a substring with another substring in a string. It makes a copy of the original string.
Parameters
[in] subject String to be modified
search Substring to search and change
replace Substring to put in place of search
Definition at line 759 of file utils.cpp.
Referenced by FormatHandling::FormatManager::loadAndSaveMultipleAlignments(), and FormatHandling::FormatManager::saveAlignment().
ReplaceStringInPlace()
void utils::ReplaceStringInPlace (std::string & subject, const std::string & search, const std::string & replace)
Function that replaces a substring with another substring in a string. It does not make a copy of the original string, but modifies it.
Parameters
[in,out] subject String to be modified
search Substring to search and change
replace Substring to put in place of search
Definition at line 749 of file utils.cpp.
Referenced by FormatHandling::FormatManager::loadAndSaveMultipleAlignments(), trimAlManager::menu(), and FormatHandling::FormatManager::saveAlignment().
roundInt()
int utils::roundInt (double number)
Round double to integer method.
Parameters
number The number that will be rounded.
Returns
the rounded number.
This method rounds a double number to a integer.
Definition at line 66 of file utils.cpp.
Referenced by statistics::Gaps::applyWindow(), statistics::Gaps::calcCutPoint(), Cleaner::cleanByCutValueFallBehind(), Cleaner::cleanByCutValueOverpass(), Cleaner::cleanByCutValueOverpassOrEquals(), and Cleaner::cleanStrict().
roundToInf()
int utils::roundToInf (double number)
Round double to inferior integer method.
Parameters
number The number that will be rounded.
Returns
the rounded number.
This method rounds a double number to the inferior integer.
Definition at line 60 of file utils.cpp.
roundToSup()
int utils::roundToSup (double number)
Round double to greater integer method.
Parameters
number The number that will be rounded.
Returns
the rounded number.
This method rounds a double number to the greater integer.
Definition at line 72 of file utils.cpp.
streamSVG()
void utils::streamSVG (float * x, float * y, int num, std::string * lineName, std::string * lineColor, std::string * chartTitle, std::string * filename)
Definition at line 896 of file utils.cpp.
References min().
Referenced by trimAlManager::svg_stats_out().
swap() [1/3]
void utils::swap (float * a, float * b)
Swapping elements method.
Parameters
a One element to swap.
b Other element to swap.
This method swaps the values in a and b.
Definition at line 191 of file utils.cpp.
Referenced by quicksort().
swap() [2/3]
void utils::swap (int * a, int * b)
Swapping elements method.
Parameters
a One element to swap.
b Other element to swap.
This method swaps the values in a and b.
Definition at line 236 of file utils.cpp.
swap() [3/3]
void utils::swap (int ** a, int ** b)
Swaps double pointers.
Parameters
a Double pointer A
b Double pointer B
Definition at line 274 of file utils.cpp.
toUpper()
char utils::toUpper (char c) inline
Definition at line 438 of file utils.h.
Referenced by statistics::Similarity::calculateVectors(), and lookForPattern().
trimLine()
char * utils::trimLine (std::string nline)
Remove all content surrounded by ("") or ([]).
It warns as well when a mismatch for these flags is found.
.
Parameters
nline Line to be trimmed.
Returns
Line trimmed of comments or nullptr if there has been a mismatch
Definition at line 391 of file utils.cpp.
References BracketsMissmatchFound, debug, PossibleMissmatch, and reporting::reportManager::report().