trimAl: source/newmain.cpp File Reference
newmain.cpp File Reference
#include <TimerFactory.h>
#include "../include/trimalArgumentParser.h"
#include "../include/reportsystem.h"
#include <../include/ReadWriteMS/vcf_statish.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References __internalReport::__reportSystem::debug, __internalReport::__reportSystem::IsDebug, trimAlManager::parseArguments(), trimAlManager::perform(), trimAlManager::processArguments(), and StartTiming.