trimAl: /home/vfernandez/git/MyFork/source/reportsystem.cpp File Reference
reportsystem.cpp File Reference
#include "InternalBenchmarker.h"
#include "reportsystem.h"
Variables
reporting::reportManager debug = reporting::reportManager()
Variable Documentation
debug
reporting::reportManager debug = reporting::reportManager() related
Definition at line 33 of file reportsystem.cpp.
Referenced by Alignment::alignmentSummaryHTML(), Alignment::alignmentSummarySVG(), statistics::Gaps::applyWindow(), statistics::Mold::applyWindow(), statistics::Consistency::applyWindow(), statistics::Similarity::applyWindow(), trimAlManager::back_trans_argument(), trimAlManager::block_argument(), trimAlManager::check_absolute_gap_theshold(), trimAlManager::check_automated_manual_incompatibilities(), trimAlManager::check_automated_methods_incompatibilities(), trimAlManager::check_backtranslations(), trimAlManager::check_block_size(), trimAlManager::check_clusters_incompatibilities(), trimAlManager::check_coding_sequences_type(), trimAlManager::check_codon_behaviour_incompatibility(), trimAlManager::check_col_numbering(), trimAlManager::check_combinations_among_thresholds_incompatibility(), trimAlManager::check_compareset_window_argument(), trimAlManager::check_file_aligned(), trimAlManager::check_force_selection(), trimAlManager::check_inFile_incompatibilities(), trimAlManager::check_input_file_with_coding_sequences_argument(), trimAlManager::check_max_identity_incompatibilities(), trimAlManager::check_output_file_with_statistics(), trimAlManager::check_output_relevance(), trimAlManager::check_outputs_coincidence(), trimAlManager::check_residue_and_sequence_overlap(), trimAlManager::check_select_cols_and_seqs_incompatibilities(), trimAlManager::check_similarity_matrix(), trimAlManager::check_stats_incompatibilities(), trimAlManager::check_thresholds_incompatibilities(), trimAlManager::check_vcf_incompatibility(), trimAlManager::check_windows_incompatibilities(), Alignment::checkCorrespondence(), trimAlManager::clean_alignment(), trimAlManager::CleanResiduesNonAuto(), trimAlManager::clusters_argument(), statistics::Consistency::compareAndChoose(), trimAlManager::compareset_argument(), trimAlManager::conservation_threshold_argument(), trimAlManager::consistency_threshold_argument(), trimAlManager::consistency_window_argument(), trimAlManager::create_or_use_similarity_matrix(), Alignment::fillMatrices(), trimAlManager::force_select_argument(), statistics::Consistency::forceComparison(), trimAlManager::gap_threshold_argument(), trimAlManager::gap_window_argument(), statistics::similarityMatrix::getDistance(), FormatHandling::FormatManager::getFormatFromFile(), FormatHandling::FormatManager::getNonEmptyFile(), trimAlManager::in_argument(), FormatHandling::FormatManager::loadAlignment(), main(), trimAlManager::matrix_argument(), trimAlManager::max_identity_argument(), trimAlManager::min_coverage_argument(), trimAlManager::min_quality_argument(), trimAlManager::out_format_arguments(), trimAlManager::output_reports(), trimAlManager::parseArguments(), statistics::Consistency::perform(), trimAlManager::performCompareset(), Alignment::prepareCodingSequence(), Cleaner::removeAllGapsSeqsAndCols(), Cleaner::removeDuplicates(), Cleaner::removeOnlyTerminal(), trimAlManager::residue_overlap_argument(), trimAlManager::save_alignment(), FormatHandling::FormatManager::saveAlignments(), trimAlManager::select_cols_argument(), trimAlManager::seqs_select_argument(), trimAlManager::sequence_overlap_argument(), trimAlManager::similarity_threshold_argument(), trimAlManager::similarity_window_argument(), utils::trimLine(), trimAlManager::verbosity_argument(), and trimAlManager::window_argument().