var searchData=
[
  ['scopedmessage',['ScopedMessage',['../class_catch_1_1_scoped_message.html',1,'Catch']]],
  ['section',['Section',['../class_catch_1_1_section.html',1,'Catch']]],
  ['sectionendinfo',['SectionEndInfo',['../struct_catch_1_1_section_end_info.html',1,'Catch']]],
  ['sectioninfo',['SectionInfo',['../struct_catch_1_1_section_info.html',1,'Catch']]],
  ['sequencesmatrix',['sequencesMatrix',['../classsequences_matrix.html',1,'']]],
  ['serialize_5fstr_5fchar',['serialize_str_char',['../structpicojson_1_1serialize__str__char.html',1,'picojson']]],
  ['similaritymatrix',['similarityMatrix',['../classsimilarity_matrix.html',1,'']]],
  ['sourcelineinfo',['SourceLineInfo',['../struct_catch_1_1_source_line_info.html',1,'Catch']]],
  ['startswithmatcher',['StartsWithMatcher',['../struct_catch_1_1_matchers_1_1_std_string_1_1_starts_with_matcher.html',1,'Catch::Matchers::StdString']]],
  ['statisticsconservation2',['statisticsConservation2',['../classstatistics_conservation2.html',1,'']]],
  ['statisticsgaps',['statisticsGaps',['../classstatistics_gaps.html',1,'']]],
  ['statisticsmanager',['StatisticsManager',['../class_statistics_manager.html',1,'']]],
  ['streamendstop',['StreamEndStop',['../struct_catch_1_1_stream_end_stop.html',1,'Catch']]],
  ['stringmaker',['StringMaker',['../struct_catch_1_1_string_maker.html',1,'Catch']]],
  ['stringmaker_3c_20bool_20_3e',['StringMaker&lt; bool &gt;',['../struct_catch_1_1_string_maker_3_01bool_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20catch_3a_3adetail_3a_3aapprox_20_3e',['StringMaker&lt; Catch::Detail::Approx &gt;',['../struct_catch_1_1_string_maker_3_01_catch_1_1_detail_1_1_approx_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20char_20_2a_20_3e',['StringMaker&lt; char * &gt;',['../struct_catch_1_1_string_maker_3_01char_01_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20char_20_3e',['StringMaker&lt; char &gt;',['../struct_catch_1_1_string_maker_3_01char_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20char_20const_20_2a_20_3e',['StringMaker&lt; char const * &gt;',['../struct_catch_1_1_string_maker_3_01char_01const_01_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20char_5bsz_5d_3e',['StringMaker&lt; char[SZ]&gt;',['../struct_catch_1_1_string_maker_3_01char[_s_z]_4.html',1,'Catch']]],
  ['stringmaker_3c_20double_20_3e',['StringMaker&lt; double &gt;',['../struct_catch_1_1_string_maker_3_01double_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20float_20_3e',['StringMaker&lt; float &gt;',['../struct_catch_1_1_string_maker_3_01float_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20int_20_3e',['StringMaker&lt; int &gt;',['../struct_catch_1_1_string_maker_3_01int_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20long_20_3e',['StringMaker&lt; long &gt;',['../struct_catch_1_1_string_maker_3_01long_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20long_20long_20_3e',['StringMaker&lt; long long &gt;',['../struct_catch_1_1_string_maker_3_01long_01long_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20r_20c_3a_3a_2a_20_3e',['StringMaker&lt; R C::* &gt;',['../struct_catch_1_1_string_maker_3_01_r_01_c_1_1_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20signed_20char_20_3e',['StringMaker&lt; signed char &gt;',['../struct_catch_1_1_string_maker_3_01signed_01char_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20signed_20char_5bsz_5d_3e',['StringMaker&lt; signed char[SZ]&gt;',['../struct_catch_1_1_string_maker_3_01signed_01char[_s_z]_4.html',1,'Catch']]],
  ['stringmaker_3c_20std_3a_3anullptr_5ft_20_3e',['StringMaker&lt; std::nullptr_t &gt;',['../struct_catch_1_1_string_maker_3_01std_1_1nullptr__t_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20std_3a_3astring_20_3e',['StringMaker&lt; std::string &gt;',['../struct_catch_1_1_string_maker_3_01std_1_1string_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20std_3a_3avector_3c_20t_2c_20allocator_20_3e_20_3e',['StringMaker&lt; std::vector&lt; T, Allocator &gt; &gt;',['../struct_catch_1_1_string_maker_3_01std_1_1vector_3_01_t_00_01_allocator_01_4_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20std_3a_3awstring_20_3e',['StringMaker&lt; std::wstring &gt;',['../struct_catch_1_1_string_maker_3_01std_1_1wstring_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20t_20_2a_20_3e',['StringMaker&lt; T * &gt;',['../struct_catch_1_1_string_maker_3_01_t_01_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20char_20_3e',['StringMaker&lt; unsigned char &gt;',['../struct_catch_1_1_string_maker_3_01unsigned_01char_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20char_5bsz_5d_3e',['StringMaker&lt; unsigned char[SZ]&gt;',['../struct_catch_1_1_string_maker_3_01unsigned_01char[_s_z]_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20int_20_3e',['StringMaker&lt; unsigned int &gt;',['../struct_catch_1_1_string_maker_3_01unsigned_01int_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20long_20_3e',['StringMaker&lt; unsigned long &gt;',['../struct_catch_1_1_string_maker_3_01unsigned_01long_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20unsigned_20long_20long_20_3e',['StringMaker&lt; unsigned long long &gt;',['../struct_catch_1_1_string_maker_3_01unsigned_01long_01long_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20wchar_5ft_20_2a_20_3e',['StringMaker&lt; wchar_t * &gt;',['../struct_catch_1_1_string_maker_3_01wchar__t_01_5_01_4.html',1,'Catch']]],
  ['stringmaker_3c_20wchar_5ft_20const_20_2a_20_3e',['StringMaker&lt; wchar_t const * &gt;',['../struct_catch_1_1_string_maker_3_01wchar__t_01const_01_5_01_4.html',1,'Catch']]],
  ['stringmatcherbase',['StringMatcherBase',['../struct_catch_1_1_matchers_1_1_std_string_1_1_string_matcher_base.html',1,'Catch::Matchers::StdString']]],
  ['stringref',['StringRef',['../class_catch_1_1_string_ref.html',1,'Catch']]]
];
