trimAl: similarityMatrix Class Reference
similarityMatrix Class Reference
Class that contains information of similarity matrices.
These are used to calculate the similarity between residues on the same column.
Default matrices for AA, NT and DEG NT are provided, along with method for loading custom matrices.
#include <similarityMatrix.h>
Public Member Functions
similarityMatrix ()
Constructor.
~similarityMatrix ()
Destructor.
bool loadSimMatrix (char *filename)
Method to load a custom matrix.
void defaultAASimMatrix ()
Method to load the default AA similarity matrix.
void defaultNTSimMatrix ()
Method to load the default NT similarity matrix.
void defaultNTDegeneratedSimMatrix ()
Method to load the default DEG NT similarity matrix.
void alternativeSimilarityMatrices (int matrix_code, int datatype)
Method to load alternative similarity matrices also included on the suite. Currently, only one type of alternative matrix is available:
matrix_code: 1 datatype SequenceTypes::AA.
float getDistance (char &A, char &B)
Method to get the similarity distance between two residues, A and B
Characters provided must be both uppercase, please, refer to utils::toUpper.
void printMatrix ()
Method to print the loaded matrix.
Private Member Functions
void memoryAllocation (int nPos)
Method to allocate memory for the similiarity matrix.
void memoryDeletion ()
Method to deallocate memory allocated on the similarityMatrix::memoryAllocation method.
It makes use of the numPositions to effectively remove the memory.
Private Attributes
int * vhash
float ** simMat
float ** distMat
int numPositions
Detailed Description
Class that contains information of similarity matrices.
These are used to calculate the similarity between residues on the same column.
Default matrices for AA, NT and DEG NT are provided, along with method for loading custom matrices.
Definition at line 45 of file similarityMatrix.h.
Constructor & Destructor Documentation
similarityMatrix()
similarityMatrix::similarityMatrix ()
Constructor.
Definition at line 45 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("similarityMatrix::similarityMatrix() ");
     numPositions = 0;
     vhash = nullptr;
     simMat = nullptr;
     distMat = nullptr;
 }
References distMat, numPositions, simMat, StartTiming, and vhash.
~similarityMatrix()
similarityMatrix::~similarityMatrix ()
Destructor.
Definition at line 83 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("similarityMatrix::~similarityMatrix() ");
     if (numPositions != 0) memoryDeletion();
 }
References memoryDeletion(), numPositions, and StartTiming.
Member Function Documentation
alternativeSimilarityMatrices()
void similarityMatrix::alternativeSimilarityMatrices (int matrix_code, int datatype)
Method to load alternative similarity matrices also included on the suite. Currently, only one type of alternative matrix is available:
matrix_code: 1 datatype SequenceTypes::AA.
Parameters
matrix_code ID of the matrix
datatype Numberical representation of the data type. See SequenceTypes
Definition at line 348 of file similarityMatrix.cpp.
                       {
     int i, j, k;
     float sum;
     // Allocate memory depending on the input datatype
     switch (datatype) {
         case SequenceTypes::AA:
             memoryAllocation(20);
             break;
         case SequenceTypes::DNA:
         case SequenceTypes::RNA:
             memoryAllocation(5);
             break;
         case SequenceTypes::DNA | SequenceTypes::DEG:
         case SequenceTypes::RNA | SequenceTypes::DEG:
             memoryAllocation(15);
             break;
     }
     for (i = 0; i < TAMABC; i++)
         vhash[i] = -1;
     // We create the hashing vector taking into account the input datatype
     for (i = 0; i < numPositions; i++) {
         switch (datatype) {
             case SequenceTypes::AA:
                 vhash[listAASym[i] - 'A'] = i;
                 break;
             case SequenceTypes::DNA:
             case SequenceTypes::RNA:
                 vhash[listNTSym[i] - 'A'] = i;
                 break;
             case SequenceTypes::DNA | SequenceTypes::DEG:
             case SequenceTypes::RNA | SequenceTypes::DEG:
                 vhash[listNTDegenerateSym[i] - 'A'] = i;
                 break;
         }
     }
     // Working similarity matrix is set depending on the pre loaded matrices
     for (i = 0; i < numPositions; i++) {
         for (j = 0; j < numPositions; j++) {
             switch (matrix_code) {
                 case 1:
                     simMat[i][j] = alternative_1_NTDegeneratedMatrix[i][j];
                     break;
             }
         }
     }
     // Calculate the distances between residues based on Euclidean distance
     for (j = 0; j < numPositions; j++) {
         for (i = 0; i < numPositions; i++) {
             if ((i != j) && (distMat[i][j] == 0.0)) {
                 for (k = 0, sum = 0; k < numPositions; k++)
                     sum += ((simMat[k][j] - simMat[k][i]) * (simMat[k][j] - simMat[k][i]));
                 sum = (float) sqrt(sum);
                 distMat[i][j] = sum;
                 distMat[j][i] = sum;
             }
         }
     }
 }
References AA, DEG, distMat, DNA, memoryAllocation(), numPositions, RNA, simMat, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
defaultAASimMatrix()
void similarityMatrix::defaultAASimMatrix (void)
Method to load the default AA similarity matrix.
Definition at line 246 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("void similarityMatrix::defaultAASimMatrix(void) ");
     int i, j, k;
     float sum;
     memoryAllocation(20);
     for (i = 0; i < TAMABC; i++)
         vhash[i] = -1;
     // We create the hashing vector
     for (i = 0; i < numPositions; i++)
         vhash[listAASym[i] - 'A'] = i;
     for (i = 0; i < numPositions; i++)
         for (j = 0; j < numPositions; j++)
             simMat[i][j] = defaultAAMatrix[i][j];
     // Calculate the distances between aminoacids
     // based on Euclidean distance
     for (j = 0; j < numPositions; j++) {
         for (i = 0; i < numPositions; i++) {
             if ((i != j) && (distMat[i][j] == 0.0)) {
                 for (k = 0, sum = 0; k < numPositions; k++)
                     sum += ((simMat[k][j] - simMat[k][i]) * (simMat[k][j] - simMat[k][i]));
                 sum = (float) sqrt(sum);
                 distMat[i][j] = sum;
                 distMat[j][i] = sum;
             }
         }
     }
 }
References distMat, memoryAllocation(), numPositions, simMat, StartTiming, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
defaultNTDegeneratedSimMatrix()
void similarityMatrix::defaultNTDegeneratedSimMatrix (void)
Method to load the default DEG NT similarity matrix.
Definition at line 315 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("void similarityMatrix::defaultNTDegeneratedSimMatrix(void) ");
     int i, j, k;
     float sum;
     memoryAllocation(15);
     for (i = 0; i < TAMABC; i++)
         vhash[i] = -1;
     // We create the hashing vector
     for (i = 0; i < numPositions; i++)
         vhash[listNTDegenerateSym[i] - 'A'] = i;
     for (i = 0; i < numPositions; i++)
         for (j = 0; j < numPositions; j++)
             simMat[i][j] = defaultNTDegeneratedMatrix[i][j];
     // Calculate the distances between nucleotides based on Euclidean distance
     for (j = 0; j < numPositions; j++) {
         for (i = 0; i < numPositions; i++) {
             if ((i != j) && (distMat[i][j] == 0.0)) {
                 for (k = 0, sum = 0; k < numPositions; k++)
                     sum += ((simMat[k][j] - simMat[k][i]) * (simMat[k][j] - simMat[k][i]));
                 sum = (float) sqrt(sum);
                 distMat[i][j] = sum;
                 distMat[j][i] = sum;
             }
         }
     }
 }
References distMat, memoryAllocation(), numPositions, simMat, StartTiming, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
defaultNTSimMatrix()
void similarityMatrix::defaultNTSimMatrix (void)
Method to load the default NT similarity matrix.
Definition at line 281 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("void similarityMatrix::defaultNTSimMatrix(void) ");
     int i, j, k;
     float sum;
     memoryAllocation(5);
     for (i = 0; i < TAMABC; i++)
         vhash[i] = -1;
     // We create the hashing vector
     for (i = 0; i < numPositions; i++)
         vhash[listNTSym[i] - 'A'] = i;
     for (i = 0; i < numPositions; i++)
         for (j = 0; j < numPositions; j++)
             simMat[i][j] = defaultNTMatrix[i][j];
     // Calculate the distances between aminoacids
     // based on Euclidean distance
     for (j = 0; j < numPositions; j++) {
         for (i = 0; i < numPositions; i++) {
             if ((i != j) && (distMat[i][j] == 0.0)) {
                 for (k = 0, sum = 0; k < numPositions; k++)
                     sum += ((simMat[k][j] - simMat[k][i]) * (simMat[k][j] - simMat[k][i]));
                 sum = (float) sqrt(sum);
                 distMat[i][j] = sum;
                 distMat[j][i] = sum;
             }
         }
     }
 }
References distMat, memoryAllocation(), numPositions, simMat, StartTiming, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
getDistance()
float similarityMatrix::getDistance (char & A, char & B)
Method to get the similarity distance between two residues, A and B
Characters provided must be both uppercase, please, refer to utils::toUpper.
Parameters
A First residue to compare
B Second residue to compare
Returns
Distance between A and B based on the similarity matrix loaded.
Definition at line 425 of file similarityMatrix.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("float similarityMatrix::getDistance(char a, char b) ");
     int numa = -1, numb = -1;
     // Search the first character position
     if ((a >= 'A') && (a <= 'Z')) numa = vhash[a - 'A'];
     else {
         debug.report(ErrorCode::IncorrectSymbol, new std::string[1]{std::to_string(a)});
         return -1;
     }
     // Search the second character position
     if ((b >= 'A') && (b <= 'Z')) numb = vhash[b - 'A'];
     else {
         debug.report(ErrorCode::IncorrectSymbol, new std::string[1]{std::to_string(b)});
         return -1;
     }
     // We check if the two character positions are valid positions
     if (numa == -1) {
         debug.report(ErrorCode::UndefinedSymbol, new std::string[1]{std::to_string(a)});
         return -1;
     }
     if (numb == -1) {
         debug.report(ErrorCode::UndefinedSymbol, new std::string[1]{std::to_string(b)});
         return -1;
     }
     // Return the distance value between a and b
     return distMat[numa][numb];
 }
References debug, distMat, IncorrectSymbol, reporting::reportManager::report(), StartTiming, UndefinedSymbol, and vhash.
Referenced by statistics::Similarity::calculateVectors().
loadSimMatrix()
bool similarityMatrix::loadSimMatrix (char * filename)
Method to load a custom matrix.
Parameters
filename Path to file containing the matrix to load
Returns
True if loaded
False if an error ocurred
Definition at line 113 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("bool similarityMatrix::loadSimMatrix(char *filename) ");
     char aux[LINE_LENGTH + 1],
         first[LINE_LENGTH],
         listSym[LINE_LENGTH + 1];
     int i, j, k;
     float sum;
     bool firstColumn = true;
     std::ifstream file;
     // We try to open the file, if we can't open the file
     // we return false.
     file.open(filename);
     if (file.fail())
         return false;
     // Read the first line of the file and, depending on the
     // line length (free of spaces an tabulators), we allocate
     // memory for the object structures
     file.getline(aux, LINE_LENGTH);
     utils::removeSpaces(aux, listSym);
     memoryAllocation(strlen(listSym));
     utils::initlVect(vhash, TAMABC, -1);
     // We create the hashing vector
     for (i = 0; i < numPositions; i++) {
         listSym[i] = (char) toupper((int) listSym[i]);
         if ((listSym[i] >= 'A') && (listSym[i] <= 'Z')) {
             if ((vhash[listSym[i] - 'A']) != -1) {
                 memoryDeletion();
                 return false;
             }
             vhash[listSym[i] - 'A'] = i;
         } else {
             memoryDeletion();
             return false;
         }
     }
     for (i = 0; i < numPositions; i++) {
         // Read the first symbol of the line
         j = 0;
         file >> first;
         // If the format includes the first aminoacid in the line
         if (firstColumn) {
             first[0] = (char) toupper((int) first[0]);
             // Format checking. The first token must not be a valid number
             if (((first[0] >= '0' && first[0] <= '9') ||
                  (first[0] == '-' && (first[1] >= '0' && first[1] <= '9')))
                 && i > 0) {
                 memoryDeletion();
                 return false;
             }
             // If in the token is a character, there is "first column"
             // in the format of the alignment
             if ((first[0] >= 'A') && (first[0] <= 'Z')) {
                 firstColumn = true;
                 if ((vhash[first[0] - 'A']) == -1) {
                     memoryDeletion();
                     return false;
                 }
             }
             // If we have read a number there is no "first column"
             // in the format of the alignment
             else if ((first[0] >= '0' && first[0] <= '9') || (first[0] == '-' && (first[1] >= '0' && first[1] <= '9'))) {
                 firstColumn = false;
                 j = 1;
                 simMat[i][0] = atof(first);
                 first[0] = listSym[i];
             }
         } else {
             j = 1;
             // Do some checkings
             if ((first[0] >= 'A') && (first[0] <= 'Z') && (i > 0)) {
                 memoryDeletion();
                 return false;
             }
             simMat[i][0] = atof(first);
             first[0] = listSym[i];
         }
         // Read the corresponding number row
         for (; j < numPositions; j++)
             file >> simMat[vhash[first[0] - 'A']][j];
     }
     // Calculate the average between two simmetric positions
     // respect to the diagonal of the matrix (between [i][j] and [j][i]
     // If the input is a non-symmetric matrix, the output will be a
     // symmetric matrix
     for (i = 0; i < numPositions; i++) {
         for (j = i + 1; j < numPositions; j++) {
             if (simMat[i][j] != simMat[j][i]) {
                 float value = (simMat[i][j] + simMat[j][i]) / 2.0;
                 simMat[i][j] = value;
                 simMat[j][i] = value;
             }
         }
     }
     // Calculate the distances between aminoacids
     // based on Euclidean distance
     for (j = 0; j < numPositions; j++) {
         for (i = 0; i < numPositions; i++) {
             if ((i != j) && (distMat[i][j] == 0.0)) {
                 for (k = 0, sum = 0; k < numPositions; k++)
                     sum += ((simMat[k][j] - simMat[k][i]) * (simMat[k][j] - simMat[k][i]));
                 sum = (float) sqrt(sum);
                 distMat[i][j] = sum;
                 distMat[j][i] = sum;
             }
         }
     }
     file.close();
     return true;
 }
References distMat, utils::initlVect(), LINE_LENGTH, memoryAllocation(), memoryDeletion(), numPositions, utils::removeSpaces(), simMat, StartTiming, TAMABC, and vhash.
Referenced by trimAlManager::create_or_use_similarity_matrix().
memoryAllocation()
void similarityMatrix::memoryAllocation (int nPos) private
Method to allocate memory for the similiarity matrix.
Parameters
nPos Number of different possible residues in the alignment.
This are, on the default matrices:
AA: 20 residues
NT: 5 residues
DEG NT: 15 residues
Definition at line 55 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("void similarityMatrix::memoryAllocation(int nPos) ");
     int i, j;
     // Initialize square table dimension to store the distances
     // and to store the similarity matrix.
     if (numPositions != 0) memoryDeletion();
     numPositions = nPos;
     // Reserve memory for all structures
     vhash = new int[TAMABC];
     simMat = new float *[nPos];
     distMat = new float *[nPos];
     for (i = 0; i < nPos; i++) {
         simMat[i] = new float[nPos];
         distMat[i] = new float[nPos];
         for (j = 0; j < nPos; j++) {
             distMat[i][j] = 0.0;
             simMat[i][j] = 0.0;
         }
     }
 }
References distMat, memoryDeletion(), numPositions, simMat, StartTiming, TAMABC, and vhash.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), and loadSimMatrix().
memoryDeletion()
void similarityMatrix::memoryDeletion () private
Method to deallocate memory allocated on the similarityMatrix::memoryAllocation method.
It makes use of the numPositions to effectively remove the memory.
Definition at line 92 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("void similarityMatrix::memoryDeletion() ");
     int i;
     for (i = 0; i < numPositions; i++) {
         delete[] simMat[i];
         delete[] distMat[i];
     }
     delete[] distMat;
     delete[] simMat;
     delete[] vhash;
     numPositions = 0;
     distMat = nullptr;
     simMat = nullptr;
     vhash = nullptr;
 }
References distMat, numPositions, simMat, StartTiming, and vhash.
Referenced by loadSimMatrix(), memoryAllocation(), and ~similarityMatrix().
printMatrix()
void similarityMatrix::printMatrix (void)
Method to print the loaded matrix.
Definition at line 413 of file similarityMatrix.cpp.
{
      // Create a timer that will report times upon its destruction
      // which means the end of the current scope.
     StartTiming("void similarityMatrix::printMatrix() ");
     for (int i = 0; i < numPositions; i++) {
         for (int j = 0; j < numPositions; j++)
             std::cerr << std::setw(8) << std::setprecision(4) << std::right << simMat[i][j];
         std::cerr << std::endl;
     }
 }
References numPositions, simMat, and StartTiming.
Member Data Documentation
distMat
float** similarityMatrix::distMat private
Definition at line 49 of file similarityMatrix.h.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), getDistance(), loadSimMatrix(), memoryAllocation(), memoryDeletion(), and similarityMatrix().
numPositions
int similarityMatrix::numPositions private
Definition at line 50 of file similarityMatrix.h.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), loadSimMatrix(), memoryAllocation(), memoryDeletion(), printMatrix(), similarityMatrix(), and ~similarityMatrix().
simMat
float** similarityMatrix::simMat private
Definition at line 48 of file similarityMatrix.h.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), loadSimMatrix(), memoryAllocation(), memoryDeletion(), printMatrix(), and similarityMatrix().
vhash
int* similarityMatrix::vhash private
Definition at line 47 of file similarityMatrix.h.
Referenced by alternativeSimilarityMatrices(), defaultAASimMatrix(), defaultNTDegeneratedSimMatrix(), defaultNTSimMatrix(), getDistance(), loadSimMatrix(), memoryAllocation(), memoryDeletion(), and similarityMatrix().
The documentation for this class was generated from the following files:
/home/vfernandez/git/trimAl/include/similarityMatrix.h
/home/vfernandez/git/trimAl/source/similarityMatrix.cpp