trimAl: statistics::Manager Class Reference
statistics::Manager Class Reference
Class to handle the interaction with Alignment and statistics objects.
It serves as a wrapper or intermediate between the alignment and each specific stat.
It also encapsulates the similarityMatrix.
#include <Manager.h>
Public Member Functions
bool setSimilarityMatrix (similarityMatrix *sm)
Method to set a similarity matrix.
bool calculateGapStats ()
Method to handle gap stat calculation
It checks if the gaps submodule has been created, otherwise, creates it.
void printStatisticsGapsColumns ()
Wrapper to Statistics::Gaps::printGapsColumns()
It calls to calculateGapStats() to make sure the information is available before reporting the requested values.
void printStatisticsGapsTotal ()
Wrapper to Statistics::Gaps::printGapsAcl()
It calls to calculateGapStats() to make sure the information is available before reporting the requested values.
bool calculateConservationStats ()
Method to handle similarity stat calculation
It checks if the similarity submodule has been created, otherwise, creates it.
void printStatisticsConservationColumns ()
Wrapper to Statistics::Similarity::printConservationAcl()
It calls to calculateConservationStats() to make sure the information is available before reporting the requested values.
void printStatisticsConservationTotal ()
Wrapper to Statistics::Similarity::printGapsTotal()
It calls to calculateConservationStats() to make sure the information is available before reporting the requested values.
void printCorrespondence ()
Method to print the vector containing the keep/reject (Alignment::saveResidues) values of the associated Alignment
If -1 , the residue would be rejected, otherwise, it prints the position on the alignment of the kept residue.
Public Attributes
Gaps * gaps = nullptr
Gaps submodule.
Similarity * similarity = nullptr
Similarity submodule.
Consistency * consistency = nullptr
Consistency submodule.
similarityMatrix * _similarityMatrix = nullptr
SimilarityMatrix used by Similarity.
int ghWindow
Gap window.
int shWindow
Similarity window.
Private Member Functions
Manager (Alignment *parent)
Manager (Alignment *parent, Manager *mold)
~Manager ()
Private Attributes
Alignment * alig
Friends
class ::Alignment
Detailed Description
Class to handle the interaction with Alignment and statistics objects.
It serves as a wrapper or intermediate between the alignment and each specific stat.
It also encapsulates the similarityMatrix.
Definition at line 28 of file Manager.h.
Constructor & Destructor Documentation
Manager() [1/2]
statistics::Manager::Manager (Alignment * parent) explicit private
Definition at line 153 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("Manager::Manager(Alignment *parent) ");
         alig = parent;
         ghWindow = 0;
         shWindow = 0;
     }
References alig, ghWindow, shWindow, and StartTiming.
Manager() [2/2]
statistics::Manager::Manager (Alignment * parent, Manager * mold) private
Definition at line 163 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("Manager::Manager(Alignment *parent, Manager *mold) ");
         alig = parent;
         _similarityMatrix = mold->_similarityMatrix;
         ghWindow = mold->ghWindow;
         shWindow = mold->shWindow;
         if (mold->similarity)
             similarity = new Similarity(parent, mold->similarity);
         if (mold->consistency)
             consistency = new Consistency(parent, mold->consistency);
         if (mold->gaps)
             gaps = new Gaps(parent, mold->gaps);
     }
References _similarityMatrix, alig, consistency, gaps, ghWindow, shWindow, similarity, and StartTiming.
~Manager()
statistics::Manager::~Manager () private
Definition at line 184 of file Manager.cpp.
                       {
         delete gaps;
         gaps = nullptr;
         delete similarity;
         similarity = nullptr;
         delete consistency;
         consistency = nullptr;
     }
References consistency, gaps, and similarity.
Member Function Documentation
calculateConservationStats()
bool statistics::Manager::calculateConservationStats (void)
Method to handle similarity stat calculation
It checks if the similarity submodule has been created, otherwise, creates it.
Definition at line 13 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("bool Manager::calculateConservationStats(void) ");
         // It the gaps statistics object has not been created
         // we create it
         if (!calculateGapStats())
             return false;
         // It the similarity statistics object has not been
         // created we create it
         if (similarity == nullptr) {
             similarity = new Similarity(alig);
             similarity->setSimilarityMatrix(_similarityMatrix);
             similarity->applyWindow(shWindow);
         }
         // Ask for the similarity matrix
         if (!similarity->isSimMatrixDef())
             return false;
         // Compute the similarity statistics from the input
         // Alignment
         if (!similarity->calculateVectors(true))
             return false;
         // Ask to know if it is necessary to apply any window
         // method. If it's necessary, we apply it
         if (alig->Statistics->similarity->isDefinedWindow())
             return true;
         else
             return alig->Statistics->similarity->applyWindow(shWindow);
     }
References _similarityMatrix, alig, statistics::Similarity::applyWindow(), calculateGapStats(), statistics::Similarity::calculateVectors(), statistics::Similarity::isDefinedWindow(), statistics::Similarity::isSimMatrixDef(), statistics::Similarity::setSimilarityMatrix(), shWindow, similarity, StartTiming, and Alignment::Statistics.
Referenced by Cleaner::clean(), Cleaner::cleanCombMethods(), Cleaner::cleanConservation(), printStatisticsConservationColumns(), printStatisticsConservationTotal(), and trimAlManager::svg_stats_out().
calculateGapStats()
bool statistics::Manager::calculateGapStats ()
Method to handle gap stat calculation
It checks if the gaps submodule has been created, otherwise, creates it.
Definition at line 135 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("bool Manager::calculateGapStats(void) ");
         // If Alignment matrix is not created, return false
         if (alig->sequences == nullptr)
             return false;
         // If sgaps object is not created, we create them
         // and calculate the statistics
         if (gaps == nullptr) {
             gaps = new Gaps(alig);
         }
         gaps->CalculateVectors();
         return gaps->applyWindow(ghWindow);
     }
References alig, statistics::Gaps::applyWindow(), statistics::Gaps::CalculateVectors(), gaps, ghWindow, Alignment::sequences, and StartTiming.
Referenced by calculateConservationStats(), statistics::Similarity::calculateVectors(), Cleaner::clean(), Cleaner::clean2ndSlope(), Cleaner::cleanGaps(), Cleaner::cleanNoAllGaps(), printStatisticsGapsColumns(), printStatisticsGapsTotal(), Cleaner::removeOnlyTerminal(), and trimAlManager::svg_stats_out().
printCorrespondence()
void statistics::Manager::printCorrespondence (void)
Method to print the vector containing the keep/reject (Alignment::saveResidues) values of the associated Alignment
If -1 , the residue would be rejected, otherwise, it prints the position on the alignment of the kept residue.
Definition at line 121 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("void Manager::printCorrespondence(void) ");
         int i;
         std::cout << "#ColumnsMap\t";
         // Print the saveResidues relathionship
         for (i = 0; i < alig->originalNumberOfResidues - 1; i++)
             std::cout << alig->saveResidues[i] << ", ";
         std::cout << alig->saveResidues[i] << std::endl;
     }
References alig, Alignment::originalNumberOfResidues, Alignment::saveResidues, and StartTiming.
Referenced by trimAlManager::perform().
printStatisticsConservationColumns()
void statistics::Manager::printStatisticsConservationColumns (void)
Wrapper to Statistics::Similarity::printConservationAcl()
It calls to calculateConservationStats() to make sure the information is available before reporting the requested values.
Definition at line 50 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("void Manager::printStatisticsConservationColumns(void) ");
         // Check if the similarity statistics object has been
         // created */
         if (calculateConservationStats())
             /* then prints the information */
             alig->Statistics->similarity->printConservationColumns();
     }
References alig, calculateConservationStats(), statistics::Similarity::printConservationColumns(), similarity, StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::print_statistics().
printStatisticsConservationTotal()
void statistics::Manager::printStatisticsConservationTotal (void)
Wrapper to Statistics::Similarity::printGapsTotal()
It calls to calculateConservationStats() to make sure the information is available before reporting the requested values.
Definition at line 63 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("void Manager::printStatisticsConservationTotal(void) ");
         // Check if the similarity statistics object has been
         // created
         if (calculateConservationStats())
             // then prints the information
             alig->Statistics->similarity->printConservationAcl();
     }
References alig, calculateConservationStats(), statistics::Similarity::printConservationAcl(), similarity, StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::print_statistics().
printStatisticsGapsColumns()
void statistics::Manager::printStatisticsGapsColumns (void)
Wrapper to Statistics::Gaps::printGapsColumns()
It calls to calculateGapStats() to make sure the information is available before reporting the requested values.
Definition at line 95 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("void Manager::printStatisticsGapsColumns(void) ");
         // Check if there is computed the gaps statistics
         if (calculateGapStats())
             // then prints the information
             alig->Statistics->gaps->printGapsColumns();
     }
References alig, calculateGapStats(), gaps, statistics::Gaps::printGapsColumns(), StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::print_statistics().
printStatisticsGapsTotal()
void statistics::Manager::printStatisticsGapsTotal (void)
Wrapper to Statistics::Gaps::printGapsAcl()
It calls to calculateGapStats() to make sure the information is available before reporting the requested values.
Definition at line 108 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("void Manager::printStatisticsGapsTotal(void) ");
         // Check it there is computed the gaps statistics
         if (calculateGapStats())
             // then prints the information
             alig->Statistics->gaps->printGapsAcl();
     }
References alig, calculateGapStats(), gaps, statistics::Gaps::printGapsAcl(), StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::print_statistics().
setSimilarityMatrix()
bool statistics::Manager::setSimilarityMatrix (similarityMatrix * sm)
Method to set a similarity matrix.
Definition at line 77 of file Manager.cpp.
{
         // Create a timerLevel that will report times upon its destruction
         //  which means the end of the current scope.
         StartTiming("bool Manager::setSimilarityMatrix(similarityMatrix *sm) ");
         _similarityMatrix = sm;
         // If scons object is not created, we create them
         if (alig->Statistics->similarity == nullptr)
             alig->Statistics->similarity = new Similarity(alig);
         // Associate the matrix to the similarity statistics object
         // If it's OK, we return true
         return alig->Statistics->similarity->setSimilarityMatrix(sm);
     }
References _similarityMatrix, alig, statistics::Similarity::setSimilarityMatrix(), similarity, StartTiming, and Alignment::Statistics.
Referenced by trimAlManager::create_or_use_similarity_matrix().
Friends And Related Function Documentation
::Alignment
friend class ::Alignment friend
Making Alignment a friend class allows us to have private constructor and destructors.
This gives us more control over the statistics classes, hinting that they shouldn't be created outside the scope of a newAlignmet.
Definition at line 108 of file Manager.h.
Member Data Documentation
_similarityMatrix
similarityMatrix* statistics::Manager::_similarityMatrix = nullptr
SimilarityMatrix used by Similarity.
Definition at line 47 of file Manager.h.
Referenced by calculateConservationStats(), Manager(), and setSimilarityMatrix().
alig
Alignment* statistics::Manager::alig private
Definition at line 110 of file Manager.h.
Referenced by calculateConservationStats(), calculateGapStats(), Manager(), printCorrespondence(), printStatisticsConservationColumns(), printStatisticsConservationTotal(), printStatisticsGapsColumns(), printStatisticsGapsTotal(), and setSimilarityMatrix().
consistency
Consistency* statistics::Manager::consistency = nullptr
Consistency submodule.
Definition at line 42 of file Manager.h.
Referenced by Alignment::alignmentSummaryHTML(), Alignment::alignmentSummarySVG(), trimAlManager::CleanResiduesNonAuto(), Manager(), statistics::Consistency::perform(), trimAlManager::print_statistics(), and ~Manager().
gaps
Gaps* statistics::Manager::gaps = nullptr
Gaps submodule.
Definition at line 34 of file Manager.h.
Referenced by Alignment::alignmentSummaryHTML(), Alignment::alignmentSummarySVG(), calculateGapStats(), statistics::Similarity::calculateVectors(), Cleaner::clean(), Cleaner::clean2ndSlope(), Cleaner::cleanCombMethods(), Cleaner::cleanGaps(), Cleaner::cleanNoAllGaps(), trimAlManager::CleanSequences(), Manager(), printStatisticsGapsColumns(), printStatisticsGapsTotal(), Cleaner::removeOnlyTerminal(), trimAlManager::svg_stats_out(), and ~Manager().
ghWindow
int statistics::Manager::ghWindow
Gap window.
Definition at line 52 of file Manager.h.
Referenced by calculateGapStats(), Manager(), and Alignment::setWindowsSize().
shWindow
int statistics::Manager::shWindow
Similarity window.
Definition at line 56 of file Manager.h.
Referenced by calculateConservationStats(), Manager(), and Alignment::setWindowsSize().
similarity
Similarity* statistics::Manager::similarity = nullptr
Similarity submodule.
Definition at line 38 of file Manager.h.
Referenced by Alignment::alignmentSummaryHTML(), Alignment::alignmentSummarySVG(), calculateConservationStats(), Cleaner::clean(), Cleaner::cleanCombMethods(), Cleaner::cleanConservation(), trimAlManager::CleanSequences(), Manager(), printStatisticsConservationColumns(), printStatisticsConservationTotal(), setSimilarityMatrix(), trimAlManager::svg_stats_out(), and ~Manager().
The documentation for this class was generated from the following files:
/home/vfernandez/git/trimAl/include/Statistics/Manager.h
/home/vfernandez/git/trimAl/source/Statistics/Manager.cpp