trimAl: trimAlManager Class Reference
trimAlManager Class Reference
Main class of trimAl.
It is strutured to work with 3 calls:
#include <trimalManager.h>
Public Member Functions
trimAlManager ()
~trimAlManager ()
int perform ()
Method to perform the analysis if all checks have passed.
void delete_variables ()
Method to delete all variables that need to be deallocated.
Public Attributes
std::vector< std::string > * vcfs = nullptr
bool appearErrors = false
Flag to trace errors.
bool getComplementary = false
Flag to return the complementary alignment.
bool columnNumbering = false
Flag to return column numbering in report.
bool nogaps = false
Flag to use the nogaps option.
bool noallgaps = false
Flag to use the noallgaps option.
bool gappyout = false
Flag to use the gappyout trimming method.
bool strict = false
Flag to use the strict trimming method.
bool strictplus = false
Flag to use the strictplus trimming method.
bool automated1 = false
Flag to use the automated1 trimming method.
bool sgc = false
Flag to show the Gaps Scores per column.
bool sgt = false
Flag to show the Accumulated Gaps Scores.
bool ssc = false
Flag to show the Similarity Scores per column.
bool sst = false
Flag to show the Accumulated Similarity Scores.
bool sfc = false
Flag to show the Sum of Pairs scores per column.
bool sft = false
Flag to show the Accumulated Sum of Pairs.
bool sident = false
Flag to show identity scores in the alignment.
bool soverlap = false
Flag to show overlap scores in the alignment.
bool selectSeqs = false
Flag to select sequences manually from the alignment.
bool selectCols = false
Flag to select columns manually from the alignment.
bool splitByStopCodon = false
Flag to use the SplitByCodonStop option.
bool terminalOnly = false
Flag to use the Terminal Only option.
bool keepSeqs = false
Flag to keep sequences in the alignment.
bool ignoreStopCodon = false
Flag to use the Ignore Stop Codon option.
float conservationThreshold = -1
Similarity Threshold to use while trimming.
float gapThreshold = -1
Gap Threshold to use while trimming.
float similarityThreshold = -1
Similarity Threshold to use while trimming.
float consistencyThreshold = -1
Consistency Threshold to use while trimming.
float residuesOverlap = -1
Residues Overlap to use while trimming.
float sequenceOverlap = -1
Sequence Overlap to use while trimming.
float maxIdentity = -1
Max Identity to use while trimming.
int i = 1
Argument Iterator Variable.
int stats = 0
Stats Flag to use in reporting. For each stat requested, this flag is decreased by one.
int windowSize = -1
Window Size to use while trimming.
int gapWindow = -1
Gap Window Size to use while trimming.
int similarityWindow = -1
Similarity Window to use while trimming.
int consistencyWindow = -1
Consistency Window to use while trimming.
int blockSize = -1
Block Size to use while trimming.
int clusters = -1
Number of most representative sequences we are going to use.
int automatedMethodCount = -1
Integer counter of the automatic methods.
If the counter is bigger than 0, we are using an automatic method.
If the counter is bigger than 1, we are trying to use multiple automatic methods.
int alternative_matrix = -1
Int that represents which alternative matrix to use, where '-1' means no alternative matrix, and '1' means degenerated_nt_identity.
int * delColumns = nullptr
Vector that contains the column indexes the user specified to be removed.
int * delSequences = nullptr
Vector that contains the sequence indexes the user specified to be removed.
int * sequencesLengths = nullptr
Vector that contains the sequences lengths of each sequence in the backtranslation option.
size_t argumentLength = size_t(-1)
Temp variable to use when there is a need to copy an argument to a char array.
std::string * sequencesNames = nullptr
Temporal variable to use in backtranslation option to compare with infile.
std::ifstream compare
Temporal variable to open files in trimAlManager::check_multiple_files_comparison function.
similarityMatrix * similMatrix = nullptr
Temporal Similarity Matrix.
Alignment * origAlig = nullptr
Main alignment used/loaded on trimAl in combination with singleAlig.
Alignment * singleAlig = nullptr
Alignment obtained by making modifications to singleAlig or backtranslationAlig.
Alignment * tempAlig = nullptr
Temporal alignment that allows us to make some changes to trimAlManager::singleAlig, destroy it and set trimAlManager::singleAlig to this.
Alignment * backtranslationAlig = nullptr
Alignment used on the backtranslation functionality.
Alignment ** compareAlignmentsArray = nullptr
Alignment Vector used on trimAlManager::check_multiple_files_comparison to compare them.
char c
Temporal char variable.
char * forceFile = nullptr
Forcefile to use in combination with multiple files comparison, to compare them against this.
char * infile = nullptr
File to load the alignment when only one alignment has trimming interest.
char * backtransFile = nullptr
File to load the alignment containing the backtranslation information.
char * outfile = nullptr
File to output the trimmed alignment. This can contain tags which will be traduced to some variables:
[in] will be changed with the original filename.
[format] will be changed with the output format name specified.
[extension] will be changed to the correct format extension.
char * htmlOutFile = nullptr
File to output the html report.
char * svgOutFile = nullptr
File to output the svg report.
char * svgStatsOutFile = nullptr
File to output the svg graph showing the stats along the alignment.
char * compareset = nullptr
Pointer to the argument that contains the compareset file.
char * matrixFile = nullptr
File that contains a user defined similarity matrix.
char ** filesToCompare = nullptr
Vector containing the files to compare in trimAlManager::check_multiple_files_comparison function.
char line [256]
Temporal variable to read lines from a file.
std::vector< std::string > oformats
Formats names we are going to output our trimmed alignment.
statistics::Consistency * CS = nullptr
Private Member Functions
void output_reports ()
void save_alignment ()
int perform_VCF ()
void svg_stats_out ()
void print_statistics ()
Method to print statistics requested.
bool create_or_use_similarity_matrix ()
Method to create, load and use a similarity matrix, depending on alignment residue nature, if the user gave a specific similarity matrix, etc.
void clean_alignment ()
Core Method of the program. This is where almost all cleaning methods are called from.
void postprocess_alignment ()
void set_window_size ()
Method to set correct window sizes depending on values for them given by the user.
void menu ()
Method to show the menu of the program.
void examples ()
Method to show the examples information about the program.
void CleanSequences ()
Method to trim or reduce the number of sequences in an alignment. It performs one or none of the following methods:
void CleanResiduesAuto ()
Method to trim the alignment using automatic or semi-automatic methods:
void CleanResiduesNonAuto ()
Method to trim the alignment using non automatic methods:
Private Attributes
FormatManager formatManager
Read Write Machine that allows to manage formats easily.
Argument Parsing methods
Parameters
[in] argc Number of arguments in argv
[in] *argv[] Arguments passed to the program
[in,out] *currentArg Current argument being evaluated.
It is passed as a pointer to allow methods to consume several argc
Returns
True if current argument (*currentArg) corresponds to the argument being checked.
False otherwise.
Access Level
All methods are inline-private except parseArguments(int argc, char *argv[])
Special Cases:
parseArguments(int argc, char *argv[])
Is the only public method in the group.
Calls the rest of methods in the group.
help_arguments(const int* argc, char* argv[], int* currentArg)
Is the only private method that doesn't accept *currentArg.
This is due it iterates over all values of argv before checking the rest of arguments.
void parseArguments (int argc, char *argv[])
Method to parse arguments into usable structure in trimal.
void verbosity_argument (const int *argc, char *argv[])
Method to parse the verbosity argument.
This check is done before any other check.
This is due to trimAl not performing any action if any help argument has been provided.
.
void help_arguments (const int *argc, char *argv[], int *currentArg)
Method to parse information arguments as help and menu.
bool in_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the input file argument.
bool vcf_argument (const int *argc, char *argv[], int *currentArg)
Method to parse vcf argument.
bool out_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the output file pattern.
bool html_out_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the html output file.
bool timetracker_out_argument (const int *argc, char *argv[], int *currentArg)
Method to parse InternalBenchmarker output argument.
Need to be checked before any other argument.
bool svg_out_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the svg output file.
bool svg_stats_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the svg stats output file.
bool out_format_arguments (const int *argc, char *argv[], int *currentArg)
Method to parse the output formats as -fasta -clustal or -formats [...].
bool matrix_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the custom matrix argument.
bool compareset_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the comparset argument.
bool force_select_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the force select argument.
bool back_trans_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the backtranslation argument.
bool gap_threshold_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the gap threshold argument.
bool similarity_threshold_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the similarity threshold argument.
bool consistency_threshold_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the consistency threshold argument.
bool conservation_threshold_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the similarity threshold argument.
bool select_cols_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the select columns argument.
bool no_gaps_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the nogaps argument.
bool no_all_gaps_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the noallgaps argument.
bool keep_seqs_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the keepSeqs argument.
bool keep_header_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the keepHeader argument.
bool gappy_out_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the gappyout argument.
bool strict_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the strict argument.
bool strict_plus_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the strictplus argument.
bool automated1_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the automated1 argument.
bool residue_overlap_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the residue overlap argument.
bool sequence_overlap_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the sequence overlap argument.
bool seqs_select_argument (const int *argc, char *argv[], int *currentArg)
Method to parse que select sequences argument.
bool max_identity_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the max identity argument.
bool clusters_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the clusters argument.
bool terminal_only_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the terminal only argument.
bool window_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the Window argument.
bool gap_window_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the Gap Window argument.
bool similarity_window_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the Similarity Window argument.
bool consistency_window_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the Consistency Window argument.
bool block_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the Block Size argument.
bool stats_arguments (const int *argc, char *argv[], int *currentArg)
Method to parse stats arguments.
bool complementary_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the complementary argument.
bool col_numbering_argument (const int *argc, char *argv[], int *currentArg)
Method to parse the column numbering argument.
bool split_by_stop_codon_argument (const int *argc, char *argv[], int *currentArg)
Method to parse split by stop codon argument.
bool ignore_stop_codon_argument (const int *argc, char *argv[], int *currentArg)
Method to parse ignore by stop codon argument.
Process Arguments Methods
bool processArguments (char *argv[])
Method to process the information obtained by trimAlManager::parseArguments
It checks for argument incompatibilities and arguments dependencies.
bool check_arguments_incompatibilities ()
Method to check argument incompatibilities.
Take in mind that an incompatibility is between two arguments, but only one method will check this incompatibility. If you are searching for the method that checks incompatibility between X and Y, this check may be done on check_X_incompatibilities or check_Y_incompatibilities.
bool check_inFile_incompatibilities ()
Method to check the inFile argument incompatibilities.
bool check_select_cols_and_seqs_incompatibilities ()
Method to check incompatibilities with select cols and select seqs arguments.
bool check_thresholds_incompatibilities ()
Method to check incompatibilities with manual thresholds.
bool check_automated_methods_incompatibilities ()
Method to check incompatibilities related to automated trimming methods.
bool check_max_identity_incompatibilities ()
Method to check max identity incompatibilities.
bool check_clusters_incompatibilities ()
Method to check clusters incompatibilities.
bool check_windows_incompatibilities ()
Method to check windows incompatibilities.
bool check_stats_incompatibilities ()
Method to check statistics incompatibilities.
bool check_codon_behaviour_incompatibility ()
Method to check incompatibilities related to how the algorithm should treat stop codons.
bool check_combinations_among_thresholds_incompatibility ()
As some thresholds are incompatible between them, we check their incompatibilities.
bool check_automated_manual_incompatibilities ()
Check if only one method, either automatic or manual has been asked.
bool check_arguments_needs (char *argv[])
Method that checks dependencies between arguments.
Take in mind that dependencies may be between multiple arguments, so, if there is a dependency between arguments X, Y and Z, this dependency check may be on check_X, check_Y or check_Z.
At the same time, is possible to find a function that checks this dependency specifically: check_X_with_Y_and_Z.
bool check_force_selection ()
Method to check dependency of force select argument.
bool check_input_file_with_coding_sequences_argument ()
Method to check dependency between custom coding sequence file and infile arguments.
bool check_file_aligned ()
Method to check if an alignment needs to be aligned depending on the methods that have been asked to perform and, if so, checks if alignment is aligned.
bool check_similarity_matrix ()
Method to check if given a similarity matrix, there is a need to use it.
bool check_outputs_coincidence ()
Method to check if both output patterns (alignment output and html report output) are the same, which would mean one of them would overwrite the other.
bool check_col_numbering ()
Method to check if column numbering makes sense based on the functionality asked.
bool check_residue_and_sequence_overlap ()
Method to check if both of them (residue overlap and sequence overlap) have been defined by the user as they have a dependency on each other.
bool check_output_relevance ()
Method to check if, being asked to give an HTML report, it makes logic, depending on the functionality asked.
bool check_output_file_with_statistics ()
Method to check if there is an output file to allow statistics to be given on terminal.
bool check_block_size ()
Method to check if the block size is bigger than allowed depending on size of alignment.
bool check_backtranslations ()
Method to check backtranslation needs.
bool check_coding_sequences_type ()
Method to check the type of sequences present in the backtranslationAlig.
bool check_and_prepare_coding_sequence ()
Method to check and prepare the coding sequence.
bool check_backtranslation_infile_names_correspondence ()
Method to check if the origAlig and backtranslationAlig are compatible in names to make the backtranslation behaviour.
void check_compareset_window_argument ()
Method to check and warn if windowsize and compareset has been given.
void check_output_format ()
Method to check if an output format has been given. If no output format has been given, it will use the inFile format.
bool performCompareset ()
Method to check if multiple files comparison has been set correctly.
It also perform some calculations needed on comparfiles behaviour.
Detailed Description
Main class of trimAl.
It is strutured to work with 3 calls:
trimAlManager::parseArguments(int argc, char *argv[]) :
To parse the arguments passed to the program.
trimAlManager::processArguments(char* argv[]) :
To check if every argument passed in compatible with the rest, and also, if it has all it's dependencies fulfilled.
trimAlManager::perform() :
To perform the logic requested by passed arguments.
See main
Definition at line 28 of file trimalManager.h.
Constructor & Destructor Documentation
trimAlManager()
trimAlManager::trimAlManager ()
Definition at line 20 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("trimAlManager::trimAlManager() ");
 }
References StartTiming.
~trimAlManager()
trimAlManager::~trimAlManager ()
Definition at line 26 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("trimAlManager::~trimAlManager() ");
     delete_variables();
 }
References delete_variables(), and StartTiming.
Member Function Documentation
automated1_argument()
bool trimAlManager::automated1_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the automated1 argument.
Definition at line 540 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-automated1")) && (!automated1)) {
         automated1 = true;
         return true;
     }
     return false;
 }
References automated1, and i.
Referenced by parseArguments().
back_trans_argument()
bool trimAlManager::back_trans_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the backtranslation argument.
Definition at line 382 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-backtrans") && ((*i) + 1 != *argc) && (backtransFile == nullptr)) {
         argumentLength = strlen(argv[++*i]);
         backtransFile = new char[argumentLength + 1];
         strcpy(backtransFile, argv[*i]);
         if ((backtranslationAlig = formatManager.loadAlignment(backtransFile)) == nullptr) {
             debug.report(ErrorCode::AlignmentNotLoaded, backtransFile);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References AlignmentNotLoaded, appearErrors, argumentLength, backtransFile, backtranslationAlig, debug, formatManager, i, FormatManager::loadAlignment(), and reporting::reportManager::report().
Referenced by parseArguments().
block_argument()
bool trimAlManager::block_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the Block Size argument.
Definition at line 708 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-block") && ((*i) + 1 != *argc) && (blockSize == -1)) {
         if (utils::isNumber(argv[*i + 1])) {
             blockSize = atoi(argv[++*i]);
             if (blockSize <= 0) {
                 debug.report(ErrorCode::BlockSizeOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::BlockSizeNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, blockSize, BlockSizeNotRecognized, BlockSizeOutOfRange, debug, i, utils::isNumber(), and reporting::reportManager::report().
Referenced by parseArguments().
check_and_prepare_coding_sequence()
bool trimAlManager::check_and_prepare_coding_sequence () inline private
Method to check and prepare the coding sequence.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1263 of file trimalManager.cpp.
{
     if ((!appearErrors) &&
         // If we are going to do a back translation
             (backtransFile != nullptr) &&
         // Perform it and save if it has errored.
             (!backtranslationAlig->prepareCodingSequence(
                 splitByStopCodon,
                 ignoreStopCodon,
                 origAlig)
             )
         )
     {
         // Error reporting is made by prepareCodingSequence function.
         appearErrors = true;
         return true;
     }
     return false;
 }
References appearErrors, backtransFile, backtranslationAlig, ignoreStopCodon, origAlig, Alignment::prepareCodingSequence(), and splitByStopCodon.
Referenced by check_arguments_needs().
check_arguments_incompatibilities()
bool trimAlManager::check_arguments_incompatibilities () inline private
Method to check argument incompatibilities.
Take in mind that an incompatibility is between two arguments, but only one method will check this incompatibility. If you are searching for the method that checks incompatibility between X and Y, this check may be done on check_X_incompatibilities or check_Y_incompatibilities.
Returns
True if all incompatibilities checks have passed.
False otherwise
Definition at line 144 of file trimalManager.cpp.
{
     // The incompatibilities are checked only once,
     // so there are arguments with no function to check it's incompatibilities although they have.
     // These are checked within other functions.
     // So if argument A is incompatible with B,
     // A may have this checked in it's incompatibilities function,
     // but B may have no function to check them.
     check_inFile_incompatibilities();
     check_select_cols_and_seqs_incompatibilities();
     check_thresholds_incompatibilities();
     check_automated_methods_incompatibilities();
     check_max_identity_incompatibilities();
     check_clusters_incompatibilities();
     check_windows_incompatibilities();
     check_stats_incompatibilities();
     check_codon_behaviour_incompatibility();
     check_combinations_among_thresholds_incompatibility();
     return appearErrors;
 }
References appearErrors, check_automated_methods_incompatibilities(), check_clusters_incompatibilities(), check_codon_behaviour_incompatibility(), check_combinations_among_thresholds_incompatibility(), check_inFile_incompatibilities(), check_max_identity_incompatibilities(), check_select_cols_and_seqs_incompatibilities(), check_stats_incompatibilities(), check_thresholds_incompatibilities(), and check_windows_incompatibilities().
Referenced by processArguments().
check_arguments_needs()
bool trimAlManager::check_arguments_needs (char * argv[]) inline private
Method that checks dependencies between arguments.
Take in mind that dependencies may be between multiple arguments, so, if there is a dependency between arguments X, Y and Z, this dependency check may be on check_X, check_Y or check_Z.
At the same time, is possible to find a function that checks this dependency specifically: check_X_with_Y_and_Z.
Parameters
argv Arguments passed to the program
Returns
False if dependencies check has passed
True otherwise
Definition at line 943 of file trimalManager.cpp.
{
     check_force_selection();
     check_input_file_with_coding_sequences_argument();
     check_file_aligned();
     check_similarity_matrix();
     check_outputs_coincidence();
     check_col_numbering();
     check_residue_and_sequence_overlap();
     check_output_relevance();
     check_output_file_with_statistics();
     check_automated_manual_incompatibilities();
     check_block_size();
     check_backtranslations();
     check_coding_sequences_type();
     check_and_prepare_coding_sequence();
     check_backtranslation_infile_names_correspondence();
     check_compareset_window_argument();
     check_output_format();
     return appearErrors;
 }
References appearErrors, check_and_prepare_coding_sequence(), check_automated_manual_incompatibilities(), check_backtranslation_infile_names_correspondence(), check_backtranslations(), check_block_size(), check_coding_sequences_type(), check_col_numbering(), check_compareset_window_argument(), check_file_aligned(), check_force_selection(), check_input_file_with_coding_sequences_argument(), check_output_file_with_statistics(), check_output_format(), check_output_relevance(), check_outputs_coincidence(), check_residue_and_sequence_overlap(), and check_similarity_matrix().
Referenced by processArguments().
check_automated_manual_incompatibilities()
bool trimAlManager::check_automated_manual_incompatibilities () inline private
Check if only one method, either automatic or manual has been asked.
Returns
False if dependencies check has passed
True otherwise
Definition at line 988 of file trimalManager.cpp.
{
     if ((getComplementary) && (!appearErrors))
         if (!automatedMethodCount && // Are we not using an automated method?
             (gapThreshold == -1) && (conservationThreshold == -1) && (similarityThreshold == -1) && // Neither a threshold method.
             (!selectCols) && (!selectSeqs) && (residuesOverlap == -1) && (sequenceOverlap == -1) && // Neither a sequence and residues semimanual selection methods
             (maxIdentity == -1) && (clusters == -1)) // Or complex selection of sequences.
         {
             debug.report(ErrorCode::TrimmingMethodNeeded, new std::string[1]{"-complementary"});
             appearErrors = true;
             return true;
         }
     if ((terminalOnly) && (!appearErrors))
         if (!automatedMethodCount && // Are we not using an automated method?
             (gapThreshold == -1) && (conservationThreshold == -1) && (similarityThreshold == -1) && // Neither a threshold method.
             (!selectCols) && (!selectSeqs) && (residuesOverlap == -1) && (sequenceOverlap == -1) && // Neither a sequence and residues semimanual selection methods
             (maxIdentity == -1) && (clusters == -1)) // Or complex selection of sequences.
         {
             debug.report(ErrorCode::TrimmingMethodNeeded, new std::string[1]{"-terminalonly"});
             appearErrors = true;
             return true;
         }
     return false;
 }
References appearErrors, automatedMethodCount, clusters, conservationThreshold, debug, gapThreshold, getComplementary, maxIdentity, reporting::reportManager::report(), residuesOverlap, selectCols, selectSeqs, sequenceOverlap, similarityThreshold, terminalOnly, and TrimmingMethodNeeded.
Referenced by check_arguments_needs().
check_automated_methods_incompatibilities()
bool trimAlManager::check_automated_methods_incompatibilities () inline private
Method to check incompatibilities related to automated trimming methods.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 884 of file trimalManager.cpp.
{
     if (automatedMethodCount) {
         if ((windowSize != -1) || (gapWindow != -1) || (similarityWindow != -1)) {
             debug.report(ErrorCode::CombinationAmongTrimmingMethods);
             appearErrors = true;
         }
         if (automatedMethodCount > 1) {
             debug.report(ErrorCode::CombinationAmongTrimmingMethods);
             appearErrors = true;
         }
     }
     return appearErrors;
 }
References appearErrors, automatedMethodCount, CombinationAmongTrimmingMethods, debug, gapWindow, reporting::reportManager::report(), similarityWindow, and windowSize.
Referenced by check_arguments_incompatibilities().
check_backtranslation_infile_names_correspondence()
bool trimAlManager::check_backtranslation_infile_names_correspondence () inline private
Method to check if the origAlig and backtranslationAlig are compatible in names to make the backtranslation behaviour.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1282 of file trimalManager.cpp.
{
     //NOTE Maybe we don't need to copy the names and lengths to two new arrays
     // as we could pass the original names and lengths to the check checkCorrespondence function,
     // which doesn't modify the pointers passed to them
     if ((!appearErrors) && (backtransFile != nullptr)) {
         sequencesNames = new std::string[backtranslationAlig->getNumSpecies()];
         sequencesLengths = new int[backtranslationAlig->getNumSpecies()];
         backtranslationAlig->getSequences(sequencesNames, sequencesLengths);
         if (!origAlig->checkCorrespondence(
                 sequencesNames,
                 sequencesLengths,
                 backtranslationAlig->getNumSpecies(),
                 3
         )) {
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, backtransFile, backtranslationAlig, Alignment::checkCorrespondence(), Alignment::getNumSpecies(), Alignment::getSequences(), origAlig, sequencesLengths, and sequencesNames.
Referenced by check_arguments_needs().
check_backtranslations()
bool trimAlManager::check_backtranslations () inline private
Method to check backtranslation needs.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1217 of file trimalManager.cpp.
{
     if (!appearErrors) {
         if (backtransFile == nullptr) {
             // Crossed dependency between Backtranslation and SplitByCodon
             if (splitByStopCodon) {
                 debug.report(ErrorCode::ParemeterOnlyOnBacktranslation, new std::string[1]{"-splitbystopcodon"});
                 appearErrors = true;
                 return true;
             }
             // Crossed dependency between Backtranslation and IgnoreStopCodon
             if (ignoreStopCodon) {
                 debug.report(ErrorCode::ParemeterOnlyOnBacktranslation, new std::string[1]{"-ignorestopcodon"});
                 appearErrors = true;
                 return true;
             }
         }
         // If doing backtranslation, we need the input file to be aligned.
         else if (!origAlig->isFileAligned()) {
             debug.report(ErrorCode::ProteinAlignmentMustBeAligned);
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, backtransFile, debug, ignoreStopCodon, Alignment::isFileAligned(), origAlig, ParemeterOnlyOnBacktranslation, ProteinAlignmentMustBeAligned, reporting::reportManager::report(), and splitByStopCodon.
Referenced by check_arguments_needs().
check_block_size()
bool trimAlManager::check_block_size () inline private
Method to check if the block size is bigger than allowed depending on size of alignment.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1208 of file trimalManager.cpp.
{
     if ((!appearErrors) && (origAlig->getNumAminos() < (blockSize / 4))) {
         debug.report(ErrorCode::BlocksizeTooBig, new std::string[1]{std::to_string(origAlig->getNumAminos() / 4)});
         appearErrors = true;
         return true;
     }
     return false;
 }
References appearErrors, blockSize, BlocksizeTooBig, debug, Alignment::getNumAminos(), origAlig, and reporting::reportManager::report().
Referenced by check_arguments_needs().
check_clusters_incompatibilities()
bool trimAlManager::check_clusters_incompatibilities () inline private
Method to check clusters incompatibilities.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 913 of file trimalManager.cpp.
{
     if (clusters != -1) {
         if (clusters > origAlig->getNumSpecies()) {
             debug.report(ErrorCode::MoreClustersThanSequences);
             appearErrors = true;
         }
     }
     return appearErrors;
 }
References appearErrors, clusters, debug, Alignment::getNumSpecies(), MoreClustersThanSequences, origAlig, and reporting::reportManager::report().
Referenced by check_arguments_incompatibilities().
check_coding_sequences_type()
bool trimAlManager::check_coding_sequences_type () inline private
Method to check the type of sequences present in the backtranslationAlig.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1246 of file trimalManager.cpp.
{
     if (
         // Is there a backtranslation file?
             (!appearErrors) && (backtransFile != nullptr) &&
         // If so, is it from DNA? If not...
             ( (!backtranslationAlig->getAlignmentType()) & SequenceTypes::DNA))
     {
         // When doing backtranslation,
         //  a DNA alignment (without gaps) is needed.
         // Report the error to the user.
         debug.report(ErrorCode::BacktransAlignIsDNA);
         appearErrors = true;
         return true;
     }
     return false;
 }
References appearErrors, BacktransAlignIsDNA, backtransFile, backtranslationAlig, debug, DNA, Alignment::getAlignmentType(), and reporting::reportManager::report().
Referenced by check_arguments_needs().
check_codon_behaviour_incompatibility()
bool trimAlManager::check_codon_behaviour_incompatibility () inline private
Method to check incompatibilities related to how the algorithm should treat stop codons.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 964 of file trimalManager.cpp.
{
     if ((!appearErrors) && (ignoreStopCodon) && (splitByStopCodon)) {
         debug.report(ErrorCode::IncompatibleArguments, new std::string[2]{"-ignorestopcodon", "-splitbystopcodon"});
         appearErrors = true;
         return true;
     }
     return false;
 }
References appearErrors, debug, ignoreStopCodon, IncompatibleArguments, reporting::reportManager::report(), and splitByStopCodon.
Referenced by check_arguments_incompatibilities().
check_col_numbering()
bool trimAlManager::check_col_numbering () inline private
Method to check if column numbering makes sense based on the functionality asked.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1115 of file trimalManager.cpp.
{
     // As colnumbering doesn't make sense if we don't trim the alignment...
     if ((columnNumbering) && (!appearErrors)) {
         if (
             // Are we not using any automated method? and...
                 (!automatedMethodCount) &&
             // Are we not using any threshold? and...
                 (gapThreshold == -1) &&
                 (conservationThreshold == -1) &&
                 (similarityThreshold == -1) &&
                 (consistencyThreshold == -1) &&
             // Neither selecting any column or sequence?
                 (!selectCols) && (!selectSeqs))
         {
             // If all that happens, we are not trimming the alignment and should report it.
             debug.report(ErrorCode::TrimmingMethodNeeded, new std::string[1]{"-colnumbering"});
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, automatedMethodCount, columnNumbering, conservationThreshold, consistencyThreshold, debug, gapThreshold, reporting::reportManager::report(), selectCols, selectSeqs, similarityThreshold, and TrimmingMethodNeeded.
Referenced by check_arguments_needs().
check_combinations_among_thresholds_incompatibility()
bool trimAlManager::check_combinations_among_thresholds_incompatibility () inline private
As some thresholds are incompatible between them, we check their incompatibilities.
Returns
False if dependencies check has passed
True otherwise
Definition at line 973 of file trimalManager.cpp.
 {
     if ((consistencyThreshold != -1)
         && (conservationThreshold != -1)
         && (!appearErrors))
     {
         if ((gapThreshold != -1) || (similarityThreshold != -1)) {
             debug.report(ErrorCode::CombinationAmongThresholdsMethods);
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, CombinationAmongThresholdsMethods, conservationThreshold, consistencyThreshold, debug, gapThreshold, reporting::reportManager::report(), and similarityThreshold.
Referenced by check_arguments_incompatibilities().
check_compareset_window_argument()
void trimAlManager::check_compareset_window_argument () inline private
Method to check and warn if windowsize and compareset has been given.
Definition at line 1305 of file trimalManager.cpp.
{
     if ((!appearErrors) && (windowSize != -1) && (compareset != nullptr))
         debug.report(InfoCode::WindowSizeCompareset);
 }
References appearErrors, compareset, debug, reporting::reportManager::report(), windowSize, and WindowSizeCompareset.
Referenced by check_arguments_needs().
check_file_aligned()
bool trimAlManager::check_file_aligned () inline private
Method to check if an alignment needs to be aligned depending on the methods that have been asked to perform and, if so, checks if alignment is aligned.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1033 of file trimalManager.cpp.
{
     if ((!appearErrors) && (infile != nullptr)) {
         if (
             // Are we requesting an automated method ? or...
                 (automatedMethodCount ||
             // Are we requesting any manual threshold method ? or...
                 (gapThreshold != -1) || (consistencyThreshold != -1) || (similarityThreshold != -1) ||
             // Are we selecting columns or sequences ? or...
                 (selectCols) || (selectSeqs) ||
             // Are we using max overlap between sequences ? or...
                 (residuesOverlap != -1) || (sequenceOverlap != -1) ||
             // Are we asking for any stats?
                 (stats < 0))
             &&
             // Then we need the alignment to be aligned;
             //  If not, we should report the error
             (!origAlig->isFileAligned()))
         {
             debug.report(ErrorCode::NotAligned, new std::string[1]{infile});
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, automatedMethodCount, consistencyThreshold, debug, gapThreshold, infile, Alignment::isFileAligned(), NotAligned, origAlig, reporting::reportManager::report(), residuesOverlap, selectCols, selectSeqs, sequenceOverlap, similarityThreshold, and stats.
Referenced by check_arguments_needs().
check_force_selection()
bool trimAlManager::check_force_selection () inline private
Method to check dependency of force select argument.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1013 of file trimalManager.cpp.
{
     if (!appearErrors) {
         if ((compareset == nullptr) && (forceFile != nullptr)) {
             debug.report(ErrorCode::ForceFileWithoutCompareDataset);
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, compareset, debug, forceFile, ForceFileWithoutCompareDataset, and reporting::reportManager::report().
Referenced by check_arguments_needs().
check_inFile_incompatibilities()
bool trimAlManager::check_inFile_incompatibilities () inline private
Method to check the inFile argument incompatibilities.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 812 of file trimalManager.cpp.
{
     if (infile != nullptr) {
         if ((sfc) || (sft) || (consistencyThreshold != -1)) {
             debug.report(ErrorCode::InFileComparisonStatistics);
             appearErrors = true;
             i++;
         }
         if (compareset != nullptr) {
             debug.report(ErrorCode::IncompatibleArguments, new std::string[2]{"-in", "-compareset"});
             appearErrors = true;
         }
         if (forceFile != nullptr) {
             debug.report(ErrorCode::IncompatibleArguments, new std::string[2]{"-in", "-forceselect"});
             appearErrors = true;
         }
     }
     return appearErrors;
 }
References appearErrors, compareset, consistencyThreshold, debug, forceFile, i, IncompatibleArguments, infile, InFileComparisonStatistics, reporting::reportManager::report(), sfc, and sft.
Referenced by check_arguments_incompatibilities().
check_input_file_with_coding_sequences_argument()
bool trimAlManager::check_input_file_with_coding_sequences_argument () inline private
Method to check dependency between custom coding sequence file and infile arguments.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1024 of file trimalManager.cpp.
{
     if ((!appearErrors) && (infile == nullptr) && (compareset == nullptr) && (forceFile == nullptr) && (backtransFile != nullptr)) {
         debug.report(ErrorCode::BacktranslationWithoutMainAlignment);
         appearErrors = true;
         return true;
     }
     return false;
 }
References appearErrors, backtransFile, BacktranslationWithoutMainAlignment, compareset, debug, forceFile, infile, and reporting::reportManager::report().
Referenced by check_arguments_needs().
check_max_identity_incompatibilities()
bool trimAlManager::check_max_identity_incompatibilities () inline private
Method to check max identity incompatibilities.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 899 of file trimalManager.cpp.
{
     if (maxIdentity != -1) {
         if ((windowSize != -1) || (gapWindow != -1) || (similarityWindow != -1) || (consistencyWindow != -1)) {
             debug.report(ErrorCode::WindowAndArgumentIncompatibilities, new std::string[1]{"-maxIdentity"});
             appearErrors = true;
         }
         if (clusters != -1) {
             debug.report(ErrorCode::OnlyOneSequencesSelectionMethodAllowed);
             appearErrors = true;
         }
     }
     return appearErrors;
 }
References appearErrors, clusters, consistencyWindow, debug, gapWindow, maxIdentity, OnlyOneSequencesSelectionMethodAllowed, reporting::reportManager::report(), similarityWindow, WindowAndArgumentIncompatibilities, and windowSize.
Referenced by check_arguments_incompatibilities().
check_output_file_with_statistics()
bool trimAlManager::check_output_file_with_statistics () inline private
Method to check if there is an output file to allow statistics to be given on terminal.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1183 of file trimalManager.cpp.
{
     // TODO: Create a method to check if a trimming method has been requested.
     // TODO:    This will help to maintain coherence when scaling up
     // TODO:    With more trimming methods.
     if ((stats < 0) && (!appearErrors)) {
         stats--;
         if (
             // If we are using an automated method
                 ((automatedMethodCount) ||
             // Or a manual threshold
                 (gapThreshold != -1) || (conservationThreshold != -1) || (similarityThreshold != -1))
             // We need the outFile to be specified.
             && (outfile == nullptr))
         {
             // If so, report the error to the user.
             debug.report(ErrorCode::OutFileNeededWhenPrintingStatistics);
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, automatedMethodCount, conservationThreshold, debug, gapThreshold, outfile, OutFileNeededWhenPrintingStatistics, reporting::reportManager::report(), similarityThreshold, and stats.
Referenced by check_arguments_needs().
check_output_format()
void trimAlManager::check_output_format () inline private
Method to check if an output format has been given. If no output format has been given, it will use the inFile format.
Definition at line 1310 of file trimalManager.cpp.
{
     if (oformats.empty() && infile) {
         oformats.emplace_back(formatManager.getFileFormatName(infile));
     }
 }
References formatManager, FormatManager::getFileFormatName(), infile, and oformats.
Referenced by check_arguments_needs().
check_output_relevance()
bool trimAlManager::check_output_relevance () inline private
Method to check if, being asked to give an HTML report, it makes logic, depending on the functionality asked.
Method to check if output is coherent.
For example, it doesn't make sense to output an HTML if there is no trimming.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1154 of file trimalManager.cpp.
{
     if (((htmlOutFile != nullptr) ||
          (svgOutFile != nullptr) ||
          (svgStatsOutFile != nullptr))
          && (!appearErrors)) {
         if (
             // Are we not using any automated method? and...
                 !automatedMethodCount &&
             // Neither using thresholds? and...
                 (gapThreshold == -1) && (conservationThreshold == -1) && (similarityThreshold == -1) && (consistencyThreshold == -1) &&
             // Neither selecting columns or sequences? and...
                 (!selectCols) && (!selectSeqs) && (residuesOverlap == -1) && (sequenceOverlap == -1) &&
             // Neither using other selecting methods? and...
                 (maxIdentity == -1) && (clusters == -1))
         {
             // Then, we are not trimming the alignment and should report it.
             if (htmlOutFile != nullptr)
                 debug.report(ErrorCode::TrimmingMethodNeeded, new std::string[1]{"-htmlout"});
             if (svgOutFile != nullptr)
                 debug.report(ErrorCode::TrimmingMethodNeeded, new std::string[1]{"-svgout"});
             if (svgStatsOutFile != nullptr)
                 debug.report(ErrorCode::TrimmingMethodNeeded, new std::string[1]{"-svgstats"});
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, automatedMethodCount, clusters, conservationThreshold, consistencyThreshold, debug, gapThreshold, htmlOutFile, maxIdentity, reporting::reportManager::report(), residuesOverlap, selectCols, selectSeqs, sequenceOverlap, similarityThreshold, svgOutFile, svgStatsOutFile, and TrimmingMethodNeeded.
Referenced by check_arguments_needs().
check_outputs_coincidence()
bool trimAlManager::check_outputs_coincidence () inline private
Method to check if both output patterns (alignment output and html report output) are the same, which would mean one of them would overwrite the other.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1078 of file trimalManager.cpp.
{
     // Check dynamically that every output path is unique
     // We use two arrays:
     //      outFiles, which contains the variables
     //      outFilesNames, which is used to identify each method
     std::array<char *, 4> outFiles
     {{
         htmlOutFile,
         outfile,
         svgOutFile,
         svgStatsOutFile
     }};
     std::array<std::string, 4> outFilesNames
     {{
         "html report (-htmlout)",
         "output alignment (-out)",
         "svg report (-svgout)",
         "svg stats (-svgstats)"
     }};
     for (int i = 0, x = 0; i < outFiles.size(); i++) {
         if (outFiles.at(i) != nullptr)
             for (x = i + 1; x < outFiles.size(); x++) {
                 if (outFiles.at(x) != nullptr)
                     if (!strcmp(outFiles.at(i), outFiles.at(x))) {
                         debug.report(ErrorCode::SameNameOutput, new std::string[2]{outFilesNames.at(i), outFilesNames.at(x)});
                         appearErrors = true;
                     }
             }
     }
     return false;
 }
References appearErrors, debug, htmlOutFile, i, outfile, reporting::reportManager::report(), SameNameOutput, svgOutFile, and svgStatsOutFile.
Referenced by check_arguments_needs().
check_residue_and_sequence_overlap()
bool trimAlManager::check_residue_and_sequence_overlap () inline private
Method to check if both of them (residue overlap and sequence overlap) have been defined by the user as they have a dependency on each other.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1139 of file trimalManager.cpp.
{
     if (!appearErrors) {
         if ((residuesOverlap != -1) && (sequenceOverlap == -1)) {
             debug.report(ErrorCode::SequenceAndResiduesOverlapMutuallyNeeded, new std::string[1]{"residues overlap"});
             appearErrors = true;
             return true;
         } else if ((residuesOverlap == -1) && (sequenceOverlap != -1)) {
             debug.report(ErrorCode::SequenceAndResiduesOverlapMutuallyNeeded, new std::string[1]{"sequences overlap"});
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, debug, reporting::reportManager::report(), residuesOverlap, SequenceAndResiduesOverlapMutuallyNeeded, and sequenceOverlap.
Referenced by check_arguments_needs().
check_select_cols_and_seqs_incompatibilities()
bool trimAlManager::check_select_cols_and_seqs_incompatibilities () inline private
Method to check incompatibilities with select cols and select seqs arguments.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 831 of file trimalManager.cpp.
{
     if (selectCols || selectSeqs) {
         if ((clusters != -1) || (maxIdentity != -1)) {
             debug.report(ErrorCode::OnlyOneSequencesSelectionMethodAllowed);
             appearErrors = true;
         }
         if (selectCols)
             if (blockSize != -1) {
                 debug.report(ErrorCode::IncompatibleArguments,
                              new std::string[2]{"-selectcols", "-block"});
                 appearErrors = true;
             }
         if (selectSeqs)
             for (int i = 0; i < delSequences[0]; i++)
             {
                 if (delSequences[i] >= origAlig->getNumSpecies()) {
                     debug.report(ErrorCode::SelectOnlyAccepts,
                                  new std::string[2]{"-selectseqs", "sequences"});
                     appearErrors = true;
                     break;
                 }
             }
     }
     return appearErrors;
 }
References appearErrors, blockSize, clusters, debug, delSequences, Alignment::getNumSpecies(), i, IncompatibleArguments, maxIdentity, OnlyOneSequencesSelectionMethodAllowed, origAlig, reporting::reportManager::report(), selectCols, SelectOnlyAccepts, and selectSeqs.
Referenced by check_arguments_incompatibilities().
check_similarity_matrix()
bool trimAlManager::check_similarity_matrix () inline private
Method to check if given a similarity matrix, there is a need to use it.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1060 of file trimalManager.cpp.
{
     if ((matrixFile != nullptr) && (!appearErrors)) {
         if ((!strict) && (!strictplus) && (!automated1) && (similarityThreshold == -1) && (!ssc) && (!sst)) {
             debug.report(ErrorCode::MatrixGivenWithNoMethodToUseIt);
             appearErrors = true;
             return true;
         }
         // TODO this is an incompatibility.
         if ((gapWindow != -1) || ((compareset == nullptr) && (consistencyWindow != -1))) {
             debug.report(ErrorCode::SimilarityMatrixNotCompatibleWindow);
             appearErrors = true;
             return true;
         }
     }
     return false;
 }
References appearErrors, automated1, compareset, consistencyWindow, debug, gapWindow, matrixFile, MatrixGivenWithNoMethodToUseIt, reporting::reportManager::report(), SimilarityMatrixNotCompatibleWindow, similarityThreshold, ssc, sst, strict, and strictplus.
Referenced by check_arguments_needs().
check_stats_incompatibilities()
bool trimAlManager::check_stats_incompatibilities () inline private
Method to check statistics incompatibilities.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 933 of file trimalManager.cpp.
{
     if (stats < 0) {
         if (columnNumbering) {
             debug.report(ErrorCode::StatisticsArgumentIncompatibilities, new std::string[1]{"-colnumbering"});
             appearErrors = true;
         }
     }
     return appearErrors;
 }
References appearErrors, columnNumbering, debug, reporting::reportManager::report(), StatisticsArgumentIncompatibilities, and stats.
Referenced by check_arguments_incompatibilities().
check_thresholds_incompatibilities()
bool trimAlManager::check_thresholds_incompatibilities () inline private
Method to check incompatibilities with manual thresholds.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 860 of file trimalManager.cpp.
{
     if ((gapThreshold != -1)            ||
         (similarityThreshold != -1)     ||
         (consistencyThreshold != -1)    ||
         (conservationThreshold != -1)
         )
     {
         if (automatedMethodCount) {
             debug.report(ErrorCode::CombinationAmongTrimmingMethods);
             appearErrors = true;
         }
         if (conservationThreshold != -1) {
             if (blockSize != -1) {
                 debug.report(ErrorCode::IncompatibleArguments,
                              new std::string[2]{"-conthreshold", "-block"});
                 appearErrors = true;
             }
         }
     }
     return appearErrors;
 }
References appearErrors, automatedMethodCount, blockSize, CombinationAmongTrimmingMethods, conservationThreshold, consistencyThreshold, debug, gapThreshold, IncompatibleArguments, reporting::reportManager::report(), and similarityThreshold.
Referenced by check_arguments_incompatibilities().
check_windows_incompatibilities()
bool trimAlManager::check_windows_incompatibilities () inline private
Method to check windows incompatibilities.
Returns
True if incompatibilities check has passed
False otherwise
Definition at line 923 of file trimalManager.cpp.
{
     if (windowSize != -1) {
         if (consistencyWindow != -1 || gapWindow != -1 || similarityWindow != -1) {
             debug.report(ErrorCode::GeneralAndSpecificWindows);
             appearErrors = true;
         }
     }
     return appearErrors;
 }
References appearErrors, consistencyWindow, debug, gapWindow, GeneralAndSpecificWindows, reporting::reportManager::report(), similarityWindow, and windowSize.
Referenced by check_arguments_incompatibilities().
clean_alignment()
void trimAlManager::clean_alignment () inline private
Core Method of the program. This is where almost all cleaning methods are called from.
Definition at line 1618 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline void trimAlManager::clean_alignment() ");
     // Check alignment is aligned
     if (!origAlig->isFileAligned()) {
         debug.report(ErrorCode::NotAligned, infile);
         exit(ErrorCode::NotAligned);
     }
     // We apply first the cleaning methods that remove sequences
     CleanSequences();
     // We apply the cleaning methods that remove columns / residues
     // Combination between Automatic and Non Automatic are not allowed
     if (automatedMethodCount)
         CleanResiduesAuto();
     else
         CleanResiduesNonAuto();
 }
References automatedMethodCount, CleanResiduesAuto(), CleanResiduesNonAuto(), CleanSequences(), debug, infile, Alignment::isFileAligned(), NotAligned, origAlig, reporting::reportManager::report(), and StartTiming.
Referenced by perform(), and perform_VCF().
CleanResiduesAuto()
void trimAlManager::CleanResiduesAuto () inline private
Method to trim the alignment using automatic or semi-automatic methods:
Automatic1
NoGaps
NoAllGaps
Gappyout
Strict
Strictplus
Definition at line 1719 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline void trimAlManager::CleanResiduesAuto() ");
     // Here we use singleAlig as source alignment as the previous step,
     // CleanSequences initializes singleAlig.
     // singleAlig can be a derived alignment from origAlig or be origAlig itself
     if (automated1) {
         if (singleAlig->Cleaning->selectMethod() == GAPPYOUT)
             gappyout = true;
         else
             strict = true;
     }
     if (nogaps) {
         tempAlig = singleAlig->Cleaning->cleanGaps(0, 0, /* getComplementary*/ false);
     } else if (noallgaps) {
         tempAlig = singleAlig->Cleaning->cleanNoAllGaps(/* getComplementary*/ false);
     } else if (gappyout) {
         tempAlig = singleAlig->Cleaning->clean2ndSlope(/* getComplementary*/ false);
     } else if (strict) {
         tempAlig = singleAlig->Cleaning->cleanCombMethods(/* getComplementary*/ false, false);
     } else if (strictplus) {
         tempAlig = singleAlig->Cleaning->cleanCombMethods(/* getComplementary*/ false, true);
     }
     // Move the new formed alignment to the variable singleAlig
     if (tempAlig) {
         // If singleAlig was an created, we delete it from memory.
         if (singleAlig != origAlig)
             delete singleAlig;
         singleAlig = tempAlig;
         tempAlig = nullptr;
     }
 }
References automated1, Cleaner::clean2ndSlope(), Cleaner::cleanCombMethods(), Cleaner::cleanGaps(), Alignment::Cleaning, Cleaner::cleanNoAllGaps(), gappyout, GAPPYOUT, noallgaps, nogaps, origAlig, Cleaner::selectMethod(), singleAlig, StartTiming, strict, strictplus, and tempAlig.
Referenced by clean_alignment().
CleanResiduesNonAuto()
void trimAlManager::CleanResiduesNonAuto () inline private
Method to trim the alignment using non automatic methods:
Delete columns
Manual thresholds: Gap, Similarity and/or Consistency
Definition at line 1756 of file trimalManager.cpp.
{
     // Here we use singleAlig as source alignment as the previous step,
     // CleanSequences initializes singleAlig.
     // singleAlig can be a derived alignment from origAlig or origAlig itself
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline void trimAlManager::CleanResiduesNonAuto() ");
     if (delColumns != nullptr) {
         for (int i = 0 ; i < delColumns[0]; i++)
         {
             if (delColumns[i] >= singleAlig->getNumAminos()) {
                 debug.report(
                         ErrorCode::SelectOnlyAccepts,
                         new std::string[2]{"-selectcols", "residues"}
                 );
                 appearErrors = true;
             }
         }
          if (!appearErrors)
             tempAlig = singleAlig->Cleaning->removeColumns(
                     delColumns,
                     1,
                     delColumns[0],
                     /* getComplementary*/ false
             );
     } else {
         // Consistency will be applied prior to gap or similarity
         if (consistencyThreshold != -1.0F) {
             tempAlig = singleAlig->Cleaning->cleanCompareFile(
                     consistencyThreshold,
                     conservationThreshold,
                     origAlig->Statistics->consistency->getValues(),
                     /* getComplementary*/ false
             );
             if (singleAlig != origAlig) delete singleAlig;
             singleAlig = tempAlig;
             tempAlig = nullptr;
         }
         if (similarityThreshold != -1.0F) {
             // Clean by similarity AND gaps
             if (gapThreshold != -1.0F) {
                 tempAlig = singleAlig->Cleaning->clean(
                         conservationThreshold,
                         gapThreshold,
                         similarityThreshold,
                         /* getComplementary*/ false
                 );
                 // Clean only by similarity
             } else {
                 tempAlig = singleAlig->Cleaning->cleanConservation(
                         conservationThreshold,
                         similarityThreshold,
                         /* getComplementary*/ false
                 );
             }
             // Clean only by gaps
         } else if (gapThreshold != -1.0F) {
             tempAlig = singleAlig->Cleaning->cleanGaps(
                     conservationThreshold,
                     gapThreshold,
                     /* getComplementary*/ false
             );
         }
     }
     if (tempAlig) {
         if (singleAlig != origAlig)
             delete singleAlig;
         singleAlig = tempAlig;
         tempAlig = nullptr;
     }
 }
References appearErrors, Cleaner::clean(), Cleaner::cleanCompareFile(), Cleaner::cleanConservation(), Cleaner::cleanGaps(), Alignment::Cleaning, conservationThreshold, statistics::Manager::consistency, consistencyThreshold, debug, delColumns, gapThreshold, Alignment::getNumAminos(), statistics::Consistency::getValues(), i, origAlig, Cleaner::removeColumns(), reporting::reportManager::report(), SelectOnlyAccepts, similarityThreshold, singleAlig, StartTiming, Alignment::Statistics, and tempAlig.
Referenced by clean_alignment().
CleanSequences()
void trimAlManager::CleanSequences () inline private
Method to trim or reduce the number of sequences in an alignment. It performs one or none of the following methods:
Clusters
MaxIdentity
Delete Sequences
Sequence Overlap
When one method is applied, NoAllGaps is also applied, as these methods rely on it
Definition at line 1665 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline void trimAlManager::CleanSequences() ");
     // Clustering by number of clusters
     if (clusters != -1) {
         tempAlig = origAlig->Cleaning->getClustering(
                 origAlig->Cleaning->getCutPointClusters(clusters)
         );
     // Clustering by Max Identity
     } else if (maxIdentity != -1) {
         tempAlig = origAlig->Cleaning->getClustering(maxIdentity);
     // Remove Sequences
     } else if (delSequences != nullptr) {
         tempAlig = origAlig->Cleaning->removeSequences(
                 delSequences,       // Informative array
                 1,                  // Position to start.
                                     // Position on number 0 indicates the number of elements.
                 delSequences[0],    // Num of sequences in array
                 false               // Complementary? Legacy
         );
     // Remove by Overlap
     } else if ((residuesOverlap != -1) && (sequenceOverlap != -1)) {
         tempAlig = origAlig->Cleaning->cleanSpuriousSeq(
                 residuesOverlap,
                 sequenceOverlap / 100.0F,
                 /* getComplementary*/ false
         );
     }
     // We'll use singleAlig as input for the next cleaning step.
     // If tempAlig is not null it means that we've performed a sequence trim
     // If not, we move the origAlig to singleAlig
     if (tempAlig) {
         singleAlig = tempAlig->Cleaning->cleanNoAllGaps(false);
         delete tempAlig;
         tempAlig = nullptr;
         delete singleAlig->Statistics->gaps;
         singleAlig->Statistics->gaps = nullptr;
         delete singleAlig->Statistics->similarity;
         singleAlig->Statistics->similarity = nullptr;
     } else {
         singleAlig = origAlig;
     }
 }
References Alignment::Cleaning, Cleaner::cleanNoAllGaps(), Cleaner::cleanSpuriousSeq(), clusters, delSequences, statistics::Manager::gaps, Cleaner::getClustering(), Cleaner::getCutPointClusters(), maxIdentity, origAlig, Cleaner::removeSequences(), residuesOverlap, sequenceOverlap, statistics::Manager::similarity, singleAlig, StartTiming, Alignment::Statistics, and tempAlig.
Referenced by clean_alignment().
clusters_argument()
bool trimAlManager::clusters_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the clusters argument.
Definition at line 613 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-clusters")) && ((*i) + 1 != *argc) && (clusters == -1)) {
         if (utils::isNumber(argv[++*i])) {
             clusters = atoi(argv[*i]);
             if (clusters < 1) {
                 debug.report(ErrorCode::ClustersValueOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::ClustersValueNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, clusters, ClustersValueNotRecognized, ClustersValueOutOfRange, debug, i, utils::isNumber(), and reporting::reportManager::report().
Referenced by parseArguments().
col_numbering_argument()
bool trimAlManager::col_numbering_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the column numbering argument.
Definition at line 770 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-colnumbering")) && !columnNumbering) {
         columnNumbering = true;
         return true;
     }
     return false;
 }
References columnNumbering, and i.
Referenced by parseArguments().
compareset_argument()
bool trimAlManager::compareset_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the comparset argument.
Definition at line 353 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-compareset") && ((*i) + 1 != *argc) && (compareset == nullptr)) {
         // Check if file can be opened
         compare.open(argv[++*i], std::ifstream::in);
         if (!compare) {
             debug.report(ErrorCode::ReferenceFileNotLoaded, argv[*i]);
             appearErrors = true;
         }
         compare.close();
         compareset = argv[*i];
         return true;
     }
     return false;
 }
References appearErrors, compare, compareset, debug, i, ReferenceFileNotLoaded, and reporting::reportManager::report().
Referenced by parseArguments().
complementary_argument()
bool trimAlManager::complementary_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the complementary argument.
Definition at line 762 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-complementary")) && !getComplementary) {
         getComplementary = true;
         return true;
     }
     return false;
 }
References getComplementary, and i.
Referenced by parseArguments().
conservation_threshold_argument()
bool trimAlManager::conservation_threshold_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the similarity threshold argument.
Definition at line 448 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-cons")) && ((*i) + 1 != *argc) && (conservationThreshold == -1)) {
         if (utils::isNumber(argv[++*i])) {
             conservationThreshold = atof(argv[*i]);
             if ((conservationThreshold < 0) || (conservationThreshold > 100)) {
                 debug.report(ErrorCode::ConservationThresholdOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::ConservationThresholdNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, conservationThreshold, ConservationThresholdNotRecognized, ConservationThresholdOutOfRange, debug, i, utils::isNumber(), and reporting::reportManager::report().
Referenced by parseArguments().
consistency_threshold_argument()
bool trimAlManager::consistency_threshold_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the consistency threshold argument.
Definition at line 431 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-conthreshold") || !strcmp(argv[*i], "-ct")) && ((*i) + 1 != *argc) && (consistencyThreshold == -1)) {
         if (utils::isNumber(argv[++*i])) {
             consistencyThreshold = atof(argv[*i]);
             if ((consistencyThreshold < 0) || (consistencyThreshold > 1)) {
                 debug.report(ErrorCode::ConsistencyThresholdOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::ConsistencyThresholdNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, consistencyThreshold, ConsistencyThresholdNotRecognized, ConsistencyThresholdOutOfRange, debug, i, utils::isNumber(), and reporting::reportManager::report().
Referenced by parseArguments().
consistency_window_argument()
bool trimAlManager::consistency_window_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the Consistency Window argument.
Definition at line 691 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-cw") && ((*i) + 1 != *argc) && (consistencyWindow == -1)) {
         if (utils::isNumber(argv[*i + 1])) {
             consistencyWindow = atoi(argv[++*i]);
             if (consistencyWindow <= 0) {
                 debug.report(ErrorCode::ConsistencyWindowValueOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::ConsistencyWindowValueNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, consistencyWindow, ConsistencyWindowValueNotRecognized, ConsistencyWindowValueOutOfRange, debug, i, utils::isNumber(), and reporting::reportManager::report().
Referenced by parseArguments().
create_or_use_similarity_matrix()
bool trimAlManager::create_or_use_similarity_matrix () inline private
Method to create, load and use a similarity matrix, depending on alignment residue nature, if the user gave a specific similarity matrix, etc.
Returns
Definition at line 1581 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline bool trimAlManager::create_or_use_similarity_matrix() ");
     if ((strict) || (strictplus) || (automated1) || (similarityThreshold != -1.0) || (ssc == 1) || (sst == 1)) {
         similMatrix = new similarityMatrix();
     // Load Matrix
         if (matrixFile != nullptr)
             similMatrix->loadSimMatrix(matrixFile);
     // Alternative Default Matrix
         else if (alternative_matrix != -1) {
             similMatrix->alternativeSimilarityMatrices(alternative_matrix, origAlig->getAlignmentType());
         }
     // Default Matrices
         else {
             int alignDataType = origAlig->getAlignmentType();
             if (alignDataType & SequenceTypes::AA)
                 similMatrix->defaultAASimMatrix();
             else if ((alignDataType == SequenceTypes::DNA) || (alignDataType == SequenceTypes::RNA))
                 similMatrix->defaultNTSimMatrix();
             else if ((alignDataType == (SequenceTypes::DNA | SequenceTypes::DEG)) ||
                      (alignDataType == (SequenceTypes::RNA | SequenceTypes::DEG)))
                 similMatrix->defaultNTDegeneratedSimMatrix();
         }
     // Check if Matrix has been loaded
         if (!origAlig->Statistics->setSimilarityMatrix(similMatrix)) {
             debug.report(ErrorCode::ImpossibleToProcessMatrix);
             return false;
         }
     }
     return true;
 }
References AA, alternative_matrix, similarityMatrix::alternativeSimilarityMatrices(), automated1, debug, similarityMatrix::defaultAASimMatrix(), similarityMatrix::defaultNTDegeneratedSimMatrix(), similarityMatrix::defaultNTSimMatrix(), DEG, DNA, Alignment::getAlignmentType(), ImpossibleToProcessMatrix, similarityMatrix::loadSimMatrix(), matrixFile, origAlig, reporting::reportManager::report(), RNA, statistics::Manager::setSimilarityMatrix(), similarityThreshold, similMatrix, ssc, sst, StartTiming, Alignment::Statistics, strict, and strictplus.
Referenced by perform(), and perform_VCF().
delete_variables()
void trimAlManager::delete_variables () inline
Method to delete all variables that need to be deallocated.
Definition at line 1853 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline void trimAlManager::delete_variables() ");
     if (singleAlig == origAlig)
         singleAlig = nullptr;
     delete singleAlig;
     singleAlig = nullptr;
     delete origAlig;
     origAlig = nullptr;
     delete[] compareAlignmentsArray;
     compareAlignmentsArray = nullptr;
     delete similMatrix;
     similMatrix = nullptr;
     delete[] delColumns;
     delColumns = nullptr;
     delete[] delSequences;
     delSequences = nullptr;
     delete[] filesToCompare;
     filesToCompare = nullptr;
     delete[] outfile;
     outfile = nullptr;
     delete[] htmlOutFile;
     htmlOutFile = nullptr;
     delete[] svgOutFile;
     svgOutFile = nullptr;
     delete[] infile;
     infile = nullptr;
     delete[] matrixFile;
     matrixFile = nullptr;
     delete [] forceFile;
     forceFile = nullptr;
     delete [] backtransFile;
     backtransFile = nullptr;
     delete backtranslationAlig;
     backtranslationAlig = nullptr;
     delete vcfs;
     vcfs = nullptr;
     delete CS;
     CS = nullptr;
 }
References backtransFile, backtranslationAlig, compareAlignmentsArray, CS, delColumns, delSequences, filesToCompare, forceFile, htmlOutFile, infile, matrixFile, origAlig, outfile, similMatrix, singleAlig, StartTiming, svgOutFile, and vcfs.
Referenced by ~trimAlManager().
examples()
void trimAlManager::examples () inline private
Method to show the examples information about the program.
Definition at line 1929 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("void trimAlManager::examples(void) ");
     // Simple idiom to allow including a text file into a char array at compile time
     // Explanation: https://stackoverflow.com/a/25021520
     std::string examples = {
         #include "examples.txt"
     };
     std::cout << examples;
 }
References StartTiming.
Referenced by help_arguments(), and parseArguments().
force_select_argument()
bool trimAlManager::force_select_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the force select argument.
Definition at line 368 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-forceselect") && ((*i) + 1 != *argc) && (forceFile == nullptr)) {
         argumentLength = strlen(argv[++*i]);
         forceFile = new char[argumentLength + 1];
         strcpy(forceFile, argv[*i]);
         if ((origAlig = formatManager.loadAlignment(forceFile)) == nullptr) {
             debug.report(ErrorCode::AlignmentNotLoaded, forceFile);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References AlignmentNotLoaded, appearErrors, argumentLength, debug, forceFile, formatManager, i, FormatManager::loadAlignment(), origAlig, and reporting::reportManager::report().
Referenced by parseArguments().
gap_threshold_argument()
bool trimAlManager::gap_threshold_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the gap threshold argument.
Definition at line 397 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-gapthreshold") || !strcmp(argv[*i], "-gt")) && ((*i) + 1 != *argc) && (gapThreshold == -1)) {
         if (utils::isNumber(argv[++*i])) {
             gapThreshold = 1. - atof(argv[*i]);
             if ((gapThreshold < 0) || (gapThreshold > 1)) {
                 debug.report(ErrorCode::GapThresholdOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::GapThresholdNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, debug, gapThreshold, GapThresholdNotRecognized, GapThresholdOutOfRange, i, utils::isNumber(), and reporting::reportManager::report().
Referenced by parseArguments().
gap_window_argument()
bool trimAlManager::gap_window_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the Gap Window argument.
Definition at line 656 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-gw") && ((*i) + 1 != *argc) && (gapWindow == -1)) {
         if (utils::isNumber(argv[*i + 1])) {
             gapWindow = atoi(argv[++*i]);
             if (gapWindow <= 0) {
                 debug.report(ErrorCode::GapWindowValueOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::GapWindowValueNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, debug, gapWindow, GapWindowValueNotRecognized, GapWindowValueOutOfRange, i, utils::isNumber(), and reporting::reportManager::report().
Referenced by parseArguments().
gappy_out_argument()
bool trimAlManager::gappy_out_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the gappyout argument.
Definition at line 516 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-gappyout") && (!strict)) {
         gappyout = true;
         return true;
     }
     return false;
 }
References gappyout, i, and strict.
Referenced by parseArguments().
help_arguments()
void trimAlManager::help_arguments (const int * argc, char * argv[], int * currentArg) inline private
Method to parse information arguments as help and menu.
Definition at line 194 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-h") || !strcmp(argv[*i], "-help")) {
         menu();
         examples();
         exit(0); // We don't want to continue if we show the help.
     }
     if (!strcmp(argv[*i], "--version")) {
         std::cout << VERSION << std::endl;
         exit(0); // We don't want to continue if we show the version.
     }
     if (!strcmp(argv[*i], "-lf") || !strcmp(argv[*i], "--listformats")) {
         std::cout << "Input Formats:  " << formatManager.getInputFormatsAvailable() << "\n";
         std::cout << "Output Formats: " << formatManager.getOutputFormatsAvailable() << "\n";
         exit(0);
     }
 }
References examples(), formatManager, FormatManager::getInputFormatsAvailable(), FormatManager::getOutputFormatsAvailable(), i, menu(), and VERSION.
Referenced by parseArguments().
html_out_argument()
bool trimAlManager::html_out_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the html output file.
Definition at line 253 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-htmlout")) && ((*i) + 1 != *argc) && (htmlOutFile == nullptr)) {
         argumentLength = strlen(argv[++*i]);
         htmlOutFile = new char[argumentLength + 1];
         strcpy(htmlOutFile, argv[*i]);
         return true;
     }
     return false;
 }
References argumentLength, htmlOutFile, and i.
Referenced by parseArguments().
ignore_stop_codon_argument()
bool trimAlManager::ignore_stop_codon_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse ignore by stop codon argument.
Definition at line 786 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-ignorestopcodon")) && !ignoreStopCodon) {
         ignoreStopCodon = true;
         return true;
     }
     return false;
 }
References i, and ignoreStopCodon.
Referenced by parseArguments().
in_argument()
bool trimAlManager::in_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the input file argument.
Definition at line 213 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-in") && ((*i) + 1 != *argc) && (infile == nullptr)) {
         argumentLength = strlen(argv[++*i]);
         infile = new char[argumentLength + 1];
         strcpy(infile, argv[*i]);
         if ((origAlig = formatManager.loadAlignment(infile)) == nullptr) {
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, argumentLength, formatManager, i, infile, FormatManager::loadAlignment(), and origAlig.
Referenced by parseArguments().
keep_header_argument()
bool trimAlManager::keep_header_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the keepHeader argument.
Definition at line 508 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-keepheader") && (!formatManager.keepHeader)) {
         formatManager.keepHeader = true;
         return true;
     }
     return false;
 }
References formatManager, i, and FormatManager::keepHeader.
Referenced by parseArguments().
keep_seqs_argument()
bool trimAlManager::keep_seqs_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the keepSeqs argument.
Definition at line 500 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-keepseqs") && (!keepSeqs)) {
         keepSeqs = true;
         return true;
     }
     return false;
 }
References i, and keepSeqs.
Referenced by parseArguments().
matrix_argument()
bool trimAlManager::matrix_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the custom matrix argument.
Definition at line 335 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-matrix") && ((*i) + 1 != *argc) && (matrixFile == nullptr)) {
         argumentLength = strlen(argv[++*i]);
         matrixFile = new char[argumentLength + 1];
         strcpy(matrixFile, argv[*i]);
         return true;
     } else if (!strcmp(argv[*i], "--alternative_matrix") && ((*i) + 1 != *argc) && (alternative_matrix == -1)) {
         i++;
         if (!strcmp(argv[*i], "degenerated_nt_identity"))
             alternative_matrix = 1;
         else {
             debug.report(ErrorCode::AlternativeMatrixNotRecognized, argv[*i]);
             appearErrors = true;
         }
     }
     return false;
 }
References alternative_matrix, AlternativeMatrixNotRecognized, appearErrors, argumentLength, debug, i, matrixFile, and reporting::reportManager::report().
Referenced by parseArguments().
max_identity_argument()
bool trimAlManager::max_identity_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the max identity argument.
Definition at line 594 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-maxidentity")) && ((*i) + 1 != *argc) && (maxIdentity == -1)) {
         if (utils::isNumber(argv[++*i])) {
             maxIdentity = atof(argv[*i]);
             if ((maxIdentity < 0) || (maxIdentity > 1)) {
                 debug.report(ErrorCode::MaxIdentityOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::MaxIdentityNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, debug, i, utils::isNumber(), maxIdentity, MaxIdentityNotRecognized, MaxIdentityOutOfRange, and reporting::reportManager::report().
Referenced by parseArguments().
menu()
void trimAlManager::menu () inline private
Method to show the menu of the program.
Definition at line 1908 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("void trimAlManager::menu(void) ");
     // Simple idiom to allow including a text file into a char array at compile time
     // Explanation: https://stackoverflow.com/a/25021520
     std::string menu = {
         #include "menu.txt"
     };
     utils::ReplaceStringInPlace(menu, "[iformat]", formatManager.getInputFormatsAvailable());
     utils::ReplaceStringInPlace(menu, "[oformat]", formatManager.getOutputFormatsAvailable());
     utils::ReplaceStringInPlace(menu, "[version]", VERSION);
     utils::ReplaceStringInPlace(menu, "[revision]", REVISION);
     utils::ReplaceStringInPlace(menu, "[build]", BUILD);
     utils::ReplaceStringInPlace(menu, "[authors]", AUTHORS);
     std::cout << menu;
 }
References AUTHORS, BUILD, formatManager, FormatManager::getInputFormatsAvailable(), FormatManager::getOutputFormatsAvailable(), utils::ReplaceStringInPlace(), REVISION, StartTiming, and VERSION.
Referenced by help_arguments(), and parseArguments().
no_all_gaps_argument()
bool trimAlManager::no_all_gaps_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the noallgaps argument.
Definition at line 492 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-noallgaps") && (!noallgaps)) {
         noallgaps = true;
         return true;
     }
     return false;
 }
References i, and noallgaps.
Referenced by parseArguments().
no_gaps_argument()
bool trimAlManager::no_gaps_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the nogaps argument.
Definition at line 484 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-nogaps") && (!nogaps)) {
         nogaps = true;
         return true;
     }
     return false;
 }
References i, and nogaps.
Referenced by parseArguments().
out_argument()
bool trimAlManager::out_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the output file pattern.
Definition at line 243 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-out")) && ((*i) + 1 != *argc) && (outfile == nullptr)) {
         argumentLength = strlen(argv[++*i]);
         outfile = new char[argumentLength + 1];
         strcpy(outfile, argv[*i]);
         return true;
     }
     return false;
 }
References argumentLength, i, and outfile.
Referenced by parseArguments().
out_format_arguments()
bool trimAlManager::out_format_arguments (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the output formats as -fasta -clustal or -formats [...].
Definition at line 300 of file trimalManager.cpp.
{
     // Detect formats using the ReadWriteMachineState (RWMS) method
     //  Store the formats desired on 'oformats' list, which
     //  will be passed to the RWMS
     if (!strcmp(argv[*i], "-formats")) {
         if ((*i + 1) == *argc) {
             debug.report(ErrorCode::NoFormatsSpecified);
         }
         while (++(*i) != *argc && argv[*i][0] != '-')
             oformats.emplace_back(argv[*i]);
         (*i)--;
         return true;
     }
     // Legacy formats handling code.
     //  Makes use of the macro LegacyFormatArgumentWrapper
     //  for the sake of understandability.
     // This transforms the old arguments to the RWMS format,
     //  emplacing the IDS for each format on oformats list.
     LegacyFormatArgumentWrapper("-clustal", "clustal")
     LegacyFormatArgumentWrapper("-fasta", "fasta")
     LegacyFormatArgumentWrapper("-fasta_m10", "fasta_m10")
     LegacyFormatArgumentWrapper("-nbrf", "pir")
     LegacyFormatArgumentWrapper("-nexus", "nexus")
     LegacyFormatArgumentWrapper("-mega", "mega")
     LegacyFormatArgumentWrapper("-phylip3.2", "phylip32")
     LegacyFormatArgumentWrapper("-phylip3.2_m10", "phylip32_m10")
     LegacyFormatArgumentWrapper("-phylip", "phylip40")
     LegacyFormatArgumentWrapper("-phylip_m10", "phylip40_m10")
     LegacyFormatArgumentWrapper("-phylip_paml", "phylip_paml")
     LegacyFormatArgumentWrapper("-phylip_paml_m10", "phylip_paml_m10")
     return false;
 }
References debug, i, LegacyFormatArgumentWrapper, NoFormatsSpecified, oformats, and reporting::reportManager::report().
Referenced by parseArguments().
output_reports()
void trimAlManager::output_reports () inline private
Definition at line 1441 of file trimalManager.cpp.
 {
     if ((svgOutFile != nullptr) && (!appearErrors))
         if (!origAlig->
                 alignmentSummarySVG(*singleAlig, svgOutFile, 0)) {
             debug.report(ErrorCode::ImpossibleToGenerate, new std::string[1]{"the SVG output file"});
             appearErrors = true;
         }
     if ((htmlOutFile != nullptr) && (!appearErrors))
         if (!origAlig->
                 alignmentSummaryHTML(*singleAlig, htmlOutFile)) {
             debug.report(ErrorCode::ImpossibleToGenerate, new std::string[1]{"the HTML output file"});
             appearErrors = true;
         }
 }
References appearErrors, debug, htmlOutFile, ImpossibleToGenerate, origAlig, reporting::reportManager::report(), singleAlig, and svgOutFile.
Referenced by perform().
parseArguments()
void trimAlManager::parseArguments (int argc, char * argv[])
Method to parse arguments into usable structure in trimal.
Definition at line 36 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("void trimAlManager::parseArguments(int argc, char *argv[]) ");
     // Call to verbosity argument has to be done
     //  before any other argument.
     verbosity_argument(&argc, argv);
     // Check if there is only an argument passed to trimAl,
     //  if so, show the menu and the examples
     if (argc == 1) {
         menu();
         examples();
         exit(0);
     }
     // Check every provided argument
     //  with each argument method
     for (int i = 1; i < argc; i++) {
         if (appearErrors) break;
         help_arguments(&argc, argv, &i);
         // Check arguments. Makes use of the
         //  macro checkArgument (start of the file)
         //  to make code more understandable.
         //
         // Argument passed to checkArgument is,
         //  indeed, a method with signature:
         //  x_argument(&argc, argv, &i)
         checkArgument(in_argument)
         checkArgument(vcf_argument)
         checkArgument(out_argument)
         checkArgument(html_out_argument)
         checkArgument(timetracker_out_argument)
         checkArgument(svg_out_argument)
         checkArgument(svg_stats_argument)
         checkArgument(out_format_arguments)
         checkArgument(matrix_argument)
         checkArgument(compareset_argument)
         checkArgument(force_select_argument)
         checkArgument(back_trans_argument)
         checkArgument(gap_threshold_argument)
         checkArgument(similarity_threshold_argument)
         checkArgument(consistency_threshold_argument)
         checkArgument(conservation_threshold_argument)
         checkArgument(no_gaps_argument)
         checkArgument(no_all_gaps_argument)
         checkArgument(keep_seqs_argument)
         checkArgument(keep_header_argument)
         checkArgument(gappy_out_argument)
         checkArgument(strict_argument)
         checkArgument(strict_plus_argument)
         checkArgument(automated1_argument)
         checkArgument(residue_overlap_argument)
         checkArgument(sequence_overlap_argument)
         checkArgument(seqs_select_argument)
         checkArgument(select_cols_argument)
         checkArgument(max_identity_argument)
         checkArgument(clusters_argument)
         checkArgument(terminal_only_argument)
         checkArgument(window_argument)
         checkArgument(gap_window_argument)
         checkArgument(similarity_window_argument)
         checkArgument(consistency_window_argument)
         checkArgument(block_argument)
         checkArgument(stats_arguments)
         checkArgument(complementary_argument)
         checkArgument(col_numbering_argument);
         checkArgument(split_by_stop_codon_argument)
         checkArgument(ignore_stop_codon_argument)
         // Skip the verbosity option, as it was checked before the loop
         if (!strcmp(argv[i], "--verbosity") || !strcmp(argv[i], "-v")) {
             i++;
             continue;
         }
         debug.report(ErrorCode::ParameterNotFoundOrRepeated, argv[i]);
         appearErrors = true;
         break;
     }
     performCompareset();
     // Check if we've provided multiple correct arguments
     // but no input file is provided.
     if (infile == nullptr && compareset == nullptr) {
         debug.report(ErrorCode::NoInputFile);
         exit(0);
     }
 }
References appearErrors, automated1_argument(), back_trans_argument(), block_argument(), checkArgument, clusters_argument(), col_numbering_argument(), compareset, compareset_argument(), complementary_argument(), conservation_threshold_argument(), consistency_threshold_argument(), consistency_window_argument(), debug, examples(), force_select_argument(), gap_threshold_argument(), gap_window_argument(), gappy_out_argument(), help_arguments(), html_out_argument(), i, ignore_stop_codon_argument(), in_argument(), infile, keep_header_argument(), keep_seqs_argument(), matrix_argument(), max_identity_argument(), menu(), no_all_gaps_argument(), no_gaps_argument(), NoInputFile, out_argument(), out_format_arguments(), ParameterNotFoundOrRepeated, performCompareset(), reporting::reportManager::report(), residue_overlap_argument(), select_cols_argument(), seqs_select_argument(), sequence_overlap_argument(), similarity_threshold_argument(), similarity_window_argument(), split_by_stop_codon_argument(), StartTiming, stats_arguments(), strict_argument(), strict_plus_argument(), svg_out_argument(), svg_stats_argument(), terminal_only_argument(), timetracker_out_argument(), vcf_argument(), verbosity_argument(), and window_argument().
Referenced by main().
perform()
int trimAlManager::perform ()
Method to perform the analysis if all checks have passed.
Returns
0 if all went ok.
-1 if parsing arguments went wrong on previously steps
-2 if there was a problem with the similarity matrix.
Definition at line 1316 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("int trimAlManager::perform() ");
     // We don't perform any manipulation in previous steps an error has
     // been detected
     if (appearErrors)
     return -1;
     // If similarity threshold is -1, it hasn't been specified, and we
     // use 0 as default value, which makes no effect
     if (conservationThreshold == -1)
         conservationThreshold = 0;
     // In case we are doing VCF transformations, the perform should
     // be applied in all the collection.
     if (vcfs != nullptr)
         return perform_VCF();
     origAlig->Cleaning->setTrimTerminalGapsFlag(terminalOnly);
     origAlig->setKeepSequencesFlag(keepSeqs);
     set_window_size();
     if (blockSize != -1)
         origAlig->setBlockSize(blockSize);
     if (!create_or_use_similarity_matrix())
         return -2;
     if (svgStatsOutFile != nullptr)
         svg_stats_out();
     print_statistics();
     clean_alignment();
     if (singleAlig == nullptr) {
         singleAlig = origAlig;
         origAlig = nullptr;
     }
     postprocess_alignment();
     output_reports();
     save_alignment();
     if ((columnNumbering) && (!appearErrors))
         singleAlig->Statistics->printCorrespondence();
     return 0;
 }
References appearErrors, blockSize, clean_alignment(), Alignment::Cleaning, columnNumbering, conservationThreshold, create_or_use_similarity_matrix(), keepSeqs, origAlig, output_reports(), perform_VCF(), postprocess_alignment(), print_statistics(), statistics::Manager::printCorrespondence(), save_alignment(), set_window_size(), Alignment::setBlockSize(), Alignment::setKeepSequencesFlag(), Cleaner::setTrimTerminalGapsFlag(), singleAlig, StartTiming, Alignment::Statistics, svg_stats_out(), svgStatsOutFile, terminalOnly, and vcfs.
Referenced by main().
perform_VCF()
int trimAlManager::perform_VCF () inline private
Definition at line 1371 of file trimalManager.cpp.
 {
     auto XX = formatManager.splitAlignmentKeeping(*origAlig);
     char replacement = '-';
     ngs::readVCF(
             /* Dataset          */ XX,
             /* VCF Collection   */ *vcfs,
             /* min Quality      */ 0,
             /* min Coverage     */ 30,
             /* ignore Filters   */ false,
             /* replacement char */ &replacement
     );
     for (Alignment* &i : XX) {
         delete origAlig;
         origAlig = i;
         origAlig->Cleaning->setTrimTerminalGapsFlag(terminalOnly);
         origAlig->setKeepSequencesFlag(keepSeqs);
         set_window_size();
         if (blockSize != -1)
             origAlig->setBlockSize(blockSize);
         if (!create_or_use_similarity_matrix())
             return -2;
         if (svgStatsOutFile != nullptr)
             svg_stats_out();
         // print_statistics();
         clean_alignment();
         postprocess_alignment();
         if ((outfile != nullptr) && (!appearErrors)) {
             std::string outFileString = std::string(outfile);
             if (!formatManager.saveAlignment(outFileString, &oformats, origAlig)) {
                 appearErrors = true;
             }
         }
     }
     return 0;
 }
References appearErrors, blockSize, clean_alignment(), Alignment::Cleaning, create_or_use_similarity_matrix(), formatManager, i, keepSeqs, oformats, origAlig, outfile, postprocess_alignment(), ngs::readVCF(), FormatManager::saveAlignment(), set_window_size(), Alignment::setBlockSize(), Alignment::setKeepSequencesFlag(), Cleaner::setTrimTerminalGapsFlag(), FormatManager::splitAlignmentKeeping(), svg_stats_out(), svgStatsOutFile, terminalOnly, and vcfs.
Referenced by perform().
performCompareset()
bool trimAlManager::performCompareset () inline private
Method to check if multiple files comparison has been set correctly.
It also perform some calculations needed on comparfiles behaviour.
Returns
False if dependencies check has passed
True otherwise
Definition at line 1432 of file trimalManager.cpp.
{
     if ((compareset != nullptr) && (!appearErrors)) {
         CS = new statistics::Consistency();
         CS->perform(compareset, formatManager, *this, forceFile);
     }
     return appearErrors;
 }
References appearErrors, compareset, CS, forceFile, formatManager, and statistics::Consistency::perform().
Referenced by parseArguments().
postprocess_alignment()
void trimAlManager::postprocess_alignment () inline private
Definition at line 1641 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline void trimAlManager::postprocess_alignment()");
     // Only terminal
     if (terminalOnly)
         singleAlig->Cleaning->removeOnlyTerminal();
     // Complementary
     if (getComplementary)
         singleAlig->Cleaning->computeComplementaryAlig(true, false);
     // Backtranslate
     if (backtransFile != nullptr) {
         tempAlig = backtranslationAlig->getTranslationCDS(singleAlig);
         if (singleAlig != origAlig)
             delete singleAlig;
         singleAlig = tempAlig;
         tempAlig = nullptr;
     }
 }
References backtransFile, backtranslationAlig, Alignment::Cleaning, Cleaner::computeComplementaryAlig(), getComplementary, Alignment::getTranslationCDS(), origAlig, Cleaner::removeOnlyTerminal(), singleAlig, StartTiming, tempAlig, and terminalOnly.
Referenced by perform(), and perform_VCF().
print_statistics()
void trimAlManager::print_statistics () inline private
Method to print statistics requested.
Definition at line 1458 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline void trimAlManager::print_statistics() ");
     if (sgc) {
         origAlig->Statistics->printStatisticsGapsColumns();
         stats++;
     }
     if (sgt) {
         origAlig->Statistics->printStatisticsGapsTotal();
         stats++;
     }
     if (ssc) {
         origAlig->Statistics->printStatisticsConservationColumns();
         stats++;
     }
     if (sst) {
         origAlig->Statistics->printStatisticsConservationTotal();
         stats++;
     }
     if (sident) {
         origAlig->printSeqIdentity();
         stats++;
     }
     if (soverlap) {
         origAlig->printSeqOverlap();
         stats++;
     }
     if (compareset != nullptr) {
         if (sfc)
             statistics::Consistency::printStatisticsFileColumns(*origAlig, origAlig->Statistics->consistency->getValues());
         if (sft)
             statistics::Consistency::printStatisticsFileAcl(*origAlig, origAlig->Statistics->consistency->getValues());
     }
 }
References compareset, statistics::Manager::consistency, statistics::Consistency::getValues(), origAlig, Alignment::printSeqIdentity(), Alignment::printSeqOverlap(), statistics::Manager::printStatisticsConservationColumns(), statistics::Manager::printStatisticsConservationTotal(), statistics::Consistency::printStatisticsFileAcl(), statistics::Consistency::printStatisticsFileColumns(), statistics::Manager::printStatisticsGapsColumns(), statistics::Manager::printStatisticsGapsTotal(), sfc, sft, sgc, sgt, sident, soverlap, ssc, sst, StartTiming, Alignment::Statistics, and stats.
Referenced by perform().
processArguments()
bool trimAlManager::processArguments (char * argv[])
Method to process the information obtained by trimAlManager::parseArguments
It checks for argument incompatibilities and arguments dependencies.
Parameters
argv Arguments passed to the program
Returns
True if all checks have passed
False otherwise
Definition at line 794 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("bool trimAlManager::processArguments(char *argv[]) ");
     if (!appearErrors) {
         // This allows us to have a count of all the automatic methods
         //  that have been requested.
         // We can use this information to prevent performing more than one method,
         //  and using as a bool, to check if any automatic method has been used.
         automatedMethodCount = nogaps + noallgaps + gappyout + strict + strictplus + automated1;
         check_arguments_incompatibilities();
         check_arguments_needs(argv);
     }
     return appearErrors;
 }
References appearErrors, automated1, automatedMethodCount, check_arguments_incompatibilities(), check_arguments_needs(), gappyout, noallgaps, nogaps, StartTiming, strict, and strictplus.
Referenced by main().
residue_overlap_argument()
bool trimAlManager::residue_overlap_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the residue overlap argument.
Definition at line 548 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-resoverlap")) && ((*i) + 1 != *argc) && (residuesOverlap == -1)) {
         if (utils::isNumber(argv[++*i])) {
             residuesOverlap = atof(argv[*i]);
             if ((residuesOverlap < 0) || (residuesOverlap > 1)) {
                 debug.report(ErrorCode::ResidueOverlapOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::ResidueOverlapNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, debug, i, utils::isNumber(), reporting::reportManager::report(), ResidueOverlapNotRecognized, ResidueOverlapOutOfRange, and residuesOverlap.
Referenced by parseArguments().
save_alignment()
void trimAlManager::save_alignment () inline private
Definition at line 1418 of file trimalManager.cpp.
 {
     if ((outfile != nullptr) && (!appearErrors)) {
         std::string outFileString = std::string(outfile);
         if (!formatManager.saveAlignment(outFileString, &oformats, singleAlig)) {
             appearErrors = true;
         }
     } else if ((stats >= 0) && (!appearErrors))
     {
         formatManager.saveAlignment("", &oformats, singleAlig);
     }
 }
References appearErrors, formatManager, oformats, outfile, FormatManager::saveAlignment(), singleAlig, and stats.
Referenced by perform().
select_cols_argument()
bool trimAlManager::select_cols_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the select columns argument.
Definition at line 466 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-selectcols") &&
         !selectCols &&
         (*i + 3) < *argc &&
         !strcmp(argv[++(*i)], "{") &&
         !strcmp(argv[(*i) + 2], "}")) {
         if ((delColumns = utils::readNumbers(argv[++(*i)])) == nullptr) {
             debug.report(ErrorCode::SelectColsNotRecognized);
             appearErrors = true;
         } else selectCols = true;
         (*i)++;
         return true;
     }
     return false;
 }
References appearErrors, debug, delColumns, i, utils::readNumbers(), reporting::reportManager::report(), selectCols, and SelectColsNotRecognized.
Referenced by parseArguments().
seqs_select_argument()
bool trimAlManager::seqs_select_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse que select sequences argument.
Definition at line 582 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-selectseqs")) && !selectSeqs && ((*i + 3) < *argc) && (!strcmp(argv[++*i], "{")) && (!strcmp(argv[*i + 2], "}"))) {
         if ((delSequences = utils::readNumbers(argv[++*i])) == nullptr) {
             debug.report(ErrorCode::SelectSeqsNotRecognized);
             appearErrors = true;
         } else selectSeqs = true;
         (*i)++;
         return true;
     }
     return false;
 }
References appearErrors, debug, delSequences, i, utils::readNumbers(), reporting::reportManager::report(), selectSeqs, and SelectSeqsNotRecognized.
Referenced by parseArguments().
sequence_overlap_argument()
bool trimAlManager::sequence_overlap_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the sequence overlap argument.
Definition at line 565 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-seqoverlap")) && ((*i) + 1 != *argc) && (sequenceOverlap == -1)) {
         if (utils::isNumber(argv[++*i])) {
             sequenceOverlap = atof(argv[*i]);
             if ((sequenceOverlap < 0) || (sequenceOverlap > 100)) {
                 debug.report(ErrorCode::SequencesOverlapOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::SequencesOverlapNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, debug, i, utils::isNumber(), reporting::reportManager::report(), sequenceOverlap, SequencesOverlapNotRecognized, and SequencesOverlapOutOfRange.
Referenced by parseArguments().
set_window_size()
void trimAlManager::set_window_size () inline private
Method to set correct window sizes depending on values for them given by the user.
Definition at line 1837 of file trimalManager.cpp.
{
     // Create a timer that will report times upon its destruction
     //  which means the end of the current scope.
     StartTiming("inline void trimAlManager::set_window_size() ");
     if (windowSize != -1) {
         gapWindow = windowSize;
         similarityWindow = windowSize;
     } else {
         if (gapWindow == -1)
             gapWindow = 0;
         if (similarityWindow == -1)
             similarityWindow = 0;
     }
     origAlig->setWindowsSize(gapWindow, similarityWindow);
 }
References gapWindow, origAlig, Alignment::setWindowsSize(), similarityWindow, StartTiming, and windowSize.
Referenced by perform(), and perform_VCF().
similarity_threshold_argument()
bool trimAlManager::similarity_threshold_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the similarity threshold argument.
Definition at line 414 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-simthreshold") || !strcmp(argv[*i], "-st")) && ((*i) + 1 != *argc) && (similarityThreshold == -1)) {
         if (utils::isNumber(argv[++*i])) {
             similarityThreshold = atof(argv[*i]);
             if ((similarityThreshold < 0) || (similarityThreshold > 1)) {
                 debug.report(ErrorCode::SimilarityThresholdOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::SimilarityThresholdNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, debug, i, utils::isNumber(), reporting::reportManager::report(), similarityThreshold, SimilarityThresholdNotRecognized, and SimilarityThresholdOutOfRange.
Referenced by parseArguments().
similarity_window_argument()
bool trimAlManager::similarity_window_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the Similarity Window argument.
Definition at line 673 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-sw") && ((*i) + 1 != *argc) && (similarityWindow == -1)) {
         if (utils::isNumber(argv[*i + 1])) {
             similarityWindow = atoi(argv[++*i]);
             if (similarityWindow <= 0) {
                 debug.report(ErrorCode::SimilarityWindowValueOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::SimilarityWindowValueNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, debug, i, utils::isNumber(), reporting::reportManager::report(), similarityWindow, SimilarityWindowValueNotRecognized, and SimilarityWindowValueOutOfRange.
Referenced by parseArguments().
split_by_stop_codon_argument()
bool trimAlManager::split_by_stop_codon_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse split by stop codon argument.
Definition at line 778 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-splitbystopcodon")) && !splitByStopCodon) {
         splitByStopCodon = true;
         return true;
     }
     return false;
 }
References i, and splitByStopCodon.
Referenced by parseArguments().
stats_arguments()
bool trimAlManager::stats_arguments (const int * argc, char * argv[], int * currentArg) inline private
Method to parse stats arguments.
Definition at line 743 of file trimalManager.cpp.
{
     stat_check(sgc)
     stat_check(sgt)
     stat_check(ssc)
     stat_check(sst)
     stat_check(sident)
     stat_check(soverlap)
     stat_check(sfc)
     stat_check(sft)
     // As macro stat_check is able to make the method to return values
     //  under certain circumstances, althought the method (stats_arguments)
     //  seem to always return false, this is incorrect and the method can
     //  return True or False, depeding if a stat argument has been recognized.
     return false;
 }
References sfc, sft, sgc, sgt, sident, soverlap, ssc, sst, and stat_check.
Referenced by parseArguments().
strict_argument()
bool trimAlManager::strict_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the strict argument.
Definition at line 524 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-strict") && (!strict)) {
         strict = true;
         return true;
     }
     return false;
 }
References i, and strict.
Referenced by parseArguments().
strict_plus_argument()
bool trimAlManager::strict_plus_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the strictplus argument.
Definition at line 532 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-strictplus")) && (!strictplus)) {
         strictplus = true;
         return true;
     }
     return false;
 }
References i, and strictplus.
Referenced by parseArguments().
svg_out_argument()
bool trimAlManager::svg_out_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the svg output file.
Definition at line 271 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-svgout")) && ((*i) + 1 != *argc) && (svgOutFile == nullptr)) {
         argumentLength = strlen(argv[++*i]);
         svgOutFile = new char[argumentLength + 1];
         strcpy(svgOutFile, argv[*i]);
         return true;
     }
     return false;
 }
References argumentLength, i, and svgOutFile.
Referenced by parseArguments().
svg_stats_argument()
bool trimAlManager::svg_stats_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the svg stats output file.
Definition at line 281 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-svgstats")) && ((*i) + 1 != *argc) && (svgStatsOutFile == nullptr)) {
         argumentLength = strlen(argv[++*i]);
         svgStatsOutFile = new char[argumentLength + 1];
         strcpy(svgStatsOutFile, argv[*i]);
         return true;
     }
     return false;
 }
References argumentLength, i, and svgStatsOutFile.
Referenced by parseArguments().
svg_stats_out()
void trimAlManager::svg_stats_out () inline private
Definition at line 1501 of file trimalManager.cpp.
 {
     std::string title = infile;
     std::string filename = svgStatsOutFile;
     std::string linename = "";
     std::string color = "";
     utils::streamSVG(nullptr, nullptr, 0, nullptr, nullptr, &title, &filename);
     if (origAlig->Statistics->calculateGapStats()) {
         float acm = 0.0F;
         float x = 0;
         float y = 1.F;
         color = "red";
         linename = "gaps";
         utils::streamSVG(&x, &y, 0, &linename, &color, nullptr, nullptr);
         for (i = 0, acm = 0; i <= origAlig->Statistics->gaps->maxGaps; i++) {
             // If the columns' number with this gaps' number is not equal to zero, we will count the columns.
             if (origAlig->Statistics->gaps->numColumnsWithGaps[i] != 0) {
                 // Compute and prints the accumulative values for the gaps in the alignment.
                 acm += origAlig->Statistics->gaps->numColumnsWithGaps[i];
                 x = acm / origAlig->numberOfResidues;
                 y = 1.F - ((i * 1.0F) / origAlig->numberOfSequences);
                 utils::streamSVG(&x, &y, 0, &linename, &color, nullptr, nullptr);
             }
         }
     }
     if (origAlig->Statistics->calculateConservationStats()) {
         color = "blue";
         linename = "similarity";
         float x = 0;
         float y = 1.F;
         utils::streamSVG(&x, &y, 0, &linename, &color, nullptr, nullptr);
         float refer, *vectAux;
         int i, num, acm;
         // Allocate memory
         vectAux = new float[origAlig->numberOfResidues];
         // Select the similarity's value source and copy that vector in a auxiliar vector
         if (origAlig->Statistics->similarity->MDK_Window != nullptr)
             utils::copyVect(origAlig->Statistics->similarity->MDK_Window, vectAux, origAlig->numberOfResidues);
         else
             utils::copyVect(origAlig->Statistics->similarity->MDK, vectAux, origAlig->numberOfResidues);
         // Sort the auxiliar vector.
         utils::quicksort(vectAux, 0, origAlig->numberOfResidues - 1);
         // Initializate some values
         refer = vectAux[origAlig->numberOfResidues - 1];
         acm = 0;
         num = 1;
         // Count the columns with the same similarity's value and compute this information to shows the accunulative
         // statistics in the alignment.
         for (i = origAlig->numberOfResidues - 2; i >= 0; i--) {
             acm++;
             if (refer != vectAux[i]) {
                 x = ((float) acm / origAlig->numberOfResidues);
                 y = refer;
                 utils::streamSVG(&x, &y, 0, &linename, &color, nullptr, nullptr);
                 refer = vectAux[i];
                 num = 1;
             } else num++;
         }
         acm++;
         x = ((float) acm / origAlig->numberOfResidues);
         y = refer;
         utils::streamSVG(&x, &y, 0, &linename, &color, nullptr, nullptr);
         // Deallocate the reserved memory.
         delete[] vectAux;
     }
     utils::streamSVG(nullptr, nullptr, 0, nullptr, nullptr, nullptr, nullptr);
 }
References statistics::Manager::calculateConservationStats(), statistics::Manager::calculateGapStats(), utils::copyVect(), statistics::Manager::gaps, i, infile, statistics::Gaps::maxGaps, statistics::Similarity::MDK, statistics::Similarity::MDK_Window, Alignment::numberOfResidues, Alignment::numberOfSequences, statistics::Gaps::numColumnsWithGaps, origAlig, utils::quicksort(), statistics::Manager::similarity, Alignment::Statistics, utils::streamSVG(), and svgStatsOutFile.
Referenced by perform(), and perform_VCF().
terminal_only_argument()
bool trimAlManager::terminal_only_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the terminal only argument.
Definition at line 631 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-terminalonly")) && (!terminalOnly)) {
         terminalOnly = true;
         return true;
     }
     return false;
 }
References i, and terminalOnly.
Referenced by parseArguments().
timetracker_out_argument()
bool trimAlManager::timetracker_out_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse InternalBenchmarker output argument.
Need to be checked before any other argument.
Definition at line 263 of file trimalManager.cpp.
{
     if ((!strcmp(argv[*i], "-timetrackerout")) && ((*i) + 1 != *argc)) {
         (*i) += 1;
         return true;
     }
     return false;
 }
References i.
Referenced by parseArguments().
vcf_argument()
bool trimAlManager::vcf_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse vcf argument.
Definition at line 226 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-vcf") && ((*i) + 1 != *argc) && (infile == nullptr)) {
         vcfs = new std::vector<std::string>();
         while (((*i) + 1 != *argc)) {
             ++*i;
             if (argv[*i][0] == '-') {
                 --*i;
                 break;
             }
             vcfs->emplace_back(argv[*i]);
         }
         return true;
     }
     return false;
 }
References i, infile, and vcfs.
Referenced by parseArguments().
verbosity_argument()
void trimAlManager::verbosity_argument (const int * argc, char * argv[]) inline private
Method to parse the verbosity argument.
This check is done before any other check.
This is due to trimAl not performing any action if any help argument has been provided.
.
Definition at line 166 of file trimalManager.cpp.
{
     for (int i = 1; i < *argc; i++) {
         if (!strcmp(argv[i], "--verbosity") || !strcmp(argv[i], "-v")) {
             if ((i + 1) != *argc) {
                 if (!strcmp(argv[i + 1], "error") || !strcmp(argv[i + 1], "3")) {
                     debug.Level = VerboseLevel::ERROR;
                     return;
                 }
                 if (!strcmp(argv[i + 1], "warning") || !strcmp(argv[i + 1], "2")) {
                     debug.Level = VerboseLevel::WARNING;
                     return;
                 }
                 if (!strcmp(argv[i + 1], "info") || !strcmp(argv[i + 1], "1")) {
                     debug.Level = VerboseLevel::INFO;
                     return;
                 }
                 if (!strcmp(argv[i + 1], "none") || !strcmp(argv[i + 1], "0")) {
                     debug.Level = VerboseLevel::NONE;
                     return;
                 }
                 debug.report(ErrorCode::VerboseLevelNotRecognized, new std::string[2]{argv[i + 1], std::to_string(debug.Level)});
             } else
                 debug.report(ErrorCode::NeedToSpecifyVerboseLevel, new std::string[2]{argv[i], std::to_string(debug.Level)});
         }
     }
 }
References debug, ERROR, i, INFO, reporting::reportManager::Level, NeedToSpecifyVerboseLevel, NONE, reporting::reportManager::report(), VerboseLevelNotRecognized, and WARNING.
Referenced by parseArguments().
window_argument()
bool trimAlManager::window_argument (const int * argc, char * argv[], int * currentArg) inline private
Method to parse the Window argument.
Definition at line 639 of file trimalManager.cpp.
{
     if (!strcmp(argv[*i], "-w") && ((*i) + 1 != *argc) && (windowSize == -1)) {
         if (utils::isNumber(argv[*i + 1])) {
             windowSize = atoi(argv[++*i]);
             if (windowSize <= 0) {
                 debug.report(ErrorCode::WindowValueOutOfRange);
                 appearErrors = true;
             }
         } else {
             debug.report(ErrorCode::WindowValueNotRecognized);
             appearErrors = true;
         }
         return true;
     }
     return false;
 }
References appearErrors, debug, i, utils::isNumber(), reporting::reportManager::report(), windowSize, WindowValueNotRecognized, and WindowValueOutOfRange.
Referenced by parseArguments().
Member Data Documentation
alternative_matrix
int trimAlManager::alternative_matrix = -1
Int that represents which alternative matrix to use, where '-1' means no alternative matrix, and '1' means degenerated_nt_identity.
Definition at line 80 of file trimalManager.h.
Referenced by create_or_use_similarity_matrix(), and matrix_argument().
appearErrors
bool trimAlManager::appearErrors = false
Flag to trace errors.
Definition at line 35 of file trimalManager.h.
Referenced by back_trans_argument(), block_argument(), check_and_prepare_coding_sequence(), check_arguments_incompatibilities(), check_arguments_needs(), check_automated_manual_incompatibilities(), check_automated_methods_incompatibilities(), check_backtranslation_infile_names_correspondence(), check_backtranslations(), check_block_size(), check_clusters_incompatibilities(), check_coding_sequences_type(), check_codon_behaviour_incompatibility(), check_col_numbering(), check_combinations_among_thresholds_incompatibility(), check_compareset_window_argument(), check_file_aligned(), check_force_selection(), check_inFile_incompatibilities(), check_input_file_with_coding_sequences_argument(), check_max_identity_incompatibilities(), check_output_file_with_statistics(), check_output_relevance(), check_outputs_coincidence(), check_residue_and_sequence_overlap(), check_select_cols_and_seqs_incompatibilities(), check_similarity_matrix(), check_stats_incompatibilities(), check_thresholds_incompatibilities(), check_windows_incompatibilities(), CleanResiduesNonAuto(), clusters_argument(), compareset_argument(), conservation_threshold_argument(), consistency_threshold_argument(), consistency_window_argument(), force_select_argument(), gap_threshold_argument(), gap_window_argument(), in_argument(), matrix_argument(), max_identity_argument(), output_reports(), parseArguments(), perform(), perform_VCF(), performCompareset(), processArguments(), residue_overlap_argument(), save_alignment(), select_cols_argument(), seqs_select_argument(), sequence_overlap_argument(), similarity_threshold_argument(), similarity_window_argument(), and window_argument().
argumentLength
int trimAlManager::argumentLength = size_t(-1)
Temp variable to use when there is a need to copy an argument to a char array.
Definition at line 87 of file trimalManager.h.
Referenced by back_trans_argument(), force_select_argument(), html_out_argument(), in_argument(), matrix_argument(), out_argument(), svg_out_argument(), and svg_stats_argument().
automated1
bool trimAlManager::automated1 = false
Flag to use the automated1 trimming method.
Definition at line 44 of file trimalManager.h.
Referenced by automated1_argument(), check_similarity_matrix(), CleanResiduesAuto(), create_or_use_similarity_matrix(), and processArguments().
automatedMethodCount
int trimAlManager::automatedMethodCount = -1
Integer counter of the automatic methods.
If the counter is bigger than 0, we are using an automatic method.
If the counter is bigger than 1, we are trying to use multiple automatic methods.
Definition at line 79 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_automated_methods_incompatibilities(), check_col_numbering(), check_file_aligned(), check_output_file_with_statistics(), check_output_relevance(), check_thresholds_incompatibilities(), clean_alignment(), and processArguments().
backtransFile
char trimAlManager::backtransFile = nullptr
File to load the alignment containing the backtranslation information.
Definition at line 110 of file trimalManager.h.
Referenced by back_trans_argument(), check_and_prepare_coding_sequence(), check_backtranslation_infile_names_correspondence(), check_backtranslations(), check_coding_sequences_type(), check_input_file_with_coding_sequences_argument(), delete_variables(), and postprocess_alignment().
backtranslationAlig
Alignment trimAlManager::backtranslationAlig = nullptr
Alignment used on the backtranslation functionality.
Definition at line 101 of file trimalManager.h.
Referenced by back_trans_argument(), check_and_prepare_coding_sequence(), check_backtranslation_infile_names_correspondence(), check_coding_sequences_type(), delete_variables(), and postprocess_alignment().
blockSize
int trimAlManager::blockSize = -1
Block Size to use while trimming.
Definition at line 76 of file trimalManager.h.
Referenced by block_argument(), check_block_size(), check_select_cols_and_seqs_incompatibilities(), check_thresholds_incompatibilities(), perform(), and perform_VCF().
c
char trimAlManager::c
Temporal char variable.
Definition at line 105 of file trimalManager.h.
clusters
int trimAlManager::clusters = -1
Number of most representative sequences we are going to use.
Definition at line 77 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_clusters_incompatibilities(), check_max_identity_incompatibilities(), check_output_relevance(), check_select_cols_and_seqs_incompatibilities(), CleanSequences(), and clusters_argument().
columnNumbering
bool trimAlManager::columnNumbering = false
Flag to return column numbering in report.
Definition at line 38 of file trimalManager.h.
Referenced by check_col_numbering(), check_stats_incompatibilities(), col_numbering_argument(), and perform().
compare
ifstream trimAlManager::compare
Temporal variable to open files in trimAlManager::check_multiple_files_comparison function.
Note
This could be moved there
Definition at line 94 of file trimalManager.h.
Referenced by compareset_argument().
compareAlignmentsArray
Alignment trimAlManager::compareAlignmentsArray = nullptr
Alignment Vector used on trimAlManager::check_multiple_files_comparison to compare them.
Note
This variable could be moved there.
Definition at line 102 of file trimalManager.h.
Referenced by delete_variables().
compareset
int trimAlManager::compareset = nullptr
Pointer to the argument that contains the compareset file.
Definition at line 117 of file trimalManager.h.
Referenced by check_compareset_window_argument(), check_force_selection(), check_inFile_incompatibilities(), check_input_file_with_coding_sequences_argument(), check_similarity_matrix(), compareset_argument(), parseArguments(), performCompareset(), and print_statistics().
conservationThreshold
float trimAlManager::conservationThreshold = -1
Similarity Threshold to use while trimming.
Definition at line 61 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_col_numbering(), check_combinations_among_thresholds_incompatibility(), check_output_file_with_statistics(), check_output_relevance(), check_thresholds_incompatibilities(), CleanResiduesNonAuto(), conservation_threshold_argument(), and perform().
consistencyThreshold
float trimAlManager::consistencyThreshold = -1
Consistency Threshold to use while trimming.
Definition at line 64 of file trimalManager.h.
Referenced by check_col_numbering(), check_combinations_among_thresholds_incompatibility(), check_file_aligned(), check_inFile_incompatibilities(), check_output_relevance(), check_thresholds_incompatibilities(), CleanResiduesNonAuto(), and consistency_threshold_argument().
consistencyWindow
int trimAlManager::consistencyWindow = -1
Consistency Window to use while trimming.
Definition at line 75 of file trimalManager.h.
Referenced by check_max_identity_incompatibilities(), check_similarity_matrix(), check_windows_incompatibilities(), consistency_window_argument(), and statistics::Consistency::perform().
CS
statistics::Consistency* trimAlManager::CS = nullptr
Consistency Manager. We have to save the reference, while it is still not part of an alignment
Definition at line 130 of file trimalManager.h.
Referenced by delete_variables(), statistics::Consistency::perform(), and performCompareset().
delColumns
int trimAlManager::delColumns = nullptr
Vector that contains the column indexes the user specified to be removed.
Definition at line 82 of file trimalManager.h.
Referenced by CleanResiduesNonAuto(), delete_variables(), and select_cols_argument().
delSequences
int trimAlManager::delSequences = nullptr
Vector that contains the sequence indexes the user specified to be removed.
Definition at line 83 of file trimalManager.h.
Referenced by check_select_cols_and_seqs_incompatibilities(), CleanSequences(), delete_variables(), and seqs_select_argument().
filesToCompare
char trimAlManager::filesToCompare = nullptr
Vector containing the files to compare in trimAlManager::check_multiple_files_comparison function.
Note
This variable could be moved there.
Definition at line 122 of file trimalManager.h.
Referenced by delete_variables().
forceFile
char trimAlManager::forceFile = nullptr
Forcefile to use in combination with multiple files comparison, to compare them against this.
Definition at line 106 of file trimalManager.h.
Referenced by check_force_selection(), check_inFile_incompatibilities(), check_input_file_with_coding_sequences_argument(), delete_variables(), force_select_argument(), and performCompareset().
formatManager
FormatManager trimAlManager::formatManager private
Read Write Machine that allows to manage formats easily.
Definition at line 247 of file trimalManager.h.
Referenced by back_trans_argument(), check_output_format(), force_select_argument(), help_arguments(), in_argument(), keep_header_argument(), menu(), perform_VCF(), performCompareset(), and save_alignment().
gappyout
bool trimAlManager::gappyout = false
Flag to use the gappyout trimming method.
Definition at line 41 of file trimalManager.h.
Referenced by CleanResiduesAuto(), gappy_out_argument(), and processArguments().
gapThreshold
float trimAlManager::gapThreshold = -1
Gap Threshold to use while trimming.
Definition at line 62 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_col_numbering(), check_combinations_among_thresholds_incompatibility(), check_file_aligned(), check_output_file_with_statistics(), check_output_relevance(), check_thresholds_incompatibilities(), CleanResiduesNonAuto(), and gap_threshold_argument().
gapWindow
int trimAlManager::gapWindow = -1
Gap Window Size to use while trimming.
Definition at line 73 of file trimalManager.h.
Referenced by check_automated_methods_incompatibilities(), check_max_identity_incompatibilities(), check_similarity_matrix(), check_windows_incompatibilities(), gap_window_argument(), and set_window_size().
getComplementary
bool trimAlManager::getComplementary = false
Flag to return the complementary alignment.
Definition at line 37 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), complementary_argument(), and postprocess_alignment().
htmlOutFile
char trimAlManager::htmlOutFile = nullptr
File to output the html report.
Definition at line 113 of file trimalManager.h.
Referenced by check_output_relevance(), check_outputs_coincidence(), delete_variables(), html_out_argument(), and output_reports().
i
int trimAlManager::i = 1
Argument Iterator Variable.
Definition at line 70 of file trimalManager.h.
Referenced by automated1_argument(), back_trans_argument(), block_argument(), check_inFile_incompatibilities(), check_outputs_coincidence(), check_select_cols_and_seqs_incompatibilities(), CleanResiduesNonAuto(), clusters_argument(), col_numbering_argument(), compareset_argument(), complementary_argument(), conservation_threshold_argument(), consistency_threshold_argument(), consistency_window_argument(), force_select_argument(), gap_threshold_argument(), gap_window_argument(), gappy_out_argument(), help_arguments(), html_out_argument(), ignore_stop_codon_argument(), in_argument(), keep_header_argument(), keep_seqs_argument(), matrix_argument(), max_identity_argument(), no_all_gaps_argument(), no_gaps_argument(), out_argument(), out_format_arguments(), parseArguments(), perform_VCF(), residue_overlap_argument(), select_cols_argument(), seqs_select_argument(), sequence_overlap_argument(), similarity_threshold_argument(), similarity_window_argument(), split_by_stop_codon_argument(), strict_argument(), strict_plus_argument(), svg_out_argument(), svg_stats_argument(), svg_stats_out(), terminal_only_argument(), timetracker_out_argument(), vcf_argument(), verbosity_argument(), and window_argument().
ignoreStopCodon
bool trimAlManager::ignoreStopCodon = false
Flag to use the Ignore Stop Codon option.
Definition at line 58 of file trimalManager.h.
Referenced by check_and_prepare_coding_sequence(), check_backtranslations(), check_codon_behaviour_incompatibility(), and ignore_stop_codon_argument().
infile
char trimAlManager::infile = nullptr
File to load the alignment when only one alignment has trimming interest.
Definition at line 108 of file trimalManager.h.
Referenced by check_file_aligned(), check_inFile_incompatibilities(), check_input_file_with_coding_sequences_argument(), check_output_format(), clean_alignment(), delete_variables(), in_argument(), parseArguments(), svg_stats_out(), and vcf_argument().
keepSeqs
bool trimAlManager::keepSeqs = false
Flag to keep sequences in the alignment.
Definition at line 57 of file trimalManager.h.
Referenced by keep_seqs_argument(), perform(), and perform_VCF().
line
char trimAlManager::line
Temporal variable to read lines from a file.
Definition at line 122 of file trimalManager.h.
matrixFile
char trimAlManager::matrixFile = nullptr
File that contains a user defined similarity matrix.
Definition at line 120 of file trimalManager.h.
Referenced by check_similarity_matrix(), create_or_use_similarity_matrix(), delete_variables(), and matrix_argument().
maxIdentity
float trimAlManager::maxIdentity = -1
Max Identity to use while trimming.
Definition at line 67 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_max_identity_incompatibilities(), check_output_relevance(), check_select_cols_and_seqs_incompatibilities(), CleanSequences(), and max_identity_argument().
noallgaps
bool trimAlManager::noallgaps = false
Flag to use the noallgaps option.
Definition at line 40 of file trimalManager.h.
Referenced by CleanResiduesAuto(), no_all_gaps_argument(), and processArguments().
nogaps
bool trimAlManager::nogaps = false
Flag to use the nogaps option.
Definition at line 39 of file trimalManager.h.
Referenced by CleanResiduesAuto(), no_gaps_argument(), and processArguments().
oformats
std::vector< std::string > trimAlManager::oformats
Formats names we are going to output our trimmed alignment.
Definition at line 125 of file trimalManager.h.
Referenced by check_output_format(), out_format_arguments(), statistics::Consistency::perform(), perform_VCF(), and save_alignment().
origAlig
Alignment trimAlManager::origAlig = nullptr
Main alignment used/loaded on trimAl in combination with singleAlig.
Definition at line 98 of file trimalManager.h.
Referenced by check_and_prepare_coding_sequence(), check_backtranslation_infile_names_correspondence(), check_backtranslations(), check_block_size(), check_clusters_incompatibilities(), check_file_aligned(), check_select_cols_and_seqs_incompatibilities(), clean_alignment(), CleanResiduesAuto(), CleanResiduesNonAuto(), CleanSequences(), create_or_use_similarity_matrix(), delete_variables(), force_select_argument(), in_argument(), output_reports(), statistics::Consistency::perform(), perform(), perform_VCF(), postprocess_alignment(), print_statistics(), set_window_size(), and svg_stats_out().
outfile
char trimAlManager::outfile = nullptr
File to output the trimmed alignment. This can contain tags which will be traduced to some variables:
[in] will be changed with the original filename.
[format] will be changed with the output format name specified.
[extension] will be changed to the correct format extension.
Definition at line 112 of file trimalManager.h.
Referenced by check_output_file_with_statistics(), check_outputs_coincidence(), delete_variables(), out_argument(), statistics::Consistency::perform(), perform_VCF(), and save_alignment().
residuesOverlap
float trimAlManager::residuesOverlap = -1
Residues Overlap to use while trimming.
Definition at line 65 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_file_aligned(), check_output_relevance(), check_residue_and_sequence_overlap(), CleanSequences(), and residue_overlap_argument().
selectCols
bool trimAlManager::selectCols = false
Flag to select columns manually from the alignment.
Definition at line 54 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_col_numbering(), check_file_aligned(), check_output_relevance(), check_select_cols_and_seqs_incompatibilities(), and select_cols_argument().
selectSeqs
bool trimAlManager::selectSeqs = false
Flag to select sequences manually from the alignment.
Definition at line 53 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_col_numbering(), check_file_aligned(), check_output_relevance(), check_select_cols_and_seqs_incompatibilities(), and seqs_select_argument().
sequenceOverlap
float trimAlManager::sequenceOverlap = -1
Sequence Overlap to use while trimming.
Definition at line 66 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_file_aligned(), check_output_relevance(), check_residue_and_sequence_overlap(), CleanSequences(), and sequence_overlap_argument().
sequencesLengths
int trimAlManager::sequencesLengths = nullptr
Vector that contains the sequences lengths of each sequence in the backtranslation option.
Note
This can be moved to trimAlManager::check_backtranslation_infile_names_correspondence() function or even deleted, as we don't really need to copy them in order to compare them with origAlig names.
Definition at line 84 of file trimalManager.h.
Referenced by check_backtranslation_infile_names_correspondence().
sequencesNames
string trimAlManager::sequencesNames = nullptr
Temporal variable to use in backtranslation option to compare with infile.
Note
This variable may be deleted, as we don't need to copy the sequences names to compare them.
Definition at line 90 of file trimalManager.h.
Referenced by check_backtranslation_infile_names_correspondence().
sfc
bool trimAlManager::sfc = false
Flag to show the Sum of Pairs scores per column.
Definition at line 49 of file trimalManager.h.
Referenced by check_inFile_incompatibilities(), print_statistics(), and stats_arguments().
sft
bool trimAlManager::sft = false
Flag to show the Accumulated Sum of Pairs.
Definition at line 50 of file trimalManager.h.
Referenced by check_inFile_incompatibilities(), print_statistics(), and stats_arguments().
sgc
bool trimAlManager::sgc = false
Flag to show the Gaps Scores per column.
Definition at line 45 of file trimalManager.h.
Referenced by print_statistics(), and stats_arguments().
sgt
bool trimAlManager::sgt = false
Flag to show the Accumulated Gaps Scores.
Definition at line 46 of file trimalManager.h.
Referenced by print_statistics(), and stats_arguments().
sident
bool trimAlManager::sident = false
Flag to show identity scores in the alignment.
Definition at line 51 of file trimalManager.h.
Referenced by print_statistics(), and stats_arguments().
similarityThreshold
float trimAlManager::similarityThreshold = -1
Similarity Threshold to use while trimming.
Definition at line 63 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), check_col_numbering(), check_combinations_among_thresholds_incompatibility(), check_file_aligned(), check_output_file_with_statistics(), check_output_relevance(), check_similarity_matrix(), check_thresholds_incompatibilities(), CleanResiduesNonAuto(), create_or_use_similarity_matrix(), and similarity_threshold_argument().
similarityWindow
int trimAlManager::similarityWindow = -1
Similarity Window to use while trimming.
Definition at line 74 of file trimalManager.h.
Referenced by check_automated_methods_incompatibilities(), check_max_identity_incompatibilities(), check_windows_incompatibilities(), set_window_size(), and similarity_window_argument().
similMatrix
similarityMatrix trimAlManager::similMatrix = nullptr
Temporal Similarity Matrix.
Definition at line 95 of file trimalManager.h.
Referenced by create_or_use_similarity_matrix(), and delete_variables().
singleAlig
Alignment trimAlManager::singleAlig = nullptr
Alignment obtained by making modifications to singleAlig or backtranslationAlig.
Definition at line 99 of file trimalManager.h.
Referenced by CleanResiduesAuto(), CleanResiduesNonAuto(), CleanSequences(), delete_variables(), output_reports(), perform(), postprocess_alignment(), and save_alignment().
soverlap
bool trimAlManager::soverlap = false
Flag to show overlap scores in the alignment.
Definition at line 52 of file trimalManager.h.
Referenced by print_statistics(), and stats_arguments().
splitByStopCodon
bool trimAlManager::splitByStopCodon = false
Flag to use the SplitByCodonStop option.
Definition at line 55 of file trimalManager.h.
Referenced by check_and_prepare_coding_sequence(), check_backtranslations(), check_codon_behaviour_incompatibility(), and split_by_stop_codon_argument().
ssc
bool trimAlManager::ssc = false
Flag to show the Similarity Scores per column.
Definition at line 47 of file trimalManager.h.
Referenced by check_similarity_matrix(), create_or_use_similarity_matrix(), print_statistics(), and stats_arguments().
sst
bool trimAlManager::sst = false
Flag to show the Accumulated Similarity Scores.
Definition at line 48 of file trimalManager.h.
Referenced by check_similarity_matrix(), create_or_use_similarity_matrix(), print_statistics(), and stats_arguments().
stats
int trimAlManager::stats = 0
Stats Flag to use in reporting. For each stat requested, this flag is decreased by one.
Definition at line 71 of file trimalManager.h.
Referenced by check_file_aligned(), check_output_file_with_statistics(), check_stats_incompatibilities(), statistics::Consistency::perform(), print_statistics(), and save_alignment().
strict
bool trimAlManager::strict = false
Flag to use the strict trimming method.
Definition at line 42 of file trimalManager.h.
Referenced by check_similarity_matrix(), CleanResiduesAuto(), create_or_use_similarity_matrix(), gappy_out_argument(), processArguments(), and strict_argument().
strictplus
bool trimAlManager::strictplus = false
Flag to use the strictplus trimming method.
Definition at line 43 of file trimalManager.h.
Referenced by check_similarity_matrix(), CleanResiduesAuto(), create_or_use_similarity_matrix(), processArguments(), and strict_plus_argument().
svgOutFile
char trimAlManager::svgOutFile = nullptr
File to output the svg report.
Definition at line 114 of file trimalManager.h.
Referenced by check_output_relevance(), check_outputs_coincidence(), delete_variables(), output_reports(), and svg_out_argument().
svgStatsOutFile
char trimAlManager::svgStatsOutFile = nullptr
File to output the svg graph showing the stats along the alignment.
Definition at line 115 of file trimalManager.h.
Referenced by check_output_relevance(), check_outputs_coincidence(), perform(), perform_VCF(), svg_stats_argument(), and svg_stats_out().
tempAlig
Alignment trimAlManager::tempAlig = nullptr
Temporal alignment that allows us to make some changes to trimAlManager::singleAlig, destroy it and set trimAlManager::singleAlig to this.
Definition at line 100 of file trimalManager.h.
Referenced by CleanResiduesAuto(), CleanResiduesNonAuto(), CleanSequences(), and postprocess_alignment().
terminalOnly
bool trimAlManager::terminalOnly = false
Flag to use the Terminal Only option.
Definition at line 56 of file trimalManager.h.
Referenced by check_automated_manual_incompatibilities(), perform(), perform_VCF(), postprocess_alignment(), and terminal_only_argument().
vcfs
std::vector<std::string>* trimAlManager::vcfs = nullptr
Definition at line 31 of file trimalManager.h.
Referenced by delete_variables(), perform(), perform_VCF(), and vcf_argument().
windowSize
int trimAlManager::windowSize = -1
Window Size to use while trimming.
Definition at line 72 of file trimalManager.h.
Referenced by check_automated_methods_incompatibilities(), check_compareset_window_argument(), check_max_identity_incompatibilities(), check_windows_incompatibilities(), statistics::Consistency::perform(), set_window_size(), and window_argument().
The documentation for this class was generated from the following files:
/home/vfernandez/git/trimAl/include/trimalManager.h
trimAlManager/trimAlManager-parseArguments.dox
trimAlManager/trimAlManager-processArguments.dox
trimAlManager/trimAlManager-variables.dox
trimAlManager/trimalManager.dox
/home/vfernandez/git/trimAl/source/trimalManager.cpp