trimAl: /home/vfernandez/git/trimAl/source/trimAlMain.cpp File Reference
trimAlMain.cpp File Reference
#include "InternalBenchmarker.h"
#include "trimalManager.h"
#include "reportsystem.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 31 of file trimAlMain.cpp.
{
     // We have to check the output parameter of the timerFactory
     //  before it's called the first time
     #if TimingReport
         timerFactory.checkOutputParameter(argc, argv);
     #endif
     // Debug tag to prevent Debug Messages to be printed on user side
     debug.IsDebug = true;
     // To allow timing the whole program, we must encapsulate
     //  inside it's own scope. Thus, we store the returnValue outside
     //  the scope.
     int returnValue;
     {
         // Create a BenchmarkSnapshot that will report times and/or memory usage
         // upon its destruction
         StartTiming("int main(int argc, char *argv[]) ");
         // Create trimAl Manager
         trimAlManager trimAl;
         trimAl.parseArguments(argc, argv);
         // Process them: Incompatibilities and co-dependencies
         trimAl.processArguments(argv);
         // Perform the required actions
         returnValue = trimAl.perform();
     }
     // Return the exit code obtained in the perform method.
     return returnValue;
 }
References reporting::reportManager::debug, reporting::reportManager::IsDebug, trimAlManager::parseArguments(), trimAlManager::perform(), trimAlManager::processArguments(), and StartTiming.